# Generated by Django 5.1.5 on 2026-02-15 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名稱')),
                ('code', models.CharField(help_text='唯一識別碼，用於程式中引用此流程', max_length=50, unique=True, verbose_name='流程代碼')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('reminder_hours', models.IntegerField(default=24, help_text='多久提醒一次未處理的核准', verbose_name='提醒間隔(小時)')),
                ('max_reminders', models.IntegerField(default=3, verbose_name='最多提醒次數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '工作流程模板',
                'verbose_name_plural': '工作流程模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='物件ID')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待核准'), ('RETURNED', '已退回'), ('APPROVED', '已核准'), ('REJECTED', '已拒絕'), ('CANCELLED', '已撤回')], default='DRAFT', max_length=20, verbose_name='狀態')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('submit_date', models.DateTimeField(blank=True, null=True, verbose_name='送出時間')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True, verbose_name='最後提醒時間')),
                ('reminder_count', models.IntegerField(default=0, verbose_name='已提醒次數')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='物件類型')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
            ],
            options={
                'verbose_name': '核准請求',
                'verbose_name_plural': '核准請求',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='發送時間')),
                ('reminder_number', models.IntegerField(verbose_name='第幾次提醒')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email已發送')),
                ('line_sent', models.BooleanField(default=False, verbose_name='Line已發送')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_reminders_received', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workflow.approvalrequest', verbose_name='核准請求')),
            ],
            options={
                'verbose_name': '提醒記錄',
                'verbose_name_plural': '提醒記錄',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='從1開始，數字越小越先執行', verbose_name='步驟順序')),
                ('step_name', models.CharField(help_text='例如：HR主管核准、總經理核准', max_length=100, verbose_name='步驟名稱')),
                ('approver_field', models.CharField(blank=True, help_text='從申請物件中動態取得核准者，例如：direct_supervisor', max_length=100, verbose_name='動態欄位')),
                ('can_approve', models.BooleanField(default=True, verbose_name='可核准')),
                ('can_reject', models.BooleanField(default=True, verbose_name='可拒絕')),
                ('can_return', models.BooleanField(default=True, verbose_name='可退回')),
                ('approver_role', models.ForeignKey(blank=True, help_text='指定群組，該群組的所有成員都可以核准', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='核准角色')),
                ('approver_user', models.ForeignKey(blank=True, help_text='指定特定使用者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_as_approver', to=settings.AUTH_USER_MODEL, verbose_name='指定人員')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowtemplate', verbose_name='所屬流程')),
            ],
            options={
                'verbose_name': '流程步驟',
                'verbose_name_plural': '流程步驟',
                'ordering': ['template', 'step_number'],
                'unique_together': {('template', 'step_number')},
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='當前步驟'),
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', '送出'), ('APPROVE', '核准'), ('REJECT', '拒絕'), ('RETURN', '退回'), ('CANCEL', '撤回'), ('RESUBMIT', '重新送出')], max_length=20, verbose_name='動作')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('comments', models.TextField(blank=True, verbose_name='簽核意見')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email已發送')),
                ('line_sent', models.BooleanField(default=False, verbose_name='Line已發送')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('actor_as_delegate', models.ForeignKey(blank=True, help_text='如果是代理人操作，此欄位記錄原核准者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_delegated_actions', to=settings.AUTH_USER_MODEL, verbose_name='代理身分')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.approvalrequest', verbose_name='核准請求')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep', verbose_name='流程步驟')),
            ],
            options={
                'verbose_name': '核准歷史',
                'verbose_name_plural': '核准歷史',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='ApproverDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='代理開始日期')),
                ('end_date', models.DateField(verbose_name='代理結束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL, verbose_name='代理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL, verbose_name='原核准者')),
                ('workflow_template', models.ForeignKey(blank=True, help_text='留空表示適用所有流程', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowtemplate', verbose_name='限定流程')),
            ],
            options={
                'verbose_name': '代理人設定',
                'verbose_name_plural': '代理人管理',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflowtemplate', verbose_name='工作流程'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_ap_content_21b21d_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status'], name='workflow_ap_status_2999e2_idx'),
        ),
    ]
