# Generated by Django 5.1.5 on 2026-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('merchant_trade_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='交易編號')),
                ('trade_date', models.DateTimeField(auto_now_add=True, verbose_name='交易時間')),
                ('total_amount', models.IntegerField(verbose_name='交易金額')),
                ('trade_desc', models.CharField(max_length=200, verbose_name='交易描述')),
                ('item_name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('rtn_code', models.IntegerField(default=0, help_text='1: 成功, 其他: 失敗/待付款', verbose_name='交易狀態碼')),
                ('rtn_msg', models.CharField(blank=True, max_length=200, verbose_name='交易訊息')),
                ('payment_type', models.CharField(choices=[('ECPay', '綠界科技'), ('NewebPay', '藍新金流')], default='ECPay', max_length=20, verbose_name='支付方式')),
                ('has_shipping', models.BooleanField(default=False, verbose_name='含運費')),
                ('related_app', models.CharField(blank=True, max_length=50, verbose_name='關聯App')),
                ('related_model', models.CharField(blank=True, max_length=50, verbose_name='關聯模型')),
                ('related_id', models.CharField(blank=True, max_length=50, verbose_name='關聯ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '交易紀錄',
                'verbose_name_plural': '交易紀錄',
                'ordering': ['-trade_date'],
            },
        ),
    ]
