# Generated by Django 5.1.5 on 2026-02-20 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0006_serviceitem_is_shareholder_list_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='科目代號')),
                ('name', models.CharField(max_length=100, verbose_name='科目名稱')),
                ('category', models.CharField(choices=[('ASSET', '資產'), ('LIABILITY', '負債'), ('EQUITY', '權益'), ('REVENUE', '營收'), ('EXPENSE', '費用')], max_length=20, verbose_name='類別')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '會計科目',
                'verbose_name_plural': '會計科目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True, verbose_name='傳票編號')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(blank=True, verbose_name='摘要')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('POSTED', '已過帳')], default='DRAFT', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '會計傳票',
                'verbose_name_plural': '會計傳票',
                'ordering': ['-date', '-voucher_no'],
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='借方')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='貸方')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='備註')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internal_accounting.account', verbose_name='科目')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.customer', verbose_name='客戶/對象')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='internal_accounting.voucher', verbose_name='傳票')),
            ],
            options={
                'verbose_name': '傳票分錄',
                'verbose_name_plural': '傳票分錄',
            },
        ),
    ]
