# Generated by Django 5.1.5 on 2026-02-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('assistant', models.CharField(blank=True, max_length=100, null=True, verbose_name='記帳助理')),
                ('assistant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='助理Email')),
                ('is_posted', models.BooleanField(default=False, verbose_name='已過帳')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('quotation_data', models.JSONField(blank=True, default=list, verbose_name='報價單明細')),
                ('cost_sharing_data', models.JSONField(blank=True, default=list, verbose_name='公費分攤')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '應收帳款',
                'verbose_name_plural': '應收帳款',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='收款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金額')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': '代收紀錄',
                'verbose_name_plural': '代收紀錄',
                'ordering': ['-date'],
            },
        ),
    ]
