# Generated by Django 5.1.5 on 2026-02-21 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0002_receivable_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='收款單號')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='收款日期')),
                ('method', models.CharField(choices=[('bank', '銀行存款'), ('ecpay', '綠界'), ('fee', '手續費'), ('bad_debt', '壞帳或折讓')], default='bank', max_length=20, verbose_name='收款方式')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='收款金額')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='扣繳稅款')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='手續費')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='壞帳或折讓')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='收款合計')),
                ('is_correction_needed', models.BooleanField(default=False, verbose_name='是否需補扣')),
                ('reporting_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='扣繳申報金額')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': '收款管理',
                'verbose_name_plural': '收款管理',
                'ordering': ['-date', '-collection_no'],
            },
        ),
    ]
