# Generated by Django 5.1.5 on 2026-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='receivable_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='應收帳款編號'),
        ),
    ]
