# Generated by Django 5.1.5 on 2026-02-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0004_receivable_receivable_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='method',
            field=models.CharField(choices=[('bank', '銀行存款'), ('ecpay', '綠界'), ('cash', '現金'), ('bad_debt', '壞帳或折讓'), ('other', '其他')], default='bank', max_length=20, verbose_name='收款方式'),
        ),
    ]
