# Generated by Django 5.1.5 on 2026-02-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('internal_accounting', '0005_alter_collection_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
