# Generated by Django 5.1.5 on 2026-02-22 06:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('internal_accounting', '0006_receivable_source_content_type_receivable_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('collection_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='收款單號')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='收款日期')),
                ('method', models.CharField(choices=[('bank', '銀行存款'), ('ecpay', '綠界'), ('cash', '現金'), ('bad_debt', '壞帳或折讓'), ('other', '其他')], default='bank', max_length=20, verbose_name='收款方式')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='收款金額')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='扣繳稅款')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='手續費')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='壞帳或折讓')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='收款合計')),
                ('is_correction_needed', models.BooleanField(default=False, verbose_name='是否需補扣')),
                ('reporting_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='扣繳申報金額')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': 'historical 收款管理',
                'verbose_name_plural': 'historical 收款管理',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReceivable',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('receivable_no', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='應收帳款編號')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('assistant', models.CharField(blank=True, max_length=100, null=True, verbose_name='記帳助理')),
                ('assistant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='助理Email')),
                ('is_posted', models.BooleanField(default=False, verbose_name='已過帳')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('quotation_data', models.JSONField(blank=True, default=list, verbose_name='報價單明細')),
                ('cost_sharing_data', models.JSONField(blank=True, default=list, verbose_name='公費分攤')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'historical 應收帳款',
                'verbose_name_plural': 'historical 應收帳款',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
