# Generated by Django 5.1.5 on 2026-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0007_collection_is_deleted_receivable_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='已過帳'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='已過帳'),
        ),
    ]
