# Generated by Django 5.1.5 on 2026-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0008_collection_is_posted_historicalcollection_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auxiliary_type',
            field=models.CharField(choices=[('NONE', '無'), ('PARTNER', '對象 (客戶/廠商/統編)'), ('DEPT', '部門'), ('PROJECT', '專案')], default='NONE', max_length=20, verbose_name='輔助核算類別'),
        ),
    ]
