# Generated by Django 5.1.5 on 2026-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0009_account_auxiliary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherdetail',
            name='customer',
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='對象/統編'),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='voucherdetail',
            name='project',
            field=models.CharField(blank=True, max_length=50, verbose_name='專案'),
        ),
    ]
