# Generated by Django 5.1.5 on 2026-02-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0010_remove_voucherdetail_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='傳票編號'),
        ),
    ]
