# Generated by Django 5.1.5 on 2026-02-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0012_voucher_is_deleted_voucher_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('ASSET', '資產'), ('LIABILITY', '負債'), ('EQUITY', '權益'), ('REVENUE', '營收'), ('COST', '成本'), ('EXPENSE', '費用'), ('NON_OP_INC', '營業外收入'), ('NON_OP_EXP', '營業外支出'), ('TAX', '所得稅費用')], max_length=20, verbose_name='類別'),
        ),
        migrations.CreateModel(
            name='VoucherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vouchers/%Y/%m/', verbose_name='圖片檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='internal_accounting.voucher', verbose_name='所屬傳票')),
            ],
            options={
                'verbose_name': '傳票夾檔圖片',
                'verbose_name_plural': '傳票夾檔圖片',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
