# Generated by Django 5.1.5 on 2026-02-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0013_alter_account_category_voucherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceivable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='客戶Email'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='客戶Email'),
        ),
    ]
