# Generated by Django 5.1.5 on 2026-02-24 06:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('internal_accounting', '0014_historicalreceivable_email_receivable_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReceivableFeeApportion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('task_description', models.CharField(blank=True, max_length=255, verbose_name='執行項目')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='分攤比例(%)')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='分攤金額')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='員工')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': 'historical 公費分攤明細',
                'verbose_name_plural': 'historical 公費分攤明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReceivableFeeApportion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('task_description', models.CharField(blank=True, max_length=255, verbose_name='執行項目')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='分攤比例(%)')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='分攤金額')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_apportions', to='hr.employee', verbose_name='員工')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_apportions', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': '公費分攤明細',
                'verbose_name_plural': '公費分攤明細',
                'ordering': ['id'],
            },
        ),
    ]
