# Generated by Django 6.0.2 on 2026-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0015_historicalreceivablefeeapportion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceivable',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='立帳日期'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='立帳日期'),
        ),
    ]
