# Generated by Django 5.1.5 on 2026-04-08 05:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0016_receivable_add_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('asset_no', models.CharField(max_length=50, unique=True, verbose_name='財產編號')),
                ('name', models.CharField(max_length=100, verbose_name='財產名稱')),
                ('purchase_date', models.DateField(verbose_name='取得日期')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='取得成本')),
                ('salvage_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='預估殘值')),
                ('useful_life_months', models.IntegerField(verbose_name='耐用月數')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='累計折舊')),
                ('status', models.CharField(choices=[('ACTIVE', '使用中'), ('SCRAPPED', '已報廢'), ('SOLD', '已出售')], default='ACTIVE', max_length=20, verbose_name='狀態')),
                ('depreciation_expense_account_code', models.CharField(blank=True, max_length=20, verbose_name='折舊費用科目')),
                ('accumulated_depreciation_account_code', models.CharField(blank=True, max_length=20, verbose_name='累計折舊科目')),
            ],
            options={
                'verbose_name': '財產目錄',
                'verbose_name_plural': '財產目錄',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='auxiliary_type',
            field=models.CharField(choices=[('NONE', '無'), ('PARTNER', '對象 (客戶/廠商/統編)'), ('DEPT', '部門'), ('PROJECT', '專案'), ('ASSET', '固定資產')], default='NONE', max_length=20, verbose_name='輔助核算類別'),
        ),
        migrations.AlterField(
            model_name='historicalvoucher',
            name='source',
            field=models.CharField(choices=[('MANUAL', '人工輸入'), ('SYSTEM', '系統拋轉'), ('YEAR_END_CLOSING', '年度結轉'), ('DEPRECIATION', '提列折舊')], default='MANUAL', max_length=20, verbose_name='來源'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='source',
            field=models.CharField(choices=[('MANUAL', '人工輸入'), ('SYSTEM', '系統拋轉'), ('YEAR_END_CLOSING', '年度結轉'), ('DEPRECIATION', '提列折舊')], default='MANUAL', max_length=20, verbose_name='來源'),
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('status', models.CharField(choices=[('OPEN', '開帳'), ('CLOSED', '已關帳')], default='OPEN', max_length=20, verbose_name='狀態')),
            ],
            options={
                'verbose_name': '會計期間',
                'verbose_name_plural': '會計期間',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccountingPeriod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('status', models.CharField(choices=[('OPEN', '開帳'), ('CLOSED', '已關帳')], default='OPEN', max_length=20, verbose_name='狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 會計期間',
                'verbose_name_plural': 'historical 會計期間',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFixedAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('asset_no', models.CharField(db_index=True, max_length=50, verbose_name='財產編號')),
                ('name', models.CharField(max_length=100, verbose_name='財產名稱')),
                ('purchase_date', models.DateField(verbose_name='取得日期')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='取得成本')),
                ('salvage_value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='預估殘值')),
                ('useful_life_months', models.IntegerField(verbose_name='耐用月數')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='累計折舊')),
                ('status', models.CharField(choices=[('ACTIVE', '使用中'), ('SCRAPPED', '已報廢'), ('SOLD', '已出售')], default='ACTIVE', max_length=20, verbose_name='狀態')),
                ('depreciation_expense_account_code', models.CharField(blank=True, max_length=20, verbose_name='折舊費用科目')),
                ('accumulated_depreciation_account_code', models.CharField(blank=True, max_length=20, verbose_name='累計折舊科目')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 財產目錄',
                'verbose_name_plural': 'historical 財產目錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
