# Generated by Django 5.1.5 on 2026-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0017_fixedasset_alter_account_auxiliary_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='壞帳或折讓'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='收款金額'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='手續費'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='reporting_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='扣繳申報金額'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='扣繳稅款'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='收款合計'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='壞帳或折讓'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='收款金額'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='手續費'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='reporting_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='扣繳申報金額'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='扣繳稅款'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='收款合計'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='貸方'),
        ),
        migrations.AlterField(
            model_name='voucherdetail',
            name='debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='借方'),
        ),
    ]
