# Generated by Django 6.0.2 on 2026-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0018_alter_collection_allowance_alter_collection_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='depreciation_done',
            field=models.BooleanField(default=False, verbose_name='已提列折舊'),
        ),
        migrations.AddField(
            model_name='historicalaccountingperiod',
            name='depreciation_done',
            field=models.BooleanField(default=False, verbose_name='已提列折舊'),
        ),
    ]
