# Generated by Django 6.0.2 on 2026-04-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0019_add_depreciation_done_to_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreceivable',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='receivable',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='collection',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='internal_accounting.voucher', verbose_name='對應傳票'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.voucher', verbose_name='對應傳票'),
        ),
        migrations.AlterField(
            model_name='historicalvoucher',
            name='source',
            field=models.CharField(choices=[('MANUAL', '人工輸入'), ('SYSTEM', '系統拋轉'), ('YEAR_END_CLOSING', '年度結轉'), ('DEPRECIATION', '提列折舊'), ('COLLECTION', '收款過帳')], default='MANUAL', max_length=20, verbose_name='來源'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='source',
            field=models.CharField(choices=[('MANUAL', '人工輸入'), ('SYSTEM', '系統拋轉'), ('YEAR_END_CLOSING', '年度結轉'), ('DEPRECIATION', '提列折舊'), ('COLLECTION', '收款過帳')], default='MANUAL', max_length=20, verbose_name='來源'),
        ),
    ]
