# Generated by Django 6.0.2 on 2026-04-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0020_refactor_collection_voucher_receivable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='綠界付款後由系統自動產生', verbose_name='系統自動建立'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='綠界付款後由系統自動產生', verbose_name='系統自動建立'),
        ),
        migrations.CreateModel(
            name='ReceivableNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_days', models.IntegerField(verbose_name='逾期閾值天數')),
                ('channel', models.CharField(choices=[('LINE', 'Line'), ('EMAIL', 'Email')], max_length=10, verbose_name='通知管道')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='發送時間')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': '逾期通知紀錄',
                'verbose_name_plural': '逾期通知紀錄',
                'ordering': ['-sent_at'],
                'unique_together': {('receivable', 'threshold_days', 'channel')},
            },
        ),
    ]
