# Generated by Django 6.0.2 on 2026-04-12 06:48

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('internal_accounting', '0021_add_receivable_notification_collection_auto_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPreCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('pre_collection_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='預收單號')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='收款日期')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='預收金額')),
                ('method', models.CharField(default='ecpay', max_length=20, verbose_name='收款方式')),
                ('transaction_no', models.CharField(blank=True, help_text='綠界 merchant_trade_no', max_length=100, null=True, verbose_name='交易編號')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='來源 ID')),
                ('status', models.CharField(choices=[('unmatched', '未核銷'), ('matched', '已核銷')], default='unmatched', max_length=20, verbose_name='狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_collection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.collection', verbose_name='核銷收款單')),
                ('matched_receivable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.receivable', verbose_name='核銷應收帳款')),
                ('source_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='來源類型')),
            ],
            options={
                'verbose_name': 'historical 預收款項',
                'verbose_name_plural': 'historical 預收款項',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PreCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('pre_collection_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='預收單號')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='收款日期')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='預收金額')),
                ('method', models.CharField(default='ecpay', max_length=20, verbose_name='收款方式')),
                ('transaction_no', models.CharField(blank=True, help_text='綠界 merchant_trade_no', max_length=100, null=True, verbose_name='交易編號')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='來源 ID')),
                ('status', models.CharField(choices=[('unmatched', '未核銷'), ('matched', '已核銷')], default='unmatched', max_length=20, verbose_name='狀態')),
                ('matched_collection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_collection', to='internal_accounting.collection', verbose_name='核銷收款單')),
                ('matched_receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_collections', to='internal_accounting.receivable', verbose_name='核銷應收帳款')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='來源類型')),
            ],
            options={
                'verbose_name': '預收款項',
                'verbose_name_plural': '預收款項',
                'ordering': ['-date', '-pre_collection_no'],
            },
        ),
    ]
