# Generated by Django 6.0.2 on 2026-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0022_pre_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprecollection',
            name='method',
            field=models.CharField(choices=[('ecpay', '綠界'), ('bank', '銀行存款'), ('cash', '現金'), ('other', '其他')], default='ecpay', max_length=20, verbose_name='收款方式'),
        ),
        migrations.AlterField(
            model_name='precollection',
            name='method',
            field=models.CharField(choices=[('ecpay', '綠界'), ('bank', '銀行存款'), ('cash', '現金'), ('other', '其他')], default='ecpay', max_length=20, verbose_name='收款方式'),
        ),
    ]
