# Generated by Django 6.0.2 on 2026-05-08 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0023_alter_historicalprecollection_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='收款日期'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='收款日期'),
        ),
        migrations.AlterField(
            model_name='historicalreceivable',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='historicalreceivable',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalvoucher',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='historicalvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('POSTED', '已過帳')], db_index=True, default='DRAFT', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('POSTED', '已過帳')], db_index=True, default='DRAFT', max_length=20, verbose_name='狀態'),
        ),
    ]
