# Generated by Django 6.0.2 on 2026-06-12 09:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_accounting', '0026_rename_account_111401_cathay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_five_digits', models.CharField(max_length=5, verbose_name='匯款帳號後五碼')),
                ('transfer_date', models.DateField(verbose_name='匯款日期')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='匯款金額')),
                ('status', models.CharField(choices=[('pending', '待核對'), ('confirmed', '已確認'), ('rejected', '不符')], db_index=True, default='pending', max_length=20, verbose_name='核對狀態')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_reports', to='internal_accounting.collection', verbose_name='確認後產生的收款單')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_reports', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': '銀行匯款回報',
                'verbose_name_plural': '銀行匯款回報',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankTransferReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('last_five_digits', models.CharField(max_length=5, verbose_name='匯款帳號後五碼')),
                ('transfer_date', models.DateField(verbose_name='匯款日期')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='匯款金額')),
                ('status', models.CharField(choices=[('pending', '待核對'), ('confirmed', '已確認'), ('rejected', '不符')], db_index=True, default='pending', max_length=20, verbose_name='核對狀態')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('collection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.collection', verbose_name='確認後產生的收款單')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='internal_accounting.receivable', verbose_name='應收帳款')),
            ],
            options={
                'verbose_name': 'historical 銀行匯款回報',
                'verbose_name_plural': 'historical 銀行匯款回報',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
