# Generated by Django 5.1.5 on 2026-02-10 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='document_templates/', verbose_name='模板檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('model_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='適用模型')),
            ],
            options={
                'verbose_name': '文件模板',
                'verbose_name_plural': '文件模板',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
