# Generated by Django 5.1.5 on 2026-02-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailtemplate_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
