# Generated by Django 5.1.5 on 2026-02-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emaillog_body_emaillog_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier', max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('flex', 'Flex Message')], default='text', max_length=20, verbose_name='Type')),
                ('text_content', models.TextField(blank=True, help_text='For Text Messages. Supports Jinja2 syntax.', verbose_name='Text Content')),
                ('flex_content_json', models.TextField(blank=True, help_text='For Flex Messages. Valid JSON structure.', verbose_name='Flex JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Line Template',
                'verbose_name_plural': 'Line Templates',
            },
        ),
        migrations.CreateModel(
            name='LineMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_line_id', models.CharField(max_length=100, verbose_name='Line User ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.linemessagetemplate')),
            ],
            options={
                'verbose_name': 'Line Log',
                'verbose_name_plural': 'Line Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
