# Generated by Django 5.1.5 on 2026-02-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_linemessagetemplate_linemessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='model_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Applicable Model'),
        ),
        migrations.AddField(
            model_name='linemessagetemplate',
            name='model_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Applicable Model'),
        ),
    ]
