# Generated by Django 6.0.2 on 2026-04-15 00:55

from django.db import migrations

BUSINESS_APPS = ['bookkeeping', 'administrative', 'basic_data']
HR_APPS = ['hr', 'basic_data']


def add_groups(apps, _schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    cpa, _    = Group.objects.get_or_create(name='CPA')
    a_grp, _  = Group.objects.get_or_create(name='A組')
    b_grp, _  = Group.objects.get_or_create(name='B組')
    c_grp, _  = Group.objects.get_or_create(name='C組')
    hr_grp, _ = Group.objects.get_or_create(name='人資組')

    # CPA gets all permissions (same as management)
    cpa.permissions.set(Permission.objects.all())

    # A/B/C teams get bookkeeping + administrative + basic_data permissions
    business_perms = Permission.objects.filter(content_type__app_label__in=BUSINESS_APPS)
    for grp in (a_grp, b_grp, c_grp):
        grp.permissions.set(business_perms)

    # HR team gets hr + basic_data permissions
    hr_perms = Permission.objects.filter(content_type__app_label__in=HR_APPS)
    hr_grp.permissions.set(hr_perms)

    # Ensure management group also has all permissions (it may already exist)
    management, _ = Group.objects.get_or_create(name='management')
    management.permissions.set(Permission.objects.all())


def remove_groups(apps, _schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ['CPA', 'A組', 'B組', 'C組', '人資組']:
        Group.objects.filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailtemplate_model_content_type_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups),
    ]
