# Generated by Django 5.1.5 on 2026-04-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_permission_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任務名稱')),
                ('command', models.CharField(help_text='Django management command 名稱（例如：send_remuneration_reminders）', max_length=100, verbose_name='管理指令')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('cron_schedule', models.CharField(blank=True, help_text='例如：0 9 1 * *（每月1號 09:00）— 雲端遷移時使用', max_length=100, verbose_name='Cron 表達式')),
                ('enabled', models.BooleanField(default=True, verbose_name='啟用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次執行時間')),
                ('last_status', models.CharField(choices=[('never', '尚未執行'), ('success', '成功'), ('error', '失敗')], default='never', max_length=10, verbose_name='上次狀態')),
                ('last_message', models.TextField(blank=True, verbose_name='上次執行訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '排程任務',
                'verbose_name_plural': '排程任務',
                'ordering': ['name'],
            },
        ),
    ]
