# Generated by Django 6.0.2 on 2026-07-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0016_alter_contact_name_alter_contact_tax_id_and_more'),
        ('core', '0010_resync_group_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_event_id', models.CharField(max_length=64, unique=True, verbose_name='事件 ID')),
                ('event_type', models.CharField(choices=[('message', 'Message'), ('join', 'Join'), ('follow', 'Follow')], max_length=20, verbose_name='事件類型')),
                ('sent_at', models.DateTimeField(db_index=True, verbose_name='發生時間')),
                ('source_type', models.CharField(max_length=10, verbose_name='來源類型')),
                ('room_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='RoomID')),
                ('sender_user_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='發話者 UserID')),
                ('message_type', models.CharField(blank=True, max_length=20, verbose_name='訊息類型')),
                ('text', models.TextField(blank=True, verbose_name='文字內容')),
                ('line_message_id', models.CharField(blank=True, max_length=64, verbose_name='訊息 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.customer', verbose_name='對應客戶')),
            ],
            options={
                'verbose_name': 'LINE 事件紀錄',
                'verbose_name_plural': 'LINE 事件紀錄',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['room_id', 'sent_at'], name='core_lineev_room_id_b2b0d9_idx'), models.Index(fields=['sender_user_id', 'sent_at'], name='core_lineev_sender__75176d_idx')],
            },
        ),
    ]
