"""
把當前 DB 的 MenuItem 狀態寫成新 migration 檔案。

工作流：
    1. 在 admin 調整選單（順序、文字、icon、permission 等）
    2. docker-compose exec web python manage.py snapshot_menus
    3. 產出 modules/system_config/migrations/00XX_snapshot_menus_YYYYMMDD.py
    4. 檢視生成的檔案、commit

設計重點：
- 用 (title, parent_title) 複合鍵 update_or_create（idempotent）
- 不刪除任何 MenuItem（避免誤刪手動加的）
- 若要刪除，請另寫 migration 用 ORM 直接 delete
"""
import datetime
import pprint
from pathlib import Path

from django.core.management.base import BaseCommand
from django.db import connection

from modules.system_config.models import MenuItem


MIGRATIONS_DIR = Path(__file__).resolve().parents[2] / 'migrations'


MIGRATION_TEMPLATE = '''"""
{description}

Auto-generated by `python manage.py snapshot_menus`
快照時間：{timestamp}
共 {count} 筆 MenuItem。

說明：
- 用 (title, parent_title) 複合鍵 update_or_create
- 不會刪除既有 MenuItem，只 upsert
- 重跑安全（idempotent）
"""
from django.db import migrations


MENU_ITEMS = {data}


def apply_snapshot(apps, schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')

    # 第一輪：top-level
    for item in MENU_ITEMS:
        if item['parent_title'] is None:
            MenuItem.objects.update_or_create(
                title=item['title'],
                parent=None,
                defaults={{
                    'url_name': item['url_name'],
                    'icon_svg': item['icon_svg'],
                    'order': item['order'],
                    'is_active': item['is_active'],
                    'required_permission': item['required_permission'],
                }},
            )

    # 第二輪：子項
    for item in MENU_ITEMS:
        if item['parent_title'] is None:
            continue
        parent = MenuItem.objects.filter(title=item['parent_title'], parent__isnull=True).first()
        if parent is None:
            continue
        MenuItem.objects.update_or_create(
            title=item['title'],
            parent=parent,
            defaults={{
                'url_name': item['url_name'],
                'icon_svg': item['icon_svg'],
                'order': item['order'],
                'is_active': item['is_active'],
                'required_permission': item['required_permission'],
            }},
        )


def noop(apps, schema_editor):
    """rollback 是 no-op（保留現狀）"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('system_config', '{prev_migration}'),
    ]
    operations = [
        migrations.RunPython(apply_snapshot, noop),
    ]
'''


def get_latest_migration_name():
    """找出 system_config 目前最後一支 migration 的 name (不含 .py)"""
    files = sorted(
        f.stem for f in MIGRATIONS_DIR.glob('[0-9]*.py')
    )
    if not files:
        raise RuntimeError('找不到 system_config migrations，無法接續')
    return files[-1]


def get_next_migration_number():
    """讀現有 migration 編號，回傳下一個 4 位數字串"""
    nums = []
    for f in MIGRATIONS_DIR.glob('[0-9]*.py'):
        try:
            nums.append(int(f.stem.split('_')[0]))
        except ValueError:
            continue
    if not nums:
        return '0001'
    return f'{max(nums) + 1:04d}'


def collect_menu_items():
    """從 DB 抓所有 MenuItem，轉為含 parent_title 的 dict 列表"""
    id_to_title = {m.id: m.title for m in MenuItem.objects.all()}
    items = []
    for m in MenuItem.objects.all().order_by('parent_id', 'order', 'id'):
        items.append({
            'title': m.title,
            'url_name': m.url_name,
            'icon_svg': m.icon_svg,
            'order': m.order,
            'is_active': m.is_active,
            'parent_title': id_to_title.get(m.parent_id) if m.parent_id else None,
            'required_permission': m.required_permission,
        })
    return items


class Command(BaseCommand):
    help = '把當前 DB 的 MenuItem 狀態寫成新 migration（捕捉 admin 調整）'

    def add_arguments(self, parser):
        parser.add_argument(
            '--name',
            default='snapshot_menus',
            help='migration 描述後綴（會接在編號後），預設 snapshot_menus',
        )
        parser.add_argument(
            '--description',
            default='MenuItem 狀態快照',
            help='migration docstring 第一行',
        )

    def handle(self, *args, **options):
        items = collect_menu_items()
        if not items:
            self.stdout.write(self.style.WARNING('DB 沒有任何 MenuItem，跳過'))
            return

        next_num = get_next_migration_number()
        prev_migration = get_latest_migration_name()
        suffix = options['name']
        date_part = datetime.date.today().strftime('%Y%m%d')
        filename = f'{next_num}_{suffix}_{date_part}.py'
        filepath = MIGRATIONS_DIR / filename

        if filepath.exists():
            self.stdout.write(self.style.ERROR(f'檔案已存在：{filepath}'))
            return

        data_literal = pprint.pformat(items, width=120, sort_dicts=False)
        content = MIGRATION_TEMPLATE.format(
            description=options['description'],
            timestamp=datetime.datetime.now().isoformat(timespec='seconds'),
            count=len(items),
            data=data_literal,
            prev_migration=prev_migration,
        )

        filepath.write_text(content, encoding='utf-8')

        self.stdout.write(self.style.SUCCESS(f'✓ 已產生：{filepath.relative_to(MIGRATIONS_DIR.parents[3])}'))
        self.stdout.write(f'  共 {len(items)} 筆 MenuItem')
        self.stdout.write(f'  依賴：{prev_migration}')
        self.stdout.write('')
        self.stdout.write('下一步：')
        self.stdout.write('  1. 檢視生成的檔案內容')
        self.stdout.write('  2. git add + commit')
        self.stdout.write('  3. （可選）rollback 測試：migrate system_config <prev>，再 migrate system_config')
