# Generated by Django 5.1.5 on 2026-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話號碼')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手機號碼')),
                ('source', models.CharField(choices=[('ESTABLISHED', '本所設立'), ('TRANSFERRED', '他所轉入')], default='ESTABLISHED', max_length=20, verbose_name='客戶來源')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='LineID')),
                ('room_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RoomID')),
                ('registered_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='登記地址-郵遞區號')),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='登記地址')),
                ('correspondence_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='通訊地址-郵遞區號')),
                ('correspondence_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('bank_account_last5', models.CharField(blank=True, max_length=5, null=True, verbose_name='帳號後五碼')),
                ('labor_ins_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='勞保代號')),
                ('health_ins_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='健保代號')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人 (預留)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '客戶資料',
                'verbose_name_plural': '客戶資料',
                'ordering': ['-created_at'],
            },
        ),
    ]
