# Generated by Django 5.1.5 on 2026-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0002_contact_historicalcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
    ]
