# Generated by Django 5.1.5 on 2026-02-09 11:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0003_contact_is_deleted_customer_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話號碼')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手機號碼')),
                ('source', models.CharField(choices=[('ESTABLISHED', '本所設立'), ('TRANSFERRED', '他所轉入')], default='ESTABLISHED', max_length=20, verbose_name='客戶來源')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='LineID')),
                ('room_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RoomID')),
                ('registered_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='登記地址-郵遞區號')),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='登記地址')),
                ('correspondence_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='通訊地址-郵遞區號')),
                ('correspondence_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('bank_account_last5', models.CharField(blank=True, max_length=5, null=True, verbose_name='帳號後五碼')),
                ('labor_ins_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='勞保代號')),
                ('health_ins_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='健保代號')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人 (預留)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 客戶資料',
                'verbose_name_plural': 'historical 客戶資料',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
