# Generated by Django 5.1.5 on 2026-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0004_historicalcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='服務項目編號')),
                ('department', models.IntegerField(choices=[(1, '簽證'), (2, '記帳'), (3, '登記'), (4, '代墊'), (5, '預收')], verbose_name='部門分類')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='服務項目名稱')),
                ('reference_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='參考公費')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_company_law_22_1', models.BooleanField(default=False, verbose_name='是否需申報公司法22-1')),
                ('is_money_laundering_check', models.BooleanField(default=False, verbose_name='是否執行洗錢防制法檢查')),
                ('is_business_entity_change', models.BooleanField(default=False, verbose_name='是否需營業人變更')),
            ],
            options={
                'verbose_name': '服務項目',
                'verbose_name_plural': '服務項目',
                'ordering': ['service_id'],
            },
        ),
    ]
