# Generated by Django 5.1.5 on 2026-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0005_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='is_shareholder_list_change',
            field=models.BooleanField(default=False, verbose_name='是否變更股東名簿'),
        ),
    ]
