# Generated by Django 5.1.5 on 2026-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0006_serviceitem_is_shareholder_list_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='更新時間'),
        ),
    ]
