# Generated by Django 5.1.5 on 2026-02-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0009_add_document_receipt_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentReceipt',
        ),
    ]
