# Generated by Django 5.1.5 on 2026-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0010_delete_documentreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(max_length=20, verbose_name='行業代號')),
                ('industry_name', models.CharField(max_length=100, verbose_name='行業名稱')),
                ('applicable_year', models.IntegerField(help_text='例如: 112, 113', verbose_name='適用起始年度')),
                ('book_review_profit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='擴大書審純益率(%)')),
                ('net_profit_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='淨利率(%)')),
                ('income_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='所得額標準(%)')),
            ],
            options={
                'verbose_name': '各業別稅率標準',
                'verbose_name_plural': '各業別稅率標準',
                'ordering': ['-applicable_year', 'industry_code'],
                'constraints': [models.UniqueConstraint(fields=('industry_code', 'applicable_year'), name='unique_industry_rate_per_year')],
            },
        ),
    ]
