# Generated by Django 5.1.5 on 2026-03-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0011_industrytaxrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndustryTaxRate',
        ),
    ]
