# Generated by Django 5.1.5 on 2026-03-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0012_delete_industrytaxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
