# Generated by Django 6.0.2 on 2026-03-23 23:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0013_customer_notes_historicalcustomer_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServiceItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('service_id', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='服務項目編號')),
                ('department', models.IntegerField(choices=[(1, '簽證'), (2, '記帳'), (3, '登記'), (4, '代墊'), (5, '預收')], verbose_name='部門分類')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='服務項目名稱')),
                ('reference_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='參考公費')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_company_law_22_1', models.BooleanField(default=False, verbose_name='是否需申報公司法22-1')),
                ('is_money_laundering_check', models.BooleanField(default=False, verbose_name='是否執行洗錢防制法檢查')),
                ('is_business_entity_change', models.BooleanField(default=False, verbose_name='是否需營業人變更')),
                ('is_shareholder_list_change', models.BooleanField(default=False, verbose_name='是否變更股東名簿')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 服務項目',
                'verbose_name_plural': 'historical 服務項目',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
