# Generated by Django 5.1.5 on 2026-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0014_historicalserviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_account_last5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='帳號後五碼'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手機號碼'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='電話號碼'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='bank_account_last5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='帳號後五碼'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手機號碼'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='電話號碼'),
        ),
    ]
