# Generated by Django 6.0.2 on 2026-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0015_alter_customer_bank_account_last5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
    ]
