# Generated by Django 6.0.2 on 2026-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0016_alter_contact_name_alter_contact_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='負責人姓名'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='負責人姓名'),
        ),
    ]
