# Generated by Django 5.1.5 on 2026-02-25 00:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('tax_registration_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='稅籍編號')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手機')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('correspondence_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='登記地址')),
                ('acceptance_status', models.CharField(choices=[('active', '承接中'), ('suspended', '停業中'), ('transferred', '轉出/解散')], default='active', max_length=20, verbose_name='承接狀態')),
                ('billing_status', models.CharField(choices=[('billing', '收費中'), ('stopped', '停止收費')], default='billing', max_length=20, verbose_name='計費狀態')),
                ('service_type', models.CharField(choices=[('vat_business', '營業人'), ('mixed_direct', '兼營營業人(直扣法)'), ('mixed_ratio', '兼營營業人(比例扣抵)'), ('investment', '專營投資公司'), ('professional', '執行業務'), ('other', '其他')], default='vat_business', max_length=20, verbose_name='提供服務')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('cost_sharing_data', models.JSONField(blank=True, default=list, verbose_name='公費分攤資料')),
                ('bookkeeping_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookkeeping_assistant_clients', to='hr.employee', verbose_name='記帳助理')),
                ('group_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookkeeping_group_clients', to='hr.employee', verbose_name='集團助理')),
            ],
            options={
                'verbose_name': '記帳客戶',
                'verbose_name_plural': '記帳客戶',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBookkeepingClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('tax_registration_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='稅籍編號')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手機')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('correspondence_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('registered_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='登記地址')),
                ('acceptance_status', models.CharField(choices=[('active', '承接中'), ('suspended', '停業中'), ('transferred', '轉出/解散')], default='active', max_length=20, verbose_name='承接狀態')),
                ('billing_status', models.CharField(choices=[('billing', '收費中'), ('stopped', '停止收費')], default='billing', max_length=20, verbose_name='計費狀態')),
                ('service_type', models.CharField(choices=[('vat_business', '營業人'), ('mixed_direct', '兼營營業人(直扣法)'), ('mixed_ratio', '兼營營業人(比例扣抵)'), ('investment', '專營投資公司'), ('professional', '執行業務'), ('other', '其他')], default='vat_business', max_length=20, verbose_name='提供服務')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('cost_sharing_data', models.JSONField(blank=True, default=list, verbose_name='公費分攤資料')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bookkeeping_assistant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='記帳助理')),
                ('group_assistant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='集團助理')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 記帳客戶',
                'verbose_name_plural': 'historical 記帳客戶',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
