# Generated by Django 5.1.5 on 2026-02-25 01:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_bookkeepingclient_historicalbookkeepingclient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='has_group_invoice',
            field=models.BooleanField(default=False, verbose_name='是否統購發票'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='has_group_invoice',
            field=models.BooleanField(default=False, verbose_name='是否統購發票'),
        ),
        migrations.CreateModel(
            name='HistoricalGroupInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('invoice_type', models.CharField(choices=[('two_copy', '二聯'), ('two_copy_sub', '二聯副'), ('three_copy', '三聯'), ('three_copy_sub', '三聯副'), ('special', '特種'), ('two_cashier', '二收銀'), ('three_cashier', '三收銀'), ('three_cashier_sub', '三收銀副')], max_length=20, verbose_name='發票類別')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='數量')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='記帳客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 統購發票',
                'verbose_name_plural': 'historical 統購發票',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GroupInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('invoice_type', models.CharField(choices=[('two_copy', '二聯'), ('two_copy_sub', '二聯副'), ('three_copy', '三聯'), ('three_copy_sub', '三聯副'), ('special', '特種'), ('two_cashier', '二收銀'), ('three_cashier', '三收銀'), ('three_cashier_sub', '三收銀副')], max_length=20, verbose_name='發票類別')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='數量')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invoices', to='bookkeeping.bookkeepingclient', verbose_name='記帳客戶')),
            ],
            options={
                'verbose_name': '統購發票',
                'verbose_name_plural': '統購發票',
                'ordering': ['invoice_type'],
                'unique_together': {('client', 'invoice_type')},
            },
        ),
    ]
