# Generated by Django 5.1.5 on 2026-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_bookkeepingclient_has_group_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='last_convenience_bag_date',
            field=models.DateField(blank=True, null=True, verbose_name='最後提供便利袋日期'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='last_convenience_bag_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='最後提供便利袋數量'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='receive_invoice_method',
            field=models.CharField(blank=True, choices=[('711_bag', '7-11便利袋'), ('client_post', '客戶自己寄送來'), ('in_person', '親收'), ('merge', '併同其他客戶'), ('courier', '快遞'), ('other', '其他')], max_length=20, null=True, verbose_name='收發票方式'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='receive_merged_client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='併同客戶名稱 (收發票)'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='send_invoice_method',
            field=models.CharField(blank=True, choices=[('post', '郵寄'), ('in_person', '親送'), ('keep', '自留'), ('merge', '併同其他客戶'), ('client_pickup', '客戶自己拿來'), ('other', '其他')], max_length=20, null=True, verbose_name='送發票方式'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='send_merged_client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='併同客戶名稱 (送發票)'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='last_convenience_bag_date',
            field=models.DateField(blank=True, null=True, verbose_name='最後提供便利袋日期'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='last_convenience_bag_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='最後提供便利袋數量'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='receive_invoice_method',
            field=models.CharField(blank=True, choices=[('711_bag', '7-11便利袋'), ('client_post', '客戶自己寄送來'), ('in_person', '親收'), ('merge', '併同其他客戶'), ('courier', '快遞'), ('other', '其他')], max_length=20, null=True, verbose_name='收發票方式'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='receive_merged_client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='併同客戶名稱 (收發票)'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='send_invoice_method',
            field=models.CharField(blank=True, choices=[('post', '郵寄'), ('in_person', '親送'), ('keep', '自留'), ('merge', '併同其他客戶'), ('client_pickup', '客戶自己拿來'), ('other', '其他')], max_length=20, null=True, verbose_name='送發票方式'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='send_merged_client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='併同客戶名稱 (送發票)'),
        ),
    ]
