# Generated by Django 5.1.5 on 2026-02-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_bookkeepingclient_last_convenience_bag_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('year', models.CharField(max_length=10, verbose_name='年度')),
                ('cd_rom', models.CharField(blank=True, max_length=50, verbose_name='光碟')),
                ('sales_invoice_qty', models.PositiveIntegerField(default=0, verbose_name='銷項發票數量')),
                ('receipt_form', models.FileField(blank=True, null=True, upload_to='bookkeeping_receipts/%Y/%m/', verbose_name='簽收單')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_book_logs', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '帳冊紀錄',
                'verbose_name_plural': '帳冊紀錄',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConvenienceBagLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenience_bag_logs', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '便利袋紀錄',
                'verbose_name_plural': '便利袋紀錄',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
