# Generated by Django 5.1.5 on 2026-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_accountingbooklog_conveniencebaglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='client_source',
            field=models.CharField(blank=True, choices=[('our_firm', '本所設立'), ('transferred', '他所轉入')], max_length=20, null=True, verbose_name='客戶來源'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='聯繫客戶日期'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='transfer_checklist',
            field=models.JSONField(blank=True, default=dict, verbose_name='移交檢查表'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='client_source',
            field=models.CharField(blank=True, choices=[('our_firm', '本所設立'), ('transferred', '他所轉入')], max_length=20, null=True, verbose_name='客戶來源'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='聯繫客戶日期'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='transfer_checklist',
            field=models.JSONField(blank=True, default=dict, verbose_name='移交檢查表'),
        ),
    ]
