# Generated by Django 5.1.5 on 2026-02-26 01:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_bookkeepingclient_client_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTaxFilingSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('form_type', models.CharField(choices=[('401', '401表 (一般稅額計算)'), ('403', '403表 (兼營營業人)'), ('404', '404表 (特種稅額計算)')], default='401', max_length=10, verbose_name='申報格式')),
                ('filing_frequency', models.CharField(choices=[('bimonthly', '單月申報 (每兩個月)'), ('monthly', '按月申報')], default='bimonthly', max_length=20, verbose_name='申報頻率')),
                ('is_audited', models.BooleanField(default=False, help_text='打勾代表此客戶後續營所稅或相關申報為查帳申報', verbose_name='查帳申報')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 營業稅申報設定',
                'verbose_name_plural': 'historical 營業稅申報設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxFilingYear',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('year', models.PositiveIntegerField(verbose_name='年度(民國)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 營業稅申報年度',
                'verbose_name_plural': 'historical 營業稅申報年度',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxFilingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('form_type', models.CharField(choices=[('401', '401表 (一般稅額計算)'), ('403', '403表 (兼營營業人)'), ('404', '404表 (特種稅額計算)')], default='401', max_length=10, verbose_name='申報格式')),
                ('filing_frequency', models.CharField(choices=[('bimonthly', '單月申報 (每兩個月)'), ('monthly', '按月申報')], default='bimonthly', max_length=20, verbose_name='申報頻率')),
                ('is_audited', models.BooleanField(default=False, help_text='打勾代表此客戶後續營所稅或相關申報為查帳申報', verbose_name='查帳申報')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_setting', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '營業稅申報設定',
                'verbose_name_plural': '營業稅申報設定',
            },
        ),
        migrations.CreateModel(
            name='TaxFilingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('year', models.PositiveIntegerField(verbose_name='年度(民國)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_years', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '營業稅申報年度',
                'verbose_name_plural': '營業稅申報年度',
                'ordering': ['-year'],
                'unique_together': {('client', 'year')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalTaxFilingPeriod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('period_start_month', models.PositiveIntegerField(help_text='例如填寫1代表1-2月期，填寫3代表3-4月期', verbose_name='期別(起月)')),
                ('sales_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷售額')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='稅額')),
                ('input_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='進項稅額')),
                ('retained_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='留抵稅額')),
                ('payable_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應納(退)稅額')),
                ('is_filed', models.BooleanField(default=False, verbose_name='是否已申報')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='申報日期')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.taxfilingyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': 'historical 營業稅申報明細',
                'verbose_name_plural': 'historical 營業稅申報明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxFilingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('period_start_month', models.PositiveIntegerField(help_text='例如填寫1代表1-2月期，填寫3代表3-4月期', verbose_name='期別(起月)')),
                ('sales_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷售額')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='稅額')),
                ('input_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='進項稅額')),
                ('retained_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='留抵稅額')),
                ('payable_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應納(退)稅額')),
                ('is_filed', models.BooleanField(default=False, verbose_name='是否已申報')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='申報日期')),
                ('year_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='bookkeeping.taxfilingyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': '營業稅申報明細',
                'verbose_name_plural': '營業稅申報明細',
                'ordering': ['year_record__year', 'period_start_month'],
                'unique_together': {('year_record', 'period_start_month')},
            },
        ),
    ]
