# Generated by Django 5.1.5 on 2026-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_historicaltaxfilingsetting_historicaltaxfilingyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='business_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='營業人密碼'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='e_invoice_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電子發票帳號'),
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='e_invoice_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電子發票密碼'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='business_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='營業人密碼'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='e_invoice_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電子發票帳號'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='e_invoice_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='電子發票密碼'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingsetting',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('line', 'Line'), ('email', 'Email'), ('both', 'Line + Email')], max_length=10, null=True, verbose_name='通知方式'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingsetting',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款')], max_length=20, null=True, verbose_name='預設繳稅方式'),
        ),
        migrations.AddField(
            model_name='taxfilingsetting',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('line', 'Line'), ('email', 'Email'), ('both', 'Line + Email')], max_length=10, null=True, verbose_name='通知方式'),
        ),
        migrations.AddField(
            model_name='taxfilingsetting',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款')], max_length=20, null=True, verbose_name='預設繳稅方式'),
        ),
        migrations.AlterField(
            model_name='historicaltaxfilingsetting',
            name='filing_frequency',
            field=models.CharField(choices=[('bimonthly', '單月申報 (每兩個月)'), ('monthly', '按月申報 (每一個月)')], default='bimonthly', max_length=20, verbose_name='申報頻率'),
        ),
        migrations.AlterField(
            model_name='taxfilingsetting',
            name='filing_frequency',
            field=models.CharField(choices=[('bimonthly', '單月申報 (每兩個月)'), ('monthly', '按月申報 (每一個月)')], default='bimonthly', max_length=20, verbose_name='申報頻率'),
        ),
    ]
