# Generated by Django 5.1.5 on 2026-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0008_bookkeepingclient_business_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='filing_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='申報書及稅單'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('auto_replied', '自動回覆'), ('manually_replied', '人工回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='input_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='進項金額'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='media_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='媒體檔'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='period_payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣繳'), ('no_payment', '不用繳納')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='reply_method',
            field=models.CharField(blank=True, choices=[('auto', '自動回覆'), ('manual', '人工回覆')], max_length=10, null=True, verbose_name='回覆方式'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='reply_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回覆時間'),
        ),
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='tax_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='繳稅截止日'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='filing_document',
            field=models.FileField(blank=True, null=True, upload_to='vat_filings/documents/', verbose_name='申報書及稅單'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('auto_replied', '自動回覆'), ('manually_replied', '人工回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='input_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='進項金額'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='vat_filings/media/', verbose_name='媒體檔'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='period_payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣繳'), ('no_payment', '不用繳納')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='reply_method',
            field=models.CharField(blank=True, choices=[('auto', '自動回覆'), ('manual', '人工回覆')], max_length=10, null=True, verbose_name='回覆方式'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='reply_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回覆時間'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='tax_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='繳稅截止日'),
        ),
        migrations.AlterField(
            model_name='historicaltaxfilingperiod',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷項稅額'),
        ),
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷項稅額'),
        ),
    ]
