# Generated by Django 5.1.5 on 2026-02-26 13:29 (manually edited to fix unique UUID backfill)

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """Backfill unique UUIDs for any existing TaxFilingPeriod rows."""
    TaxFilingPeriod = apps.get_model('bookkeeping', 'TaxFilingPeriod')
    for period in TaxFilingPeriod.objects.all():
        period.confirm_token = uuid.uuid4()
        period.save(update_fields=['confirm_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_historicaltaxfilingperiod_filing_document_and_more'),
    ]

    operations = [
        # 1. Historical table (simple add, no unique constraint needed)
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='confirm_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='確認Token'),
        ),
        # 2. Real table: add WITHOUT unique constraint first
        migrations.AddField(
            model_name='taxfilingperiod',
            name='confirm_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='確認Token'),
        ),
        # 3. Backfill unique UUIDs for existing rows
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # 4. Now add the unique constraint
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='confirm_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='確認Token'),
        ),
    ]
