# Generated by Django 5.1.5 on 2026-02-27 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_historicaltaxfilingperiod_confirm_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='綁定供外部客戶登入的帳號', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookkeeping_client_profile', to=settings.AUTH_USER_MODEL, verbose_name='綁定帳號'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='綁定供外部客戶登入的帳號', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='綁定帳號'),
        ),
    ]
