# Generated by Django 5.1.5 on 2026-02-27 12:05

import modules.bookkeeping.models.business_tax
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_bookkeepingclient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='filing_document',
            field=models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.business_tax.get_vat_document_path, verbose_name='申報書及稅單'),
        ),
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.business_tax.get_vat_media_path, verbose_name='媒體檔'),
        ),
    ]
