# Generated by Django 5.1.5 on 2026-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0012_alter_taxfilingperiod_filing_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='invoice_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='收到發票日期'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='invoice_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='收到發票日期'),
        ),
    ]
