# Generated by Django 5.1.5 on 2026-02-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0013_historicaltaxfilingperiod_invoice_received_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='national_tax_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='營業人(國稅局)密碼'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='national_tax_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='營業人(國稅局)密碼'),
        ),
        migrations.AlterField(
            model_name='bookkeepingclient',
            name='business_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='記帳客戶登入密碼'),
        ),
        migrations.AlterField(
            model_name='historicalbookkeepingclient',
            name='business_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='記帳客戶登入密碼'),
        ),
    ]
