# Generated by Django 5.1.5 on 2026-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0015_dividendtax_historicaldividendtax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovisionaltax',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='暫繳免繳的檢查項目', verbose_name='免繳檢查表'),
        ),
        migrations.AddField(
            model_name='provisionaltax',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='暫繳免繳的檢查項目', verbose_name='免繳檢查表'),
        ),
        migrations.AlterField(
            model_name='dividendtax',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='historicaldividendtax',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='historicalincometaxfiling',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='historicalincometaxsetting',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='預設繳稅方式'),
        ),
        migrations.AlterField(
            model_name='historicalprovisionaltax',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='historicalwithholdingtax',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='incometaxfiling',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='incometaxsetting',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='預設繳稅方式'),
        ),
        migrations.AlterField(
            model_name='provisionaltax',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
        migrations.AlterField(
            model_name='withholdingtax',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('self_pay', '自行繳納'), ('office_pay', '事務所代繳'), ('auto_debit', '自動扣款'), ('no_payment', '不用繳稅')], max_length=20, null=True, verbose_name='繳稅方式'),
        ),
    ]
