# Generated by Django 5.1.5 on 2026-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0016_historicalprovisionaltax_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendtax',
            name='client_feedback',
            field=models.TextField(blank=True, verbose_name='客戶回覆'),
        ),
        migrations.AddField(
            model_name='dividendtax',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('disputed', '有異議')], default='pending', max_length=20, verbose_name='確認狀態'),
        ),
        migrations.AddField(
            model_name='dividendtax',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認時間'),
        ),
        migrations.AddField(
            model_name='dividendtax',
            name='import_date',
            field=models.DateField(blank=True, null=True, verbose_name='匯入基準日'),
        ),
        migrations.AddField(
            model_name='historicaldividendtax',
            name='client_feedback',
            field=models.TextField(blank=True, verbose_name='客戶回覆'),
        ),
        migrations.AddField(
            model_name='historicaldividendtax',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('disputed', '有異議')], default='pending', max_length=20, verbose_name='確認狀態'),
        ),
        migrations.AddField(
            model_name='historicaldividendtax',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認時間'),
        ),
        migrations.AddField(
            model_name='historicaldividendtax',
            name='import_date',
            field=models.DateField(blank=True, null=True, verbose_name='匯入基準日'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='face_value',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10, verbose_name='面額'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='imputation_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='股東可扣抵稅額'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='insurance_base',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='負責人身分投保金額'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='personal_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='個人稅率 (%)'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='share_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='金額'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='stock_type',
            field=models.CharField(blank=True, default='COMMON', max_length=20, verbose_name='股票種類'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='supplement_premium',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='補充保費'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='supplement_premium_rate',
            field=models.DecimalField(decimal_places=2, default=2.11, max_digits=5, verbose_name='補充保費稅率 (%)'),
        ),
        migrations.AddField(
            model_name='historicalshareholderdividend',
            name='total_tax_premium',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='個人稅+補充保費'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='face_value',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10, verbose_name='面額'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='imputation_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='股東可扣抵稅額'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='insurance_base',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='負責人身分投保金額'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='personal_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='個人稅率 (%)'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='share_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='金額'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='stock_type',
            field=models.CharField(blank=True, default='COMMON', max_length=20, verbose_name='股票種類'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='supplement_premium',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='補充保費'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='supplement_premium_rate',
            field=models.DecimalField(decimal_places=2, default=2.11, max_digits=5, verbose_name='補充保費稅率 (%)'),
        ),
        migrations.AddField(
            model_name='shareholderdividend',
            name='total_tax_premium',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='個人稅+補充保費'),
        ),
        migrations.AlterField(
            model_name='historicalshareholderdividend',
            name='share_count',
            field=models.IntegerField(default=0, verbose_name='股數'),
        ),
        migrations.AlterField(
            model_name='historicalshareholderdividend',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='個人所得稅'),
        ),
        migrations.AlterField(
            model_name='shareholderdividend',
            name='share_count',
            field=models.IntegerField(default=0, verbose_name='股數'),
        ),
        migrations.AlterField(
            model_name='shareholderdividend',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='個人所得稅'),
        ),
    ]
