# Generated by Django 5.1.5 on 2026-03-01 06:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0017_dividendtax_client_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwithholdingdetail',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingdetail',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='類別名稱'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingdetail',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='證號'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingdetail',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='身分證字號'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingdetail',
            name='lease_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='租賃編號'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingdetail',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingtax',
            name='interest_income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='利息收入'),
        ),
        migrations.AddField(
            model_name='historicalwithholdingtax',
            name='salary_payment_method',
            field=models.CharField(blank=True, choices=[('beginning', '月初'), ('end', '月底')], max_length=20, null=True, verbose_name='薪資發放方式'),
        ),
        migrations.AddField(
            model_name='withholdingdetail',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='withholdingdetail',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='類別名稱'),
        ),
        migrations.AddField(
            model_name='withholdingdetail',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='證號'),
        ),
        migrations.AddField(
            model_name='withholdingdetail',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='身分證字號'),
        ),
        migrations.AddField(
            model_name='withholdingdetail',
            name='lease_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='租賃編號'),
        ),
        migrations.AddField(
            model_name='withholdingdetail',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='withholdingtax',
            name='interest_income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='利息收入'),
        ),
        migrations.AddField(
            model_name='withholdingtax',
            name='salary_payment_method',
            field=models.CharField(blank=True, choices=[('beginning', '月初'), ('end', '月底')], max_length=20, null=True, verbose_name='薪資發放方式'),
        ),
        migrations.AlterField(
            model_name='historicalwithholdingdetail',
            name='income_category',
            field=models.CharField(choices=[('salary', '薪資所得'), ('professional', '執行業務所得'), ('rental', '租金所得'), ('interest', '利息所得'), ('other', '其他所得')], default='salary', max_length=20, verbose_name='所得類別'),
        ),
        migrations.AlterField(
            model_name='historicalwithholdingdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='申報總額'),
        ),
        migrations.AlterField(
            model_name='withholdingdetail',
            name='income_category',
            field=models.CharField(choices=[('salary', '薪資所得'), ('professional', '執行業務所得'), ('rental', '租金所得'), ('interest', '利息所得'), ('other', '其他所得')], default='salary', max_length=20, verbose_name='所得類別'),
        ),
        migrations.AlterField(
            model_name='withholdingdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='申報總額'),
        ),
        migrations.CreateModel(
            name='HistoricalWithholdingMonthlyBreakdown',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('period', models.CharField(choices=[('prev_bonus', '前期年終'), ('prev_salary', '前期薪資'), ('m01', '1月'), ('m02', '2月'), ('m03', '3月'), ('m04', '4月'), ('m05', '5月'), ('m06', '6月'), ('m07', '7月'), ('m08', '8月'), ('m09', '9月'), ('m10', '10月'), ('m11', '11月'), ('m12', '12月'), ('cur_bonus', '當期年終'), ('dragon_boat', '端午獎金'), ('mid_autumn', '中秋獎金')], max_length=20, verbose_name='期間')),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='薪資')),
                ('retirement_contribution', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='退休金自提')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='稅額')),
                ('meal_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='伙食費')),
                ('overtime_pay', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='加班費')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('detail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.withholdingdetail', verbose_name='所屬扣繳明細')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 扣繳月分明細',
                'verbose_name_plural': 'historical 扣繳月分明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WithholdingMonthlyBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('period', models.CharField(choices=[('prev_bonus', '前期年終'), ('prev_salary', '前期薪資'), ('m01', '1月'), ('m02', '2月'), ('m03', '3月'), ('m04', '4月'), ('m05', '5月'), ('m06', '6月'), ('m07', '7月'), ('m08', '8月'), ('m09', '9月'), ('m10', '10月'), ('m11', '11月'), ('m12', '12月'), ('cur_bonus', '當期年終'), ('dragon_boat', '端午獎金'), ('mid_autumn', '中秋獎金')], max_length=20, verbose_name='期間')),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='薪資')),
                ('retirement_contribution', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='退休金自提')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='稅額')),
                ('meal_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='伙食費')),
                ('overtime_pay', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='加班費')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_breakdowns', to='bookkeeping.withholdingdetail', verbose_name='所屬扣繳明細')),
            ],
            options={
                'verbose_name': '扣繳月分明細',
                'verbose_name_plural': '扣繳月分明細',
                'ordering': ['period'],
                'unique_together': {('detail', 'period')},
            },
        ),
    ]
