# Generated by Django 5.1.5 on 2026-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0018_historicalwithholdingdetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincometaxfiling',
            name='media_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='媒體檔'),
        ),
        migrations.AddField(
            model_name='incometaxfiling',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='income_tax/media/', verbose_name='媒體檔'),
        ),
        migrations.AlterField(
            model_name='historicalincometaxfiling',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='JSON 結構，存放各檢查項目及備註', verbose_name='稅法檢查表'),
        ),
        migrations.AlterField(
            model_name='incometaxfiling',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='JSON 結構，存放各檢查項目及備註', verbose_name='稅法檢查表'),
        ),
    ]
