# Generated by Django 5.1.5 on 2026-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0019_historicalincometaxfiling_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincometaxfiling',
            name='reconciliation',
            field=models.JSONField(blank=True, default=list, help_text='JSON list，存放扣繳調節表各列資料', verbose_name='扣繳調節表'),
        ),
        migrations.AddField(
            model_name='incometaxfiling',
            name='reconciliation',
            field=models.JSONField(blank=True, default=list, help_text='JSON list，存放扣繳調節表各列資料', verbose_name='扣繳調節表'),
        ),
    ]
