# Generated by Django 5.1.5 on 2026-03-06 04:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0020_historicalincometaxfiling_reconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('period_start_month', models.PositiveIntegerField(help_text='例如填寫1代表1-2月期，填寫3代表3-4月期', verbose_name='期別(起月)')),
                ('account_status', models.CharField(choices=[('not_started', '尚未處理'), ('in_progress', '處理中'), ('waiting_docs', '缺憑證等待中'), ('completed', '處理完成')], default='not_started', max_length=20, verbose_name='處理進度')),
                ('accounting_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('sales_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷售額')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷項稅額')),
                ('input_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='進項稅額')),
                ('payable_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應納(退)稅額')),
                ('filing_status', models.CharField(choices=[('not_filed', '尚未申報'), ('filed', '已申報')], default='not_filed', max_length=20, verbose_name='申報狀態')),
            ],
            options={
                'verbose_name': '記帳進度明細',
                'verbose_name_plural': '記帳進度明細',
                'ordering': ['year_record__year', 'period_start_month'],
            },
        ),
        migrations.CreateModel(
            name='BookkeepingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_setting', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '記帳進度設定',
                'verbose_name_plural': '記帳進度設定',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('year', models.PositiveIntegerField(verbose_name='年度(民國)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_years', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '記帳年度',
                'verbose_name_plural': '記帳年度',
                'ordering': ['-year'],
                'unique_together': {('client', 'year')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalBookkeepingPeriod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('period_start_month', models.PositiveIntegerField(help_text='例如填寫1代表1-2月期，填寫3代表3-4月期', verbose_name='期別(起月)')),
                ('account_status', models.CharField(choices=[('not_started', '尚未處理'), ('in_progress', '處理中'), ('waiting_docs', '缺憑證等待中'), ('completed', '處理完成')], default='not_started', max_length=20, verbose_name='處理進度')),
                ('accounting_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('sales_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷售額')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='銷項稅額')),
                ('input_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='進項稅額')),
                ('payable_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應納(退)稅額')),
                ('filing_status', models.CharField(choices=[('not_filed', '尚未申報'), ('filed', '已申報')], default='not_filed', max_length=20, verbose_name='申報狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': 'historical 記帳進度明細',
                'verbose_name_plural': 'historical 記帳進度明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBookkeepingSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 記帳進度設定',
                'verbose_name_plural': 'historical 記帳進度設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBookkeepingYear',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('year', models.PositiveIntegerField(verbose_name='年度(民國)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 記帳年度',
                'verbose_name_plural': 'historical 記帳年度',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.AddField(
            model_name='bookkeepingperiod',
            name='year_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='bookkeeping.bookkeepingyear', verbose_name='所屬年度'),
        ),
        migrations.AlterUniqueTogether(
            name='bookkeepingperiod',
            unique_together={('year_record', 'period_start_month')},
        ),
    ]
