# Generated by Django 5.1.5 on 2026-03-07 07:13

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0021_bookkeepingperiod_bookkeepingsetting_bookkeepingyear_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('bill_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='帳單編號')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('bill_date', models.DateField(default=django.utils.timezone.now, verbose_name='開立日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='應繳日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('issued', '已開立'), ('paid', '已收款'), ('overdue', '逾期'), ('void', '已作廢')], default='draft', max_length=20, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='合計金額')),
                ('is_ar_transferred', models.BooleanField(default=False, verbose_name='已拋轉AR')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bookkeeping.bookkeepingclient', verbose_name='記帳客戶')),
            ],
            options={
                'verbose_name': '客戶帳單',
                'verbose_name_plural': '客戶帳單',
                'ordering': ['-year', '-month'],
                'unique_together': {('client', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalClientBill',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('bill_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='帳單編號')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('bill_date', models.DateField(default=django.utils.timezone.now, verbose_name='開立日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='應繳日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('issued', '已開立'), ('paid', '已收款'), ('overdue', '逾期'), ('void', '已作廢')], default='draft', max_length=20, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='合計金額')),
                ('is_ar_transferred', models.BooleanField(default=False, verbose_name='已拋轉AR')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='記帳客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 客戶帳單',
                'verbose_name_plural': 'historical 客戶帳單',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServiceFee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('service_fee', models.IntegerField(default=0, verbose_name='服務費用')),
                ('ledger_fee', models.IntegerField(default=0, verbose_name='帳簿費用')),
                ('billing_months', models.JSONField(blank=True, default=list, help_text='例如 [1,3,5,7,9,11]', verbose_name='收費月份')),
                ('billing_cycle', models.CharField(choices=[('monthly', '月繳'), ('bimonthly', '雙月'), ('semi_annual', '半年'), ('annual', '年繳'), ('bimonthly_auto', '雙月(自動扣款)'), ('semi_annual_prepaid', '半年(預繳收費)')], default='bimonthly', max_length=30, verbose_name='收費週期')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='生效日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='記帳客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 服務費用',
                'verbose_name_plural': 'historical 服務費用',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('service_fee', models.IntegerField(default=0, verbose_name='服務費用')),
                ('ledger_fee', models.IntegerField(default=0, verbose_name='帳簿費用')),
                ('billing_months', models.JSONField(blank=True, default=list, help_text='例如 [1,3,5,7,9,11]', verbose_name='收費月份')),
                ('billing_cycle', models.CharField(choices=[('monthly', '月繳'), ('bimonthly', '雙月'), ('semi_annual', '半年'), ('annual', '年繳'), ('bimonthly_auto', '雙月(自動扣款)'), ('semi_annual_prepaid', '半年(預繳收費)')], default='bimonthly', max_length=30, verbose_name='收費週期')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='生效日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fees', to='bookkeeping.bookkeepingclient', verbose_name='記帳客戶')),
            ],
            options={
                'verbose_name': '服務費用',
                'verbose_name_plural': '服務費用',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalClientBillItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('description', models.CharField(max_length=200, verbose_name='項目說明')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='金額')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bill', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.clientbill', verbose_name='帳單')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_fee_ref', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.servicefee', verbose_name='來源服務費用')),
            ],
            options={
                'verbose_name': 'historical 帳單明細',
                'verbose_name_plural': 'historical 帳單明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClientBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('description', models.CharField(max_length=200, verbose_name='項目說明')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='金額')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='備註')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookkeeping.clientbill', verbose_name='帳單')),
                ('service_fee_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='bookkeeping.servicefee', verbose_name='來源服務費用')),
            ],
            options={
                'verbose_name': '帳單明細',
                'verbose_name_plural': '帳單明細',
                'ordering': ['id'],
            },
        ),
    ]
