# Generated by Django 5.1.5 on 2026-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0022_clientbill_historicalclientbill_historicalservicefee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicefee',
            name='billing_months',
        ),
        migrations.AddField(
            model_name='historicalservicefee',
            name='billing_months',
            field=models.IntegerField(default=13, help_text='若無特定月份可填寫 13', verbose_name='收費月份'),
        ),
        migrations.RemoveField(
            model_name='servicefee',
            name='billing_months',
        ),
        migrations.AddField(
            model_name='servicefee',
            name='billing_months',
            field=models.IntegerField(default=13, help_text='若無特定月份可填寫 13', verbose_name='收費月份'),
        ),
    ]
