# Generated by Django 5.1.5 on 2026-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0023_alter_historicalservicefee_billing_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbill',
            name='cost_sharing_data',
            field=models.JSONField(blank=True, default=list, verbose_name='公費分攤'),
        ),
        migrations.AddField(
            model_name='clientbill',
            name='quotation_data',
            field=models.JSONField(blank=True, default=list, verbose_name='帳單明細'),
        ),
        migrations.AddField(
            model_name='historicalclientbill',
            name='cost_sharing_data',
            field=models.JSONField(blank=True, default=list, verbose_name='公費分攤'),
        ),
        migrations.AddField(
            model_name='historicalclientbill',
            name='quotation_data',
            field=models.JSONField(blank=True, default=list, verbose_name='帳單明細'),
        ),
    ]
