# Generated by Django 5.1.5 on 2026-03-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0024_clientbill_cost_sharing_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientbill',
            options={'ordering': ['-year', '-month', '-client__name'], 'verbose_name': '客戶帳單', 'verbose_name_plural': '客戶帳單'},
        ),
        migrations.AddField(
            model_name='clientbill',
            name='advance_payment_data',
            field=models.JSONField(blank=True, default=list, verbose_name='代墊款明細'),
        ),
        migrations.AddField(
            model_name='historicalclientbill',
            name='advance_payment_data',
            field=models.JSONField(blank=True, default=list, verbose_name='代墊款明細'),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='cost_sharing_data',
            field=models.JSONField(blank=True, default=list, verbose_name='公費分攤比例'),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='is_ar_transferred',
            field=models.BooleanField(default=False, verbose_name='已拋轉 AR'),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='historicalclientbill',
            name='cost_sharing_data',
            field=models.JSONField(blank=True, default=list, verbose_name='公費分攤比例'),
        ),
        migrations.AlterField(
            model_name='historicalclientbill',
            name='is_ar_transferred',
            field=models.BooleanField(default=False, verbose_name='已拋轉 AR'),
        ),
        migrations.AlterField(
            model_name='historicalclientbill',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
