# Generated by Django 5.1.5 on 2026-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0025_alter_clientbill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbill',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='標記是否已經拋轉應收帳款與傳票', verbose_name='已過帳'),
        ),
        migrations.AddField(
            model_name='historicalclientbill',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='標記是否已經拋轉應收帳款與傳票', verbose_name='已過帳'),
        ),
    ]
