# Generated by Django 5.1.5 on 2026-03-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0026_clientbill_is_posted_historicalclientbill_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='notes',
            field=models.TextField(blank=True, help_text='可存放計算紀錄或提醒事項', null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='notes',
            field=models.TextField(blank=True, help_text='可存放計算紀錄或提醒事項', null=True, verbose_name='備註'),
        ),
    ]
