# Generated by Django 5.1.5 on 2026-03-09 14:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0027_historicaltaxfilingperiod_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('industry_profit_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='擴大書審純益率 (%)')),
                ('income_standard_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='所得額標準 (%)')),
                ('net_profit_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='同業利潤標準淨利率 (%)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='營所稅率 (%)')),
                ('year_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_tax_filing', to='bookkeeping.taxfilingyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': '營所稅申報設定',
                'verbose_name_plural': '營所稅申報設定',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCorporateTaxFiling',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('industry_profit_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='擴大書審純益率 (%)')),
                ('income_standard_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='所得額標準 (%)')),
                ('net_profit_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='同業利潤標準淨利率 (%)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='營所稅率 (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.taxfilingyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': 'historical 營所稅申報設定',
                'verbose_name_plural': 'historical 營所稅申報設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxAdjustmentEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('account_code', models.CharField(max_length=20, verbose_name='科目代碼')),
                ('account_name', models.CharField(max_length=100, verbose_name='科目名稱')),
                ('book_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='帳列金額')),
                ('excluded_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='帳外剔除金額')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('filing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.corporatetaxfiling', verbose_name='營所稅申報')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 申報調整明細',
                'verbose_name_plural': 'historical 申報調整明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxAdjustmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('account_code', models.CharField(max_length=20, verbose_name='科目代碼')),
                ('account_name', models.CharField(max_length=100, verbose_name='科目名稱')),
                ('book_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='帳列金額')),
                ('excluded_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='帳外剔除金額')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='bookkeeping.corporatetaxfiling', verbose_name='營所稅申報')),
            ],
            options={
                'verbose_name': '申報調整明細',
                'verbose_name_plural': '申報調整明細',
                'ordering': ['account_code'],
                'unique_together': {('filing', 'account_code')},
            },
        ),
    ]
