# Generated by Django 5.1.5 on 2026-03-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0028_corporatetaxfiling_historicalcorporatetaxfiling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatetaxfiling',
            name='year_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_tax_filing', to='bookkeeping.bookkeepingyear', verbose_name='所屬年度'),
        ),
        migrations.AlterField(
            model_name='historicalcorporatetaxfiling',
            name='year_record',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingyear', verbose_name='所屬年度'),
        ),
    ]
