# Generated by Django 5.1.5 on 2026-03-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0029_alter_corporatetaxfiling_year_record_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50, verbose_name='規則代碼')),
                ('alert_message', models.TextField(verbose_name='警報訊息')),
                ('actual_value', models.FloatField(blank=True, null=True, verbose_name='實際數值')),
                ('status', models.CharField(choices=[('UNHANDLED', '未處理'), ('NOTIFIED', '已通知'), ('IGNORED', '忽略')], default='UNHANDLED', max_length=20, verbose_name='處理狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_alerts', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_rule_alerts', to=settings.AUTH_USER_MODEL, verbose_name='處理人員')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_alerts', to='bookkeeping.bookkeepingperiod', verbose_name='帳務期別')),
            ],
            options={
                'verbose_name': '專家系統警報紀錄',
                'verbose_name_plural': '專家系統警報紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50, verbose_name='規則代碼')),
                ('custom_threshold', models.FloatField(blank=True, help_text='若為空值則使用系統預設閾值', null=True, verbose_name='客製化閾值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用此規則')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_rule_settings', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '客戶專屬規則設定',
                'verbose_name_plural': '客戶專屬規則設定',
                'unique_together': {('client', 'rule_code')},
            },
        ),
    ]
