# Generated by Django 6.0.2 on 2026-03-29 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0014_historicalserviceitem'),
        ('bookkeeping', '0031_industrytaxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookkeeping_clients', to='basic_data.customer', verbose_name='關聯客戶'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basic_data.customer', verbose_name='關聯客戶'),
        ),
    ]
