# Generated by Django 6.0.2 on 2026-03-30 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0014_historicalserviceitem'),
        ('bookkeeping', '0032_add_customer_fk_to_bookkeeping_client'),
        ('hr', '0012_historicalleavebalance_is_carried_over_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookkeepingclient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('tax_id__isnull', False), models.Q(('tax_id', ''), _negated=True)), fields=('tax_id',), name='unique_active_bookkeeping_client_tax_id'),
        ),
    ]
