# Generated by Django 5.1.5 on 2026-04-04 08:28

import django.db.models.deletion
import modules.bookkeeping.models.income_tax_media
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0033_unique_active_tax_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncomeTaxMediaData',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('raw_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='原始 001 檔')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析時間')),
                ('industry_code', models.CharField(blank=True, max_length=20, verbose_name='行業代號')),
                ('industry_name', models.CharField(blank=True, max_length=100, verbose_name='行業名稱')),
                ('gross_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業收入淨額')),
                ('cost_of_goods', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業成本')),
                ('gross_profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業毛利')),
                ('operating_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業費用')),
                ('net_operating_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業淨利')),
                ('non_operating_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業外收入')),
                ('non_operating_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業外支出')),
                ('pre_tax_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='稅前淨利')),
                ('taxable_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='課稅所得額')),
                ('annual_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應納稅額')),
                ('provisional_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='暫繳稅額')),
                ('withholding_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='扣繳稅額')),
                ('self_pay', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應自行繳納稅額')),
                ('undistributed_earnings', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='未分配盈餘')),
                ('undistributed_surtax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='未分配盈餘加徵')),
                ('raw_parsed_data', models.JSONField(blank=True, default=dict, help_text='001 檔解析後的完整 key-value 資料，供日後擴充欄位使用', verbose_name='完整解析原始資料')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.incometaxyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': 'historical 申報書媒體檔資料',
                'verbose_name_plural': 'historical 申報書媒體檔資料',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IncomeTaxMediaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('raw_file', models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.income_tax_media.get_media_file_path, verbose_name='原始 001 檔')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析時間')),
                ('industry_code', models.CharField(blank=True, max_length=20, verbose_name='行業代號')),
                ('industry_name', models.CharField(blank=True, max_length=100, verbose_name='行業名稱')),
                ('gross_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業收入淨額')),
                ('cost_of_goods', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業成本')),
                ('gross_profit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業毛利')),
                ('operating_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業費用')),
                ('net_operating_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業淨利')),
                ('non_operating_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業外收入')),
                ('non_operating_expense', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='營業外支出')),
                ('pre_tax_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='稅前淨利')),
                ('taxable_income', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='課稅所得額')),
                ('annual_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應納稅額')),
                ('provisional_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='暫繳稅額')),
                ('withholding_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='扣繳稅額')),
                ('self_pay', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='應自行繳納稅額')),
                ('undistributed_earnings', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='未分配盈餘')),
                ('undistributed_surtax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='未分配盈餘加徵')),
                ('raw_parsed_data', models.JSONField(blank=True, default=dict, help_text='001 檔解析後的完整 key-value 資料，供日後擴充欄位使用', verbose_name='完整解析原始資料')),
                ('year_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_data', to='bookkeeping.incometaxyear', verbose_name='所屬年度')),
            ],
            options={
                'verbose_name': '申報書媒體檔資料',
                'verbose_name_plural': '申報書媒體檔資料',
            },
        ),
    ]
