# Generated by Django 5.1.5 on 2026-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0034_add_income_tax_media_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetaxfiling',
            name='industry_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='行業代號'),
        ),
        migrations.AddField(
            model_name='corporatetaxfiling',
            name='industry_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='行業名稱'),
        ),
        migrations.AddField(
            model_name='historicalcorporatetaxfiling',
            name='industry_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='行業代號'),
        ),
        migrations.AddField(
            model_name='historicalcorporatetaxfiling',
            name='industry_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='行業名稱'),
        ),
    ]
