# Generated by Django 6.0.2 on 2026-04-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0035_corporatetaxfiling_industry_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookkeepingclient',
            name='business_password',
        ),
        migrations.RemoveField(
            model_name='historicalbookkeepingclient',
            name='business_password',
        ),
    ]
