# Generated by Django 5.1.5 on 2026-04-25 06:25

import modules.bookkeeping.models.income_tax
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0038_historicalbookkeepingclient_notification_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincometaxfiling',
            name='tax_bill_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='繳款書'),
        ),
        migrations.AddField(
            model_name='incometaxfiling',
            name='tax_bill_document',
            field=models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.income_tax.get_income_tax_document_path, verbose_name='繳款書'),
        ),
    ]
