# Generated by Django 5.1.5 on 2026-04-25 07:06

import modules.bookkeeping.models.business_tax
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0039_add_income_tax_bill_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxfilingperiod',
            name='tax_bill_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='繳款書'),
        ),
        migrations.AddField(
            model_name='taxfilingperiod',
            name='tax_bill_document',
            field=models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.business_tax.get_vat_document_path, verbose_name='繳款書'),
        ),
        migrations.AlterField(
            model_name='historicaltaxfilingperiod',
            name='filing_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='申報書'),
        ),
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='filing_document',
            field=models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.business_tax.get_vat_document_path, verbose_name='申報書'),
        ),
    ]
