# Generated by Django 6.0.2 on 2026-04-25 11:48

import django.db.models.deletion
import modules.bookkeeping.models.business_registration
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def backfill_business_registrations(apps, _schema_editor):
    BookkeepingClient = apps.get_model('bookkeeping', 'BookkeepingClient')
    BusinessRegistration = apps.get_model('bookkeeping', 'BusinessRegistration')
    for client in BookkeepingClient.objects.filter(is_deleted=False).iterator():
        BusinessRegistration.objects.get_or_create(client=client)


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0040_add_vat_tax_bill_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_registration', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '商工登記',
                'verbose_name_plural': '商工登記',
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('file', models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.business_registration.get_business_registration_document_path, verbose_name='檔案')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookkeeping.businessregistration', verbose_name='所屬商工登記')),
            ],
            options={
                'verbose_name': '商工登記文件',
                'verbose_name_plural': '商工登記文件',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBusinessRegistration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 商工登記',
                'verbose_name_plural': 'historical 商工登記',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBusinessRegistrationDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='檔案')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.businessregistration', verbose_name='所屬商工登記')),
            ],
            options={
                'verbose_name': 'historical 商工登記文件',
                'verbose_name_plural': 'historical 商工登記文件',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(backfill_business_registrations, migrations.RunPython.noop),
    ]
