# Generated by Django 6.0.2 on 2026-04-25 12:46

import django.db.models.deletion
import modules.bookkeeping.models.service_remuneration
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


DEFAULT_TAX_RATES = [
    # (code, label, withholding_rate, expense_rate, description, sort_order)
    ('9B',              '9B 稿費',                        Decimal('10'),  Decimal('0'),  '本國人稿費所得',                    10),
    ('9A',              '9A 執行業務所得',                Decimal('10'),  Decimal('0'),  '本國人執行業務所得（一般）',         20),
    ('9A-98',           '9A 執行業務（非自行出版）',       Decimal('10'),  Decimal('30'), '費用率 30%（非自行出版）',           21),
    ('9A-99',           '9A 執行業務（自行出版）',         Decimal('10'),  Decimal('75'), '費用率 75%（自行出版）',             22),
    ('50',              '50 薪資所得',                    Decimal('5'),   Decimal('0'),  '本國人薪資所得',                    30),
    ('92',              '92 其他所得',                    Decimal('20'),  Decimal('0'),  '本國人其他所得',                    40),
    ('FOREIGN_LT_183',  '外國人在臺未滿183天',            Decimal('20'),  Decimal('0'),  '一律 20% 扣繳',                     50),
    ('FOREIGN_GTE_183', '外國人在臺滿183天',              Decimal('18'),  Decimal('0'),  '視類別調整，預設 18%',              60),
]


def seed_tax_rates(apps, _schema_editor):
    Rate = apps.get_model('bookkeeping', 'ServiceRemunerationTaxRate')
    for code, label, wh_rate, exp_rate, desc, order in DEFAULT_TAX_RATES:
        Rate.objects.get_or_create(
            code=code,
            defaults={
                'label': label,
                'withholding_rate': wh_rate,
                'expense_rate': exp_rate,
                'description': desc,
                'sort_order': order,
                'is_active': True,
            },
        )

    NHIConfig = apps.get_model('bookkeeping', 'NHIConfig')
    if not NHIConfig.objects.exists():
        NHIConfig.objects.create(threshold=Decimal('20000'), rate=Decimal('2.11'))


def remove_seeded_data(apps, _schema_editor):
    apps.get_model('bookkeeping', 'ServiceRemunerationTaxRate').objects.all().delete()
    apps.get_model('bookkeeping', 'NHIConfig').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0041_add_business_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NHIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('threshold', models.DecimalField(decimal_places=0, default=Decimal('20000'), help_text='單筆金額超過此值才需扣補充保費', max_digits=12, verbose_name='起徵額')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('2.11'), max_digits=5, verbose_name='補充保費率 (%)')),
            ],
            options={
                'verbose_name': '二代健保設定',
                'verbose_name_plural': '二代健保設定',
            },
        ),
        migrations.CreateModel(
            name='ServiceRemunerationTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='代碼')),
                ('label', models.CharField(max_length=100, verbose_name='名稱')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='扣繳率 (%)')),
                ('expense_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='僅執行業務類別需填寫；其他類別填 0。', max_digits=5, verbose_name='費用率 (%)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '勞務報酬稅率設定',
                'verbose_name_plural': '勞務報酬稅率設定',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNHIConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('threshold', models.DecimalField(decimal_places=0, default=Decimal('20000'), help_text='單筆金額超過此值才需扣補充保費', max_digits=12, verbose_name='起徵額')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('2.11'), max_digits=5, verbose_name='補充保費率 (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 二代健保設定',
                'verbose_name_plural': 'historical 二代健保設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServiceRemuneration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('confirm_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='確認Token')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nationality', models.CharField(choices=[('local', '本國人'), ('foreign_lt_183', '外國人在臺未滿183天'), ('foreign_gte_183', '外國人在臺滿183天')], default='local', max_length=20, verbose_name='國籍')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='身分證字號')),
                ('has_nhi', models.BooleanField(default=False, verbose_name='是否投保健保')),
                ('residence_address', models.CharField(blank=True, max_length=255, verbose_name='戶籍地址')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('joined_union', models.BooleanField(default=False, verbose_name='已加入工會')),
                ('income_category', models.CharField(choices=[('9B', '9B 稿費'), ('9A', '9A 執行業務所得'), ('50', '50 薪資所得'), ('92', '92 其他所得')], default='9A', max_length=10, verbose_name='申報類別')),
                ('professional_category', models.CharField(blank=True, choices=[('98', '[98] 非自行出版稿費等(費用率30%)'), ('99', '[99] 自行出版稿費等(費用率75%)')], max_length=10, verbose_name='執行業務類別')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='金額')),
                ('service_content', models.TextField(blank=True, verbose_name='勞務內容')),
                ('service_start_date', models.DateField(blank=True, null=True, verbose_name='勞務開始日期')),
                ('service_end_date', models.DateField(blank=True, null=True, verbose_name='勞務結束日期')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='填表日期')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='公司名稱')),
                ('withholding_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='代扣所得稅')),
                ('supplementary_premium', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='二代健保補充保費')),
                ('actual_payment', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='實際支付金額')),
                ('payment_method', models.CharField(blank=True, choices=[('transfer', '匯款'), ('cash', '現金'), ('check', '支票'), ('voucher', '禮券')], max_length=20, verbose_name='付款方式')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='所得人銀行')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='銀行分行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='所得人帳號')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='所得人戶名')),
                ('signature_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='領款人簽名')),
                ('id_front_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='身分證正面')),
                ('id_back_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='身分證反面')),
                ('confirmation_status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認')], default='pending', max_length=20, verbose_name='確認狀態')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認時間')),
                ('skip_email_confirm', models.BooleanField(default=False, verbose_name='跳過Email確認')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email寄送時間')),
                ('payment_status', models.CharField(choices=[('unpaid', '待繳納'), ('paid', '已繳納')], default='unpaid', max_length=20, verbose_name='繳納狀態')),
                ('withholding_payment_slip', models.TextField(blank=True, max_length=100, null=True, verbose_name='扣繳繳款單')),
                ('supplementary_payment_slip', models.TextField(blank=True, max_length=100, null=True, verbose_name='補充保費繳款單')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 勞務報酬單',
                'verbose_name_plural': 'historical 勞務報酬單',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServiceRemunerationTaxRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='代碼')),
                ('label', models.CharField(max_length=100, verbose_name='名稱')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='扣繳率 (%)')),
                ('expense_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='僅執行業務類別需填寫；其他類別填 0。', max_digits=5, verbose_name='費用率 (%)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 勞務報酬稅率設定',
                'verbose_name_plural': 'historical 勞務報酬稅率設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceRemuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('confirm_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='確認Token')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nationality', models.CharField(choices=[('local', '本國人'), ('foreign_lt_183', '外國人在臺未滿183天'), ('foreign_gte_183', '外國人在臺滿183天')], default='local', max_length=20, verbose_name='國籍')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='身分證字號')),
                ('has_nhi', models.BooleanField(default=False, verbose_name='是否投保健保')),
                ('residence_address', models.CharField(blank=True, max_length=255, verbose_name='戶籍地址')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話')),
                ('joined_union', models.BooleanField(default=False, verbose_name='已加入工會')),
                ('income_category', models.CharField(choices=[('9B', '9B 稿費'), ('9A', '9A 執行業務所得'), ('50', '50 薪資所得'), ('92', '92 其他所得')], default='9A', max_length=10, verbose_name='申報類別')),
                ('professional_category', models.CharField(blank=True, choices=[('98', '[98] 非自行出版稿費等(費用率30%)'), ('99', '[99] 自行出版稿費等(費用率75%)')], max_length=10, verbose_name='執行業務類別')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='金額')),
                ('service_content', models.TextField(blank=True, verbose_name='勞務內容')),
                ('service_start_date', models.DateField(blank=True, null=True, verbose_name='勞務開始日期')),
                ('service_end_date', models.DateField(blank=True, null=True, verbose_name='勞務結束日期')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='填表日期')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='公司名稱')),
                ('withholding_tax', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='代扣所得稅')),
                ('supplementary_premium', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='二代健保補充保費')),
                ('actual_payment', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='實際支付金額')),
                ('payment_method', models.CharField(blank=True, choices=[('transfer', '匯款'), ('cash', '現金'), ('check', '支票'), ('voucher', '禮券')], max_length=20, verbose_name='付款方式')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='所得人銀行')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='銀行分行')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='所得人帳號')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='所得人戶名')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=modules.bookkeeping.models.service_remuneration.signature_upload_path, verbose_name='領款人簽名')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to=modules.bookkeeping.models.service_remuneration.id_front_upload_path, verbose_name='身分證正面')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to=modules.bookkeeping.models.service_remuneration.id_back_upload_path, verbose_name='身分證反面')),
                ('confirmation_status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認')], default='pending', max_length=20, verbose_name='確認狀態')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認時間')),
                ('skip_email_confirm', models.BooleanField(default=False, verbose_name='跳過Email確認')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email寄送時間')),
                ('payment_status', models.CharField(choices=[('unpaid', '待繳納'), ('paid', '已繳納')], default='unpaid', max_length=20, verbose_name='繳納狀態')),
                ('withholding_payment_slip', models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.service_remuneration.withholding_slip_upload_path, verbose_name='扣繳繳款單')),
                ('supplementary_payment_slip', models.FileField(blank=True, null=True, upload_to=modules.bookkeeping.models.service_remuneration.supp_premium_slip_upload_path, verbose_name='補充保費繳款單')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_remunerations', to='bookkeeping.bookkeepingclient', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '勞務報酬單',
                'verbose_name_plural': '勞務報酬單',
                'ordering': ['-filing_date', '-created_at'],
            },
        ),
        migrations.RunPython(seed_tax_rates, remove_seeded_data),
    ]
