# Generated by Django 6.0.2 on 2026-04-25 14:05

from decimal import Decimal

from django.db import migrations, models


def seed_rent_rate(apps, _schema_editor):
    Rate = apps.get_model('bookkeeping', 'ServiceRemunerationTaxRate')
    Rate.objects.update_or_create(
        code='RENT',
        defaults={
            'label': '租金',
            'withholding_rate': Decimal('10'),
            'expense_rate': Decimal('0'),
            'description': '本國人租金所得（標準扣繳率 10%）',
            'sort_order': 25,
            'is_active': True,
        },
    )


def remove_rent_rate(apps, _schema_editor):
    apps.get_model('bookkeeping', 'ServiceRemunerationTaxRate').objects.filter(code='RENT').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0042_add_service_remuneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalserviceremuneration',
            name='signature_image',
        ),
        migrations.RemoveField(
            model_name='serviceremuneration',
            name='signature_image',
        ),
        migrations.AlterField(
            model_name='historicalserviceremuneration',
            name='income_category',
            field=models.CharField(choices=[('9B', '9B 稿費'), ('9A', '9A 執行業務所得'), ('50', '50 薪資所得'), ('92', '92 其他所得'), ('RENT', '租金')], default='9A', max_length=10, verbose_name='申報類別'),
        ),
        migrations.AlterField(
            model_name='serviceremuneration',
            name='income_category',
            field=models.CharField(choices=[('9B', '9B 稿費'), ('9A', '9A 執行業務所得'), ('50', '50 薪資所得'), ('92', '92 其他所得'), ('RENT', '租金')], default='9A', max_length=10, verbose_name='申報類別'),
        ),
        migrations.RunPython(seed_rent_rate, remove_rent_rate),
    ]
