# Generated by Django 6.0.2 on 2026-04-25 23:40

from django.db import migrations, models


def rename_rent_code(apps, _schema_editor):
    Rate = apps.get_model('bookkeeping', 'ServiceRemunerationTaxRate')
    Rate.objects.filter(code='RENT').update(code='51')

    Remun = apps.get_model('bookkeeping', 'ServiceRemuneration')
    Remun.objects.filter(income_category='RENT').update(income_category='51')

    HistRemun = apps.get_model('bookkeeping', 'HistoricalServiceRemuneration')
    HistRemun.objects.filter(income_category='RENT').update(income_category='51')


def revert_rent_code(apps, _schema_editor):
    Rate = apps.get_model('bookkeeping', 'ServiceRemunerationTaxRate')
    Rate.objects.filter(code='51').update(code='RENT')

    Remun = apps.get_model('bookkeeping', 'ServiceRemuneration')
    Remun.objects.filter(income_category='51').update(income_category='RENT')

    HistRemun = apps.get_model('bookkeeping', 'HistoricalServiceRemuneration')
    HistRemun.objects.filter(income_category='51').update(income_category='RENT')


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0043_update_service_remuneration_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserviceremuneration',
            name='income_category',
            field=models.CharField(choices=[('9B', '9B 稿費'), ('9A', '9A 執行業務所得'), ('50', '50 薪資所得'), ('92', '92 其他所得'), ('51', '租金')], default='9A', max_length=10, verbose_name='申報類別'),
        ),
        migrations.AlterField(
            model_name='serviceremuneration',
            name='income_category',
            field=models.CharField(choices=[('9B', '9B 稿費'), ('9A', '9A 執行業務所得'), ('50', '50 薪資所得'), ('92', '92 其他所得'), ('51', '租金')], default='9A', max_length=10, verbose_name='申報類別'),
        ),
        migrations.RunPython(rename_rent_code, revert_rent_code),
    ]
