# Generated by Django 6.0.2 on 2026-04-26 12:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0044_rename_rent_to_51'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('unit_code', models.CharField(max_length=4, unique=True, verbose_name='稅籍單位代碼')),
                ('city_id', models.CharField(max_length=1, verbose_name='城市代號')),
                ('dept_id', models.CharField(max_length=5, verbose_name='稽徵所代號')),
                ('unit_name', models.CharField(max_length=50, verbose_name='單位名稱')),
            ],
            options={
                'verbose_name': '國稅局對照表',
                'verbose_name_plural': '國稅局對照表',
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTaxUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('unit_code', models.CharField(db_index=True, max_length=4, verbose_name='稅籍單位代碼')),
                ('city_id', models.CharField(max_length=1, verbose_name='城市代號')),
                ('dept_id', models.CharField(max_length=5, verbose_name='稽徵所代號')),
                ('unit_name', models.CharField(max_length=50, verbose_name='單位名稱')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 國稅局對照表',
                'verbose_name_plural': 'historical 國稅局對照表',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
