# Generated by Django 6.0.2 on 2026-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0045_add_tax_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxunit',
            options={'ordering': ['city_id', 'unit_code'], 'verbose_name': '國稅局對照表', 'verbose_name_plural': '國稅局對照表'},
        ),
        migrations.AddField(
            model_name='bookkeepingclient',
            name='tax_authority_code',
            field=models.CharField(blank=True, help_text='城市代號(1碼) + 稅籍單位代碼(4碼)，例如 A0300', max_length=5, null=True, verbose_name='國稅局轄區代碼'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='tax_authority_code',
            field=models.CharField(blank=True, help_text='城市代號(1碼) + 稅籍單位代碼(4碼)，例如 A0300', max_length=5, null=True, verbose_name='國稅局轄區代碼'),
        ),
        migrations.AlterField(
            model_name='historicaltaxunit',
            name='unit_code',
            field=models.CharField(max_length=4, verbose_name='稅籍單位代碼'),
        ),
        migrations.AlterField(
            model_name='taxunit',
            name='unit_code',
            field=models.CharField(max_length=4, verbose_name='稅籍單位代碼'),
        ),
        migrations.AlterUniqueTogether(
            name='taxunit',
            unique_together={('city_id', 'unit_code')},
        ),
    ]
