# Generated by Django 6.0.2 on 2026-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0046_tax_unit_composite_key_and_authority_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxunit',
            name='bureau_name',
            field=models.CharField(blank=True, default='', help_text='例如：財政部臺北國稅局', max_length=50, verbose_name='國稅局名稱'),
        ),
        migrations.AddField(
            model_name='taxunit',
            name='bureau_name',
            field=models.CharField(blank=True, default='', help_text='例如：財政部臺北國稅局', max_length=50, verbose_name='國稅局名稱'),
        ),
    ]
