# Generated by Django 5.1.5 on 2026-04-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0047_add_taxunit_bureau_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='service_remuneration_reminder_enabled',
            field=models.BooleanField(default=True, help_text='每月1號自動提醒尚未繳納的勞務報酬扣繳/補充保費', verbose_name='啟用勞務報酬繳費提醒'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='service_remuneration_reminder_enabled',
            field=models.BooleanField(default=True, help_text='每月1號自動提醒尚未繳納的勞務報酬扣繳/補充保費', verbose_name='啟用勞務報酬繳費提醒'),
        ),
    ]
