# Generated by Django 6.0.2 on 2026-04-30 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0048_bookkeepingclient_service_remuneration_reminder_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='assigned_accountant',
            field=models.ForeignKey(blank=True, help_text='案件管理通知將寄給此會計師；客戶從 portal 發起的案件預設指派給此會計師', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookkeeping_clients', to=settings.AUTH_USER_MODEL, verbose_name='負責會計師'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='assigned_accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='案件管理通知將寄給此會計師；客戶從 portal 發起的案件預設指派給此會計師', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='負責會計師'),
        ),
    ]
