# Generated by Django 6.0.2 on 2026-04-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0049_bookkeepingclient_assigned_accountant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookkeepingclient',
            name='assigned_accountant',
        ),
        migrations.RemoveField(
            model_name='historicalbookkeepingclient',
            name='assigned_accountant',
        ),
    ]
