# Generated by Django 6.0.2 on 2026-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0050_remove_bookkeepingclient_assigned_accountant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeepingclient',
            name='acceptance_status',
            field=models.CharField(choices=[('active', '承接中'), ('suspended', '停業中'), ('transferred', '轉出/解散')], db_index=True, default='active', max_length=20, verbose_name='承接狀態'),
        ),
        migrations.AlterField(
            model_name='bookkeepingclient',
            name='billing_status',
            field=models.CharField(choices=[('billing', '收費中'), ('stopped', '停止收費')], db_index=True, default='billing', max_length=20, verbose_name='計費狀態'),
        ),
        migrations.AlterField(
            model_name='bookkeepingclient',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('issued', '已開立'), ('paid', '已收款'), ('overdue', '逾期'), ('void', '已作廢')], db_index=True, default='draft', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='dividendtax',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='dividendtax',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='historicalbookkeepingclient',
            name='acceptance_status',
            field=models.CharField(choices=[('active', '承接中'), ('suspended', '停業中'), ('transferred', '轉出/解散')], db_index=True, default='active', max_length=20, verbose_name='承接狀態'),
        ),
        migrations.AlterField(
            model_name='historicalbookkeepingclient',
            name='billing_status',
            field=models.CharField(choices=[('billing', '收費中'), ('stopped', '停止收費')], db_index=True, default='billing', max_length=20, verbose_name='計費狀態'),
        ),
        migrations.AlterField(
            model_name='historicalbookkeepingclient',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='historicalclientbill',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('issued', '已開立'), ('paid', '已收款'), ('overdue', '逾期'), ('void', '已作廢')], db_index=True, default='draft', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='historicaldividendtax',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='historicaldividendtax',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='historicalincometaxfiling',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='historicalincometaxfiling',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='historicalprovisionaltax',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='historicalprovisionaltax',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='historicaltaxfilingperiod',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('auto_replied', '自動回覆'), ('manually_replied', '人工回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='historicaltaxfilingperiod',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='historicalwithholdingtax',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='historicalwithholdingtax',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='incometaxfiling',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='incometaxfiling',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='provisionaltax',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='provisionaltax',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('auto_replied', '自動回覆'), ('manually_replied', '人工回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='taxfilingperiod',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AlterField(
            model_name='withholdingtax',
            name='filing_status',
            field=models.CharField(choices=[('not_notified', '尚未通知'), ('waiting', '等待回覆'), ('paid', '繳納完成'), ('no_payment_needed', '無須繳納')], db_index=True, default='not_notified', max_length=20, verbose_name='繳納狀態'),
        ),
        migrations.AlterField(
            model_name='withholdingtax',
            name='is_filed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已申報'),
        ),
        migrations.AddIndex(
            model_name='clientbill',
            index=models.Index(fields=['status', '-created_at'], name='bookkeeping_status_8dcafb_idx'),
        ),
        migrations.AddIndex(
            model_name='clientbill',
            index=models.Index(fields=['-year', '-month'], name='bookkeeping_year_7cf21b_idx'),
        ),
    ]
