# Generated by Django 6.0.2 on 2026-06-12 11:51

from django.db import migrations, models


def backfill_payment_statuses(apps, schema_editor):
    """依「應繳金額是否為 0 ＋ 憑證是否已上傳」推算既有資料的兩個繳納狀態。"""
    ServiceRemuneration = apps.get_model('bookkeeping', 'ServiceRemuneration')

    def status(payable, slip):
        if not payable:
            return 'not_required'
        return 'uploaded' if slip else 'pending'

    for obj in ServiceRemuneration.objects.all().iterator():
        obj.withholding_payment_status = status(obj.withholding_tax, obj.withholding_payment_slip)
        obj.premium_payment_status = status(obj.supplementary_premium, obj.supplementary_payment_slip)
        obj.save(update_fields=['withholding_payment_status', 'premium_payment_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0053_remove_income_tax_item_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalserviceremuneration',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='serviceremuneration',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='historicalserviceremuneration',
            name='premium_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳')], db_index=True, default='pending', max_length=20, verbose_name='保費繳納狀態'),
        ),
        migrations.AddField(
            model_name='historicalserviceremuneration',
            name='withholding_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳')], db_index=True, default='pending', max_length=20, verbose_name='扣繳繳納狀態'),
        ),
        migrations.AddField(
            model_name='serviceremuneration',
            name='premium_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳')], db_index=True, default='pending', max_length=20, verbose_name='保費繳納狀態'),
        ),
        migrations.AddField(
            model_name='serviceremuneration',
            name='withholding_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳')], db_index=True, default='pending', max_length=20, verbose_name='扣繳繳納狀態'),
        ),
        migrations.RunPython(backfill_payment_statuses, migrations.RunPython.noop),
    ]
