# Generated by Django 6.0.2 on 2026-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0055_init_remuneration_reminder_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserviceremuneration',
            name='premium_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳'), ('manual_paid', '已繳納（人工確認）')], db_index=True, default='pending', max_length=20, verbose_name='保費繳納狀態'),
        ),
        migrations.AlterField(
            model_name='historicalserviceremuneration',
            name='withholding_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳'), ('manual_paid', '已繳納（人工確認）')], db_index=True, default='pending', max_length=20, verbose_name='扣繳繳納狀態'),
        ),
        migrations.AlterField(
            model_name='serviceremuneration',
            name='premium_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳'), ('manual_paid', '已繳納（人工確認）')], db_index=True, default='pending', max_length=20, verbose_name='保費繳納狀態'),
        ),
        migrations.AlterField(
            model_name='serviceremuneration',
            name='withholding_payment_status',
            field=models.CharField(choices=[('not_required', '無須繳納'), ('pending', '待繳納'), ('uploaded', '已上傳'), ('manual_paid', '已繳納（人工確認）')], db_index=True, default='pending', max_length=20, verbose_name='扣繳繳納狀態'),
        ),
    ]
