# Generated by Django 6.0.2 on 2026-06-15 14:44

import os
import django.db.models.deletion
import modules.bookkeeping.models.business_registration
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def migrate_files_to_child(apps, _schema_editor):
    """把舊的 Document.file 搬到新的 BusinessRegistrationDocumentFile 子表。"""
    Document = apps.get_model('bookkeeping', 'BusinessRegistrationDocument')
    DocumentFile = apps.get_model('bookkeeping', 'BusinessRegistrationDocumentFile')
    for doc in Document.objects.exclude(file='').exclude(file__isnull=True).iterator():
        DocumentFile.objects.create(
            document_id=doc.pk,
            file=doc.file.name,
            original_filename=os.path.basename(doc.file.name),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0057_add_vat_sales_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistrationDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('file', models.FileField(upload_to=modules.bookkeeping.models.business_registration.get_business_registration_file_path, verbose_name='檔案')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始檔名')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bookkeeping.businessregistrationdocument', verbose_name='所屬文件事件')),
            ],
            options={
                'verbose_name': '商工登記檔案',
                'verbose_name_plural': '商工登記檔案',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBusinessRegistrationDocumentFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('file', models.TextField(max_length=100, verbose_name='檔案')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始檔名')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.businessregistrationdocument', verbose_name='所屬文件事件')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 商工登記檔案',
                'verbose_name_plural': 'historical 商工登記檔案',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # 先把舊檔案搬進子表，再移除 Document.file
        migrations.RunPython(migrate_files_to_child, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='businessregistrationdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='historicalbusinessregistrationdocument',
            name='file',
        ),
    ]
