# Generated by Django 6.0.2 on 2026-06-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0059_backfill_tax_filing_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='company_act_22_1_filing',
            field=models.BooleanField(default=False, help_text='由事務所代為申報，每期加收500元服務費用', verbose_name='公司法22-1申報'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='company_act_22_1_filing',
            field=models.BooleanField(default=False, help_text='由事務所代為申報，每期加收500元服務費用', verbose_name='公司法22-1申報'),
        ),
    ]
