# Generated by Django 6.0.2 on 2026-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0060_add_company_act_22_1_filing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingclient',
            name='assigned_at',
            field=models.DateField(blank=True, help_text='指派 bookkeeping_assistant 那刻寫入；SLA 時鐘 B（遲未首次聯繫）的計時基準點', null=True, verbose_name='指派記帳助理日期'),
        ),
        migrations.AddField(
            model_name='historicalbookkeepingclient',
            name='assigned_at',
            field=models.DateField(blank=True, help_text='指派 bookkeeping_assistant 那刻寫入；SLA 時鐘 B（遲未首次聯繫）的計時基準點', null=True, verbose_name='指派記帳助理日期'),
        ),
    ]
