# Generated by Django 6.0.2 on 2026-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0064_init_engagement_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementletter',
            name='engagement_start_date',
            field=models.DateField(blank=True, help_text='人工填；配合營業稅週期，通常從最近要申報的營業稅期起算。結案自動產生的草稿此欄為空，發送前須補填', null=True, verbose_name='開始委任日期'),
        ),
        migrations.AlterField(
            model_name='historicalengagementletter',
            name='engagement_start_date',
            field=models.DateField(blank=True, help_text='人工填；配合營業稅週期，通常從最近要申報的營業稅期起算。結案自動產生的草稿此欄為空，發送前須補填', null=True, verbose_name='開始委任日期'),
        ),
    ]
