# Generated by Django 6.0.2 on 2026-06-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0065_alter_engagementletter_engagement_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeepingclient',
            name='send_invoice_method',
            field=models.CharField(blank=True, choices=[('post', '郵寄'), ('in_person', '親送'), ('keep', '自留'), ('merge', '併同其他客戶'), ('client_pickup', '客戶自己拿來'), ('purchase_by_client', '客戶自己買'), ('other', '其他')], max_length=20, null=True, verbose_name='送發票方式'),
        ),
        migrations.AlterField(
            model_name='historicalbookkeepingclient',
            name='send_invoice_method',
            field=models.CharField(blank=True, choices=[('post', '郵寄'), ('in_person', '親送'), ('keep', '自留'), ('merge', '併同其他客戶'), ('client_pickup', '客戶自己拿來'), ('purchase_by_client', '客戶自己買'), ('other', '其他')], max_length=20, null=True, verbose_name='送發票方式'),
        ),
    ]
