# Generated by Django 6.0.2 on 2026-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0066_alter_bookkeepingclient_send_invoice_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementletter',
            name='firm_name',
            field=models.CharField(choices=[('cpa', '勤信聯合會計師事務所'), ('bookkeeper', '勤信聯合記帳士事務所')], default='cpa', help_text='委任書信頭、受任人、頁尾顯示的事務所主體', max_length=20, verbose_name='受任事務所'),
        ),
        migrations.AddField(
            model_name='historicalengagementletter',
            name='firm_name',
            field=models.CharField(choices=[('cpa', '勤信聯合會計師事務所'), ('bookkeeper', '勤信聯合記帳士事務所')], default='cpa', help_text='委任書信頭、受任人、頁尾顯示的事務所主體', max_length=20, verbose_name='受任事務所'),
        ),
    ]
