# Generated by Django 6.0.2 on 2026-06-28 13:59

import modules.bookkeeping.models.engagement_letter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0067_engagementletter_firm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementletter',
            name='signature_image',
            field=models.ImageField(blank=True, upload_to=modules.bookkeeping.models.engagement_letter.get_engagement_signature_path, verbose_name='客戶手寫簽名'),
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='signer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email'),
        ),
        migrations.AddField(
            model_name='engagementletter',
            name='signer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='簽署人姓名'),
        ),
        migrations.AddField(
            model_name='historicalengagementletter',
            name='signature_image',
            field=models.TextField(blank=True, max_length=100, verbose_name='客戶手寫簽名'),
        ),
        migrations.AddField(
            model_name='historicalengagementletter',
            name='signer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email'),
        ),
        migrations.AddField(
            model_name='historicalengagementletter',
            name='signer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='簽署人姓名'),
        ),
    ]
