# Generated by Django 6.0.2 on 2026-05-01 14:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0050_remove_bookkeepingclient_assigned_accountant_and_more'),
        ('case_management', '0003_seed_email_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '提供財報'), ('other', '其他')], default='consult', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='category',
            field=models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '提供財報'), ('other', '其他')], default='consult', max_length=20, verbose_name='類別'),
        ),
        migrations.CreateModel(
            name='HistoricalCaseTaskTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('category', models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '提供財報'), ('other', '其他')], max_length=20, verbose_name='案件類別')),
                ('title', models.CharField(max_length=300, verbose_name='清單項目')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bookkeeping_client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookkeeping.bookkeepingclient', verbose_name='所屬客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 案件清單範本',
                'verbose_name_plural': 'historical 案件清單範本',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CaseTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '提供財報'), ('other', '其他')], max_length=20, verbose_name='案件類別')),
                ('title', models.CharField(max_length=300, verbose_name='清單項目')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('bookkeeping_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_task_templates', to='bookkeeping.bookkeepingclient', verbose_name='所屬客戶')),
            ],
            options={
                'verbose_name': '案件清單範本',
                'verbose_name_plural': '案件清單範本',
                'ordering': ['category', 'order', 'created_at'],
                'indexes': [models.Index(fields=['bookkeeping_client', 'category'], name='case_manage_bookkee_11e096_idx')],
            },
        ),
    ]
