# Generated by Django 6.0.2 on 2026-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_alter_case_category_alter_historicalcase_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '稅局查帳'), ('other', '其他')], default='consult', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='casetasktemplate',
            name='category',
            field=models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '稅局查帳'), ('other', '其他')], max_length=20, verbose_name='案件類別'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='category',
            field=models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '稅局查帳'), ('other', '其他')], default='consult', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='historicalcasetasktemplate',
            name='category',
            field=models.CharField(choices=[('consult', '諮詢'), ('request_doc', '索取資料'), ('filing', '申報作業'), ('dispute', '稅局查帳'), ('other', '其他')], max_length=20, verbose_name='案件類別'),
        ),
    ]
