# Generated by Django 6.0.2 on 2026-05-05 15:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0005_alter_case_category_alter_casetasktemplate_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInquiry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='電話')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='公司')),
                ('stage', models.CharField(blank=True, max_length=40, verbose_name='事業階段')),
                ('message', models.TextField(blank=True, verbose_name='諮詢內容')),
                ('source', models.CharField(choices=[('landing_contact', '首頁聯絡表單'), ('appointment_modal', '預約諮詢視窗'), ('other', '其他')], default='landing_contact', max_length=40, verbose_name='來源')),
                ('referer', models.CharField(blank=True, max_length=300, verbose_name='送出頁面')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('new', '待處理'), ('contacted', '已聯絡'), ('converted', '已成交'), ('dropped', '未成交')], default='new', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, verbose_name='內部備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('handled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 諮詢預約',
                'verbose_name_plural': 'historical 諮詢預約',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='電話')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='公司')),
                ('stage', models.CharField(blank=True, max_length=40, verbose_name='事業階段')),
                ('message', models.TextField(blank=True, verbose_name='諮詢內容')),
                ('source', models.CharField(choices=[('landing_contact', '首頁聯絡表單'), ('appointment_modal', '預約諮詢視窗'), ('other', '其他')], default='landing_contact', max_length=40, verbose_name='來源')),
                ('referer', models.CharField(blank=True, max_length=300, verbose_name='送出頁面')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('new', '待處理'), ('contacted', '已聯絡'), ('converted', '已成交'), ('dropped', '未成交')], default='new', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, verbose_name='內部備註')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
            ],
            options={
                'verbose_name': '諮詢預約',
                'verbose_name_plural': '諮詢預約',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='case_manage_status_ac145c_idx')],
            },
        ),
    ]
