# Generated by Django 6.0.2 on 2026-05-08 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_historicalinquiry_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='最後活動時間'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='最後活動時間'),
        ),
    ]
