# Generated by Django 6.0.2 on 2026-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0007_alter_case_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinquiry',
            name='source',
            field=models.CharField(choices=[('landing_contact', '首頁聯絡表單'), ('appointment_modal', '預約諮詢視窗'), ('registration_quickform', '快速登記表單'), ('other', '其他')], default='landing_contact', max_length=40, verbose_name='來源'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('landing_contact', '首頁聯絡表單'), ('appointment_modal', '預約諮詢視窗'), ('registration_quickform', '快速登記表單'), ('other', '其他')], default='landing_contact', max_length=40, verbose_name='來源'),
        ),
    ]
