# Generated by Django 6.0.2 on 2026-06-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0008_alter_historicalinquiry_source_alter_inquiry_source'),
        ('registration', '0044_registrationdocument_historicalregistrationdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='satisfied_by_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfied_tasks', to='registration.registrationdocument', verbose_name='滿足此項的登記文件'),
        ),
        migrations.AddField(
            model_name='historicalcasetask',
            name='satisfied_by_document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.registrationdocument', verbose_name='滿足此項的登記文件'),
        ),
    ]
