# Generated by Django 6.0.2 on 2026-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0009_casetask_satisfied_by_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='target_doc_type',
            field=models.CharField(blank=True, choices=[('id_card', '身分證影本'), ('bankbook', '存摺影本'), ('house_tax', '房屋稅單'), ('lease', '租賃契約'), ('photo', '大頭照'), ('other', '其他')], max_length=20, null=True, verbose_name='收料文件型別'),
        ),
        migrations.AddField(
            model_name='historicalcasetask',
            name='target_doc_type',
            field=models.CharField(blank=True, choices=[('id_card', '身分證影本'), ('bankbook', '存摺影本'), ('house_tax', '房屋稅單'), ('lease', '租賃契約'), ('photo', '大頭照'), ('other', '其他')], max_length=20, null=True, verbose_name='收料文件型別'),
        ),
    ]
