# Generated by Django 6.0.2 on 2026-06-20 02:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0010_casetask_target_doc_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeDocTypeHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('doc_type', models.CharField(choices=[('id_card', '身分證影本'), ('bankbook', '存摺影本'), ('house_tax', '房屋稅單'), ('lease', '租賃契約'), ('photo', '大頭照'), ('other', '其他')], max_length=20, unique=True, verbose_name='文件型別')),
                ('help_url', models.URLField(help_text='操作影片或說明文件的網址，客戶端會以新分頁開啟', verbose_name='說明連結')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='補充說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '收料說明設定',
                'verbose_name_plural': '收料說明設定',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalIntakeDocTypeHelp',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('doc_type', models.CharField(choices=[('id_card', '身分證影本'), ('bankbook', '存摺影本'), ('house_tax', '房屋稅單'), ('lease', '租賃契約'), ('photo', '大頭照'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件型別')),
                ('help_url', models.URLField(help_text='操作影片或說明文件的網址，客戶端會以新分頁開啟', verbose_name='說明連結')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='補充說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 收料說明設定',
                'verbose_name_plural': 'historical 收料說明設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
