# Generated by Django 6.0.2 on 2026-06-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0011_intakedoctypehelp_historicalintakedoctypehelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetask',
            name='target_doc_type',
            field=models.CharField(blank=True, choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('other', '其他')], max_length=20, null=True, verbose_name='收料文件型別'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='target_doc_type',
            field=models.CharField(blank=True, choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('other', '其他')], max_length=20, null=True, verbose_name='收料文件型別'),
        ),
        migrations.AlterField(
            model_name='historicalintakedoctypehelp',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件型別'),
        ),
        migrations.AlterField(
            model_name='intakedoctypehelp',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('other', '其他')], max_length=20, unique=True, verbose_name='文件型別'),
        ),
    ]
