# Generated by Django 6.0.2 on 2026-06-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0012_alter_casetask_target_doc_type_and_more'),
        ('registration', '0045_alter_historicalregistrationdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetask',
            name='satisfied_by_document',
        ),
        migrations.RemoveField(
            model_name='historicalcasetask',
            name='satisfied_by_document',
        ),
        migrations.AddField(
            model_name='casetask',
            name='satisfied_by_documents',
            field=models.ManyToManyField(blank=True, related_name='satisfied_tasks', to='registration.registrationdocument', verbose_name='滿足此項的登記文件'),
        ),
    ]
