# Generated by Django 6.0.2 on 2026-06-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0013_remove_casetask_satisfied_by_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='declaration_transaction',
            field=models.CharField(blank=True, max_length=200, verbose_name='聲明書交易內容'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='item_kind',
            field=models.CharField(choices=[('document', '文件上傳'), ('declaration', '聲明書簽署')], default='document', max_length=20, verbose_name='項目型態'),
        ),
        migrations.AddField(
            model_name='historicalcasetask',
            name='declaration_transaction',
            field=models.CharField(blank=True, max_length=200, verbose_name='聲明書交易內容'),
        ),
        migrations.AddField(
            model_name='historicalcasetask',
            name='item_kind',
            field=models.CharField(choices=[('document', '文件上傳'), ('declaration', '聲明書簽署')], default='document', max_length=20, verbose_name='項目型態'),
        ),
    ]
