# Generated by Django 5.1.5 on 2026-02-16 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='登記單號')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('progress_status', models.IntegerField(choices=[(0, '新接案'), (1, '討論中'), (2, '製作文件中'), (3, '審查中'), (4, '結案'), (5, '沒有辦理')], default=0, verbose_name='登記進度')),
                ('mandate_return', models.CharField(choices=[('draft', '草稿'), ('signing', '簽核中'), ('approved', '核准'), ('rejected', '拒絕')], default='draft', max_length=20, verbose_name='委任書簽回')),
                ('acceptance_date', models.DateField(default=django.utils.timezone.now, verbose_name='承接日期')),
                ('case_type', models.JSONField(blank=True, default=list, verbose_name='案件種類')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '登記進度表',
                'verbose_name_plural': '登記進度表',
                'ordering': ['-registration_no'],
            },
        ),
    ]
