# Generated by Django 5.1.5 on 2026-02-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='quotation_data',
            field=models.JSONField(blank=True, default=list, verbose_name='報價單資料'),
        ),
    ]
