# Generated by Django 5.1.5 on 2026-02-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_progress_quotation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='cost_sharing_data',
            field=models.JSONField(blank=True, default=list, verbose_name='公費分攤資料'),
        ),
    ]
