# Generated by Django 5.1.5 on 2026-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_progress_cost_sharing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='支付狀態'),
        ),
        migrations.AddField(
            model_name='progress',
            name='payment_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='支付連結Token'),
        ),
        migrations.AddField(
            model_name='progress',
            name='pickup_method',
            field=models.CharField(choices=[('mail', '郵寄'), ('self', '自取')], default='mail', max_length=20, verbose_name='取件方式'),
        ),
        migrations.AddField(
            model_name='progress',
            name='recipient_addr',
            field=models.CharField(blank=True, max_length=255, verbose_name='收件地址'),
        ),
        migrations.AddField(
            model_name='progress',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='收件人姓名'),
        ),
        migrations.AddField(
            model_name='progress',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='收件人電話'),
        ),
    ]
