# Generated by Django 5.1.5 on 2026-02-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_progress_payment_status_progress_payment_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('risk_level', models.IntegerField(choices=[(0, '一般風險'), (1, '高風險')], default=0, verbose_name='風險層級')),
                ('is_gov_agency', models.BooleanField(default=False, verbose_name='是否為我國政府機關及公營事業機構')),
                ('is_foreign_gov', models.BooleanField(default=False, verbose_name='是否為外國政府機關')),
                ('is_public_company', models.BooleanField(default=False, verbose_name='是否為我國公開發行公司及其子公司')),
                ('is_foreign_listed_subsidiary', models.BooleanField(default=False, verbose_name='是否為於國外掛牌並依掛牌所在地規定，應揭露其主要股東之股票上市、上櫃公司其子公司')),
                ('is_regulated_financial_inst', models.BooleanField(default=False, verbose_name='是否為受我國監理之金融機構及其管理之投資工具')),
                ('is_foreign_regulated_inst', models.BooleanField(default=False, verbose_name='是否設立於我國境外，且所受監理規範...之金融機構')),
                ('is_gov_fund', models.BooleanField(default=False, verbose_name='是否為我國政府機關主管之基金')),
                ('is_employee_trust', models.BooleanField(default=False, verbose_name='是否為員工持股信託、員工福利儲蓄信託')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '客戶評估表',
                'verbose_name_plural': '客戶評估表',
                'ordering': ['-created_at'],
            },
        ),
    ]
