# Generated by Django 5.1.5 on 2026-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_clientassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassessment',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='clientassessment',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID'),
        ),
    ]
