# Generated by Django 5.1.5 on 2026-02-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_clientassessment_line_id_clientassessment_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='評估日期')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='登記案件編號')),
                ('risk_level', models.IntegerField(choices=[(0, '一般風險'), (1, '高風險')], default=0, verbose_name='風險層級')),
                ('note', models.TextField(blank=True, null=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assessments', to='registration.clientassessment', verbose_name='客戶評估表')),
            ],
            options={
                'verbose_name': '案件評估表',
                'verbose_name_plural': '案件評估表',
                'ordering': ['-date'],
            },
        ),
    ]
