# Generated by Django 5.1.5 on 2026-02-17 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_caseassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassessment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名稱'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='is_accepted',
            field=models.BooleanField(choices=[(True, '承接'), (False, '不承接')], default=True, verbose_name='案件承接與否'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='is_completed',
            field=models.BooleanField(choices=[(True, '完成'), (False, '未完成')], default=True, verbose_name='案件完成否'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='main_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='needs_reporting',
            field=models.BooleanField(choices=[(True, '需通報'), (False, '不需通報')], default=False, verbose_name='案件是否符合通報義務'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='電話'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='unified_business_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='client_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assessments', to='registration.clientassessment', verbose_name='客戶評估表'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='評估日期'),
        ),
    ]
