# Generated by Django 5.1.5 on 2026-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_caseassessment_address_caseassessment_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_50',
            field=models.BooleanField(default=False, verbose_name='50 買賣不動產'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_51',
            field=models.BooleanField(default=False, verbose_name='51 管理客戶金錢、證券或其他資產'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_52',
            field=models.BooleanField(default=False, verbose_name='52 管理銀行、儲蓄或證券帳戶'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_53',
            field=models.BooleanField(default=False, verbose_name='53 有關提供公司設立、營運或管理之資金籌劃'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_54',
            field=models.BooleanField(default=False, verbose_name='54 法人或法律協議之設立、營運或管理以及買賣事業體'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_55',
            field=models.BooleanField(default=False, verbose_name='55 關於法人之籌備或設立事項'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_56',
            field=models.BooleanField(default=False, verbose_name='56 擔任或安排他人擔任公司董事或秘書、合夥之合夥人或在其他法人組織之類似職位'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_57',
            field=models.BooleanField(default=False, verbose_name='57 提供公司、合夥、信託、其他法人或協議註冊之辦公室、營業地址、居住所、通訊或管理地址'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_58',
            field=models.BooleanField(default=False, verbose_name='58 擔任或安排他人擔任信託或其他類似契約性質之受託人或其他相同角色'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='transaction_59',
            field=models.BooleanField(default=False, verbose_name='59 擔任或安排他人擔任實質持股股東'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_1',
            field=models.BooleanField(default=False, verbose_name='1. 酬金或交易金額高於新臺幣50萬元，客戶無正當理由，自行或要求多次或連續以略低於新臺幣50萬之現金支付。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_2',
            field=models.BooleanField(default=False, verbose_name='2. 酬金或交易金額高於新臺幣50萬元，客戶無正當理由，以現金、外幣現金、旅行支票、外幣匯票或其他無記名金融工具支付。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_3',
            field=models.BooleanField(default=False, verbose_name='3. 無正當理由要求立即買賣不動產或事業體。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_4',
            field=models.BooleanField(default=False, verbose_name='4. 客戶為法務部依資恐防制法公告制裁之個人、法人或團體，或法務部公布之其他國家、國際組織認定或追查之恐怖組織、恐怖分子。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_5',
            field=models.BooleanField(default=False, verbose_name='5. 交易疑似與恐怖活動、恐怖組織、資助恐怖主義或武器擴散有關聯。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_6',
            field=models.BooleanField(default=False, verbose_name='6. 為客戶準備或進行洗錢防制法第五條第三項第五款受指定各項交易，客戶未能說明具體事由，或其事由顯不屬實。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_7',
            field=models.BooleanField(default=False, verbose_name='7. 委任關係結束後，發現客戶否認該委任、無該客戶存在或其他有事實足認該客戶係被他人所冒用。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='warning_8',
            field=models.BooleanField(default=False, verbose_name='8. 其他疑似洗錢或資恐交易情事。'),
        ),
        migrations.AlterField(
            model_name='clientassessment',
            name='unified_business_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='統一編號'),
        ),
    ]
