# Generated by Django 5.1.5 on 2026-02-18 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_caseassessment_transaction_50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassessment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='評估日期'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='transaction_53',
            field=models.BooleanField(default=True, verbose_name='53 有關提供公司設立、營運或管理之資金籌劃'),
        ),
    ]
