# Generated by Django 5.1.5 on 2026-02-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_caseassessment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_1',
            field=models.BooleanField(default=False, verbose_name='1. 法務部調查局之網頁：http://www.mjib.gov.tw/MLPC，確認其國籍是否為制裁名單中之國家。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_1_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_2',
            field=models.BooleanField(default=False, verbose_name='2. 台灣集中保管結算所：http://aml.tdcc.com.tw/AMLP，以帳號登入後，確認該人物是否為 PEP。'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_2_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_3',
            field=models.BooleanField(default=False, verbose_name='3. 取得資本簽證必要文件'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_3_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_4',
            field=models.BooleanField(default=False, verbose_name='4. 取得資金來源證明'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='appendix_4_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備註'),
        ),
    ]
