# Generated by Django 5.1.5 on 2026-02-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_caseassessment_appendix_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='身分證字號')),
                ('nationality', models.CharField(choices=[('TW', '中華民國'), ('CN', '中國大陸'), ('HK', '香港'), ('KR', '韓國')], default='TW', max_length=2, verbose_name='國籍')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('is_active', models.BooleanField(choices=[(True, '使用中'), (False, '未使用')], default=True, verbose_name='狀態')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '股東及董監事',
                'verbose_name_plural': '股東及董監事',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='appendix_3',
            field=models.BooleanField(default=True, verbose_name='3. 取得資本簽證必要文件'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='appendix_4',
            field=models.BooleanField(default=True, verbose_name='4. 取得資金來源證明'),
        ),
    ]
