# Generated by Django 5.1.5 on 2026-02-18 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_shareholder_alter_caseassessment_appendix_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(max_length=20, verbose_name='統一編號')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='LineID')),
                ('room_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RoomID')),
                ('shareholder_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('shareholder_id_number', models.CharField(max_length=20, verbose_name='身份證字號')),
                ('shareholder_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='交易日期')),
                ('organization_type', models.CharField(choices=[('LTD', '有限公司'), ('CORP', '股份有限公司')], default='CORP', max_length=10, verbose_name='組織種類')),
                ('transaction_reason', models.CharField(choices=[('SETUP', '設立'), ('CAPITAL_INCREASE', '增資'), ('CAPITAL_REDUCTION', '減資'), ('BUY', '買入'), ('SELL', '賣出'), ('GIFT', '贈與'), ('BEQUEST', '受贈'), ('MERGER_INCREASE', '合併增加'), ('MERGER_DECREASE', '合併減少'), ('SPLIT_INCREASE', '分割增加'), ('SPLIT_DECREASE', '分割減少'), ('OTHER_INCREASE', '其他增加'), ('OTHER_DECREASE', '其他減少')], default='SETUP', max_length=20, verbose_name='交易事由')),
                ('stock_type', models.CharField(choices=[('COMMON', '普通股'), ('PREFERRED', '特別股')], default='COMMON', max_length=10, verbose_name='股票種類')),
                ('share_count', models.IntegerField(verbose_name='股數')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合計')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '股權交易',
                'verbose_name_plural': '股權交易',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
