# Generated by Django 5.1.5 on 2026-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_equitytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
    ]
