# Generated by Django 5.1.5 on 2026-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_shareholder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitytransaction',
            name='organization_type',
            field=models.CharField(choices=[('LTD', '有限公司'), ('CORP', '股份有限公司')], max_length=10, verbose_name='組織種類'),
        ),
        migrations.AlterField(
            model_name='equitytransaction',
            name='stock_type',
            field=models.CharField(choices=[('COMMON', '普通股'), ('PREFERRED', '特別股')], max_length=10, verbose_name='股票種類'),
        ),
        migrations.AlterField(
            model_name='equitytransaction',
            name='transaction_reason',
            field=models.CharField(choices=[('SETUP', '設立'), ('CAPITAL_INCREASE', '增資'), ('CAPITAL_REDUCTION', '減資'), ('BUY', '買入'), ('SELL', '賣出'), ('GIFT', '贈與'), ('BEQUEST', '受贈'), ('MERGER_INCREASE', '合併增加'), ('MERGER_DECREASE', '合併減少'), ('SPLIT_INCREASE', '分割增加'), ('SPLIT_DECREASE', '分割減少'), ('OTHER_INCREASE', '其他增加'), ('OTHER_DECREASE', '其他減少')], max_length=20, verbose_name='交易事由'),
        ),
    ]
