# Generated by Django 5.1.5 on 2026-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_equitytransaction_organization_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(max_length=20, verbose_name='統一編號')),
                ('service_status', models.CharField(choices=[('INCLUDED', '本所客戶'), ('EXCLUDED', '已非本所服務')], default='INCLUDED', max_length=20, verbose_name='承接狀態')),
                ('completion_status', models.CharField(choices=[('COMPLETED', '已完成'), ('UNCOMPLETED', '未完成')], default='UNCOMPLETED', max_length=20, verbose_name='完成狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '股東名簿查詢',
                'verbose_name_plural': '股東名簿查詢',
                'ordering': ['-created_at'],
            },
        ),
    ]
