# Generated by Django 5.1.5 on 2026-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_shareholderregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderregister',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='shareholderregister',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID'),
        ),
    ]
