# Generated by Django 5.1.5 on 2026-02-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_shareholderregister_line_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitytransaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='equitytransaction',
            name='line_id',
        ),
        migrations.RemoveField(
            model_name='equitytransaction',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='equitytransaction',
            name='unified_business_no',
        ),
        migrations.AddField(
            model_name='equitytransaction',
            name='shareholder_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equity_transactions', to='registration.shareholderregister', verbose_name='股東名簿查詢'),
        ),
    ]
