# Generated by Django 5.1.5 on 2026-02-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_remove_equitytransaction_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('CHAIRMAN', '董事長'), ('DIRECTOR', '董事'), ('SUPERVISOR', '監察人'), ('MANAGER', '經理人')], max_length=20, verbose_name='職稱')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='身分證字號')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='國籍')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生年月日')),
                ('shares_held', models.PositiveIntegerField(default=0, verbose_name='持有股份')),
                ('entity_name', models.CharField(blank=True, max_length=100, verbose_name='所代表法人')),
                ('entity_no', models.CharField(blank=True, max_length=20, verbose_name='代表法人統編')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='registration.shareholderregister', verbose_name='股東名簿')),
            ],
            options={
                'verbose_name': '董監事',
                'verbose_name_plural': '董監事名單',
                'ordering': ['order', 'id'],
            },
        ),
    ]
