# Generated by Django 5.1.5 on 2026-02-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_director_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderregister',
            name='unified_business_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='統一編號'),
        ),
    ]
