# Generated by Django 5.1.5 on 2026-02-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_shareholderregister_unified_business_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='檔案編號')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='費用')),
                ('filing_method', models.CharField(choices=[('OFFICE', '本所申報'), ('SELF', '自行申報')], default='OFFICE', max_length=20, verbose_name='申報方式')),
                ('account', models.CharField(blank=True, max_length=100, null=True, verbose_name='帳號')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='密碼')),
                ('health_insurance_card_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='健保卡號')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公司法22-1申報',
                'verbose_name_plural': '公司法22-1申報',
                'ordering': ['-filing_no'],
            },
        ),
    ]
