# Generated by Django 5.1.5 on 2026-02-20 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_companyfiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='年度')),
                ('category', models.CharField(choices=[('CHANGE', '變動申報'), ('ANNUAL', '年度申報')], default='ANNUAL', max_length=10, verbose_name='類別')),
                ('filing_date', models.DateField(default=django.utils.timezone.now, verbose_name='申報日期')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='登記單號')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='registration.companyfiling')),
            ],
            options={
                'verbose_name': '申報歷程',
                'verbose_name_plural': '申報歷程',
                'ordering': ['-year', '-filing_date'],
            },
        ),
    ]
