# Generated by Django 5.1.5 on 2026-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_filinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfiling',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否已完成'),
        ),
    ]
