# Generated by Django 5.1.5 on 2026-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_remove_companyfiling_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassessment',
            name='is_accepted',
            field=models.BooleanField(default=True, verbose_name='案件承接與否'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='is_completed',
            field=models.BooleanField(default=True, verbose_name='案件完成否'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='needs_reporting',
            field=models.BooleanField(default=False, verbose_name='案件是否符合通報義務'),
        ),
    ]
