# Generated by Django 5.1.5 on 2026-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_alter_caseassessment_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassessment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='案件完成否'),
        ),
    ]
