# Generated by Django 5.1.5 on 2026-02-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_alter_caseassessment_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitytransaction',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='equitytransaction',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='登記案件編號'),
        ),
    ]
