# Generated by Django 5.1.5 on 2026-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_equitytransaction_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATEntityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_business_no', models.CharField(max_length=20, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('tax_id', models.CharField(max_length=50, verbose_name='稅籍編號')),
                ('registered_address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('assistant_name', models.CharField(max_length=100, verbose_name='助理人員')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('case_types', models.JSONField(blank=True, default=list, verbose_name='案件種類')),
                ('registration_no', models.CharField(blank=True, max_length=20, verbose_name='登記單號')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完成狀態')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '營業人變更登記',
                'verbose_name_plural': '營業人變更登記',
                'ordering': ['-created_at'],
            },
        ),
    ]
