# Generated by Django 5.1.5 on 2026-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_vatentitychange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatentitychange',
            name='assistant_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='助理人員'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='registered_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='登記地址'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='稅籍編號'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='unified_business_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='統一編號'),
        ),
    ]
