# Generated by Django 5.1.5 on 2026-02-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_alter_vatentitychange_assistant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='is_ar_transferred',
            field=models.BooleanField(default=False, verbose_name='已拋轉應收帳款'),
        ),
    ]
