# Generated by Django 5.1.5 on 2026-02-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_progress_is_ar_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='已拋轉傳票過帳'),
        ),
    ]
