# Generated by Django 6.0.2 on 2026-04-12 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_progress_is_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='payment_token',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='pickup_method',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='recipient_addr',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='recipient_phone',
        ),
        migrations.CreateModel(
            name='ProgressPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='支付 Token')),
                ('amount', models.PositiveIntegerField(verbose_name='請款金額')),
                ('description', models.CharField(blank=True, help_text='例如：頭期款、尾款', max_length=100, verbose_name='說明')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='收件人姓名')),
                ('recipient_phone', models.CharField(blank=True, max_length=50, verbose_name='收件人電話')),
                ('recipient_addr', models.CharField(blank=True, max_length=255, verbose_name='收件地址')),
                ('pickup_method', models.CharField(choices=[('mail', '郵寄'), ('self', '自取')], default='mail', max_length=20, verbose_name='取件方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='registration.progress', verbose_name='登記進度')),
            ],
            options={
                'verbose_name': '付款請求',
                'verbose_name_plural': '付款請求',
                'ordering': ['-created_at'],
            },
        ),
    ]
