# Generated by Django 6.0.2 on 2026-04-12 23:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_payment_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassessment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='clientassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='clientassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalClientAssessment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('risk_level', models.IntegerField(choices=[(0, '一般風險'), (1, '高風險')], default=0, verbose_name='風險層級')),
                ('is_gov_agency', models.BooleanField(default=False, verbose_name='是否為我國政府機關及公營事業機構')),
                ('is_foreign_gov', models.BooleanField(default=False, verbose_name='是否為外國政府機關')),
                ('is_public_company', models.BooleanField(default=False, verbose_name='是否為我國公開發行公司及其子公司')),
                ('is_foreign_listed_subsidiary', models.BooleanField(default=False, verbose_name='是否為於國外掛牌並依掛牌所在地規定，應揭露其主要股東之股票上市、上櫃公司其子公司')),
                ('is_regulated_financial_inst', models.BooleanField(default=False, verbose_name='是否為受我國監理之金融機構及其管理之投資工具')),
                ('is_foreign_regulated_inst', models.BooleanField(default=False, verbose_name='是否設立於我國境外，且所受監理規範...之金融機構')),
                ('is_gov_fund', models.BooleanField(default=False, verbose_name='是否為我國政府機關主管之基金')),
                ('is_employee_trust', models.BooleanField(default=False, verbose_name='是否為員工持股信託、員工福利儲蓄信託')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 客戶評估表',
                'verbose_name_plural': 'historical 客戶評估表',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
