# Generated by Django 6.0.2 on 2026-04-12 23:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_clientassessment_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassessment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalCaseAssessment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='評估日期')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='登記案件編號')),
                ('risk_level', models.IntegerField(choices=[(0, '一般風險'), (1, '高風險')], default=0, verbose_name='風險層級')),
                ('is_accepted', models.BooleanField(default=True, verbose_name='案件承接與否')),
                ('is_completed', models.BooleanField(default=False, verbose_name='案件完成否')),
                ('needs_reporting', models.BooleanField(default=False, verbose_name='案件是否符合通報義務')),
                ('transaction_50', models.BooleanField(default=False, verbose_name='50 買賣不動產')),
                ('transaction_51', models.BooleanField(default=False, verbose_name='51 管理客戶金錢、證券或其他資產')),
                ('transaction_52', models.BooleanField(default=False, verbose_name='52 管理銀行、儲蓄或證券帳戶')),
                ('transaction_53', models.BooleanField(default=True, verbose_name='53 有關提供公司設立、營運或管理之資金籌劃')),
                ('transaction_54', models.BooleanField(default=False, verbose_name='54 法人或法律協議之設立、營運或管理以及買賣事業體')),
                ('transaction_55', models.BooleanField(default=False, verbose_name='55 關於法人之籌備或設立事項')),
                ('transaction_56', models.BooleanField(default=False, verbose_name='56 擔任或安排他人擔任公司董事或秘書、合夥之合夥人或在其他法人組織之類似職位')),
                ('transaction_57', models.BooleanField(default=False, verbose_name='57 提供公司、合夥、信託、其他法人或協議註冊之辦公室、營業地址、居住所、通訊或管理地址')),
                ('transaction_58', models.BooleanField(default=False, verbose_name='58 擔任或安排他人擔任信託或其他類似契約性質之受託人或其他相同角色')),
                ('transaction_59', models.BooleanField(default=False, verbose_name='59 擔任或安排他人擔任實質持股股東')),
                ('warning_1', models.BooleanField(default=False, verbose_name='1. 酬金或交易金額高於新臺幣50萬元，客戶無正當理由，自行或要求多次或連續以略低於新臺幣50萬之現金支付。')),
                ('warning_2', models.BooleanField(default=False, verbose_name='2. 酬金或交易金額高於新臺幣50萬元，客戶無正當理由，以現金、外幣現金、旅行支票、外幣匯票或其他無記名金融工具支付。')),
                ('warning_3', models.BooleanField(default=False, verbose_name='3. 無正當理由要求立即買賣不動產或事業體。')),
                ('warning_4', models.BooleanField(default=False, verbose_name='4. 客戶為法務部依資恐防制法公告制裁之個人、法人或團體，或法務部公布之其他國家、國際組織認定或追查之恐怖組織、恐怖分子。')),
                ('warning_5', models.BooleanField(default=False, verbose_name='5. 交易疑似與恐怖活動、恐怖組織、資助恐怖主義或武器擴散有關聯。')),
                ('warning_6', models.BooleanField(default=False, verbose_name='6. 為客戶準備或進行洗錢防制法第五條第三項第五款受指定各項交易，客戶未能說明具體事由，或其事由顯不屬實。')),
                ('warning_7', models.BooleanField(default=False, verbose_name='7. 委任關係結束後，發現客戶否認該委任、無該客戶存在或其他有事實足認該客戶係被他人所冒用。')),
                ('warning_8', models.BooleanField(default=False, verbose_name='8. 其他疑似洗錢或資恐交易情事。')),
                ('appendix_1', models.BooleanField(default=False, verbose_name='1. 法務部調查局之網頁：http://www.mjib.gov.tw/MLPC，確認其國籍是否為制裁名單中之國家。')),
                ('appendix_1_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('appendix_2', models.BooleanField(default=False, verbose_name='2. 台灣集中保管結算所：http://aml.tdcc.com.tw/AMLP，以帳號登入後，確認該人物是否為 PEP。')),
                ('appendix_2_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('appendix_3', models.BooleanField(default=True, verbose_name='3. 取得資本簽證必要文件')),
                ('appendix_3_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('appendix_4', models.BooleanField(default=True, verbose_name='4. 取得資金來源證明')),
                ('appendix_4_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('note', models.TextField(blank=True, null=True, verbose_name='說明')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client_assessment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.clientassessment', verbose_name='客戶評估表')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 案件評估表',
                'verbose_name_plural': 'historical 案件評估表',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
