# Generated by Django 6.0.2 on 2026-04-13 02:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_shareholder_is_deleted_alter_shareholder_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderregister',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='shareholderregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='shareholderregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalShareholderRegister',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('unified_business_no', models.CharField(db_index=True, max_length=20, verbose_name='統一編號')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID')),
                ('service_status', models.CharField(choices=[('INCLUDED', '本所客戶'), ('EXCLUDED', '已非本所服務')], default='INCLUDED', max_length=20, verbose_name='承接狀態')),
                ('completion_status', models.CharField(choices=[('COMPLETED', '已完成'), ('UNCOMPLETED', '未完成')], default='UNCOMPLETED', max_length=20, verbose_name='完成狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 股東名簿查詢',
                'verbose_name_plural': 'historical 股東名簿查詢',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
