# Generated by Django 6.0.2 on 2026-04-13 04:47

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_shareholderregister_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equitytransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='equitytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='equitytransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalEquityTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('shareholder_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('shareholder_id_number', models.CharField(max_length=20, verbose_name='身份證字號')),
                ('shareholder_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('transaction_date', models.DateField(default=datetime.date.today, verbose_name='交易日期')),
                ('organization_type', models.CharField(choices=[('LTD', '有限公司'), ('CORP', '股份有限公司')], max_length=10, verbose_name='組織種類')),
                ('transaction_reason', models.CharField(choices=[('SETUP', '設立'), ('CAPITAL_INCREASE', '增資'), ('CAPITAL_REDUCTION', '減資'), ('BUY', '買入'), ('SELL', '賣出'), ('GIFT', '贈與'), ('BEQUEST', '受贈'), ('MERGER_INCREASE', '合併增加'), ('MERGER_DECREASE', '合併減少'), ('SPLIT_INCREASE', '分割增加'), ('SPLIT_DECREASE', '分割減少'), ('OTHER_INCREASE', '其他增加'), ('OTHER_DECREASE', '其他減少')], max_length=20, verbose_name='交易事由')),
                ('stock_type', models.CharField(choices=[('COMMON', '普通股'), ('PREFERRED', '特別股')], max_length=10, verbose_name='股票種類')),
                ('share_count', models.IntegerField(verbose_name='股數')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合計')),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='登記案件編號')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shareholder_register', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.shareholderregister', verbose_name='股東名簿查詢')),
            ],
            options={
                'verbose_name': 'historical 股權交易',
                'verbose_name_plural': 'historical 股權交易',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
