# Generated by Django 6.0.2 on 2026-04-13 12:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_equity_transaction_basemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfiling',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='companyfiling',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='companyfiling',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalCompanyFiling',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('filing_no', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='檔案編號')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='費用')),
                ('filing_method', models.CharField(choices=[('OFFICE', '本所申報'), ('SELF', '自行申報')], default='OFFICE', max_length=20, verbose_name='申報方式')),
                ('account', models.CharField(blank=True, max_length=100, null=True, verbose_name='帳號')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='密碼')),
                ('health_insurance_card_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='健保卡號')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 公司法22-1申報',
                'verbose_name_plural': 'historical 公司法22-1申報',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
