# Generated by Django 6.0.2 on 2026-04-13 12:51

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_company_filing_basemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalProgress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('registration_no', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='登記單號')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='手機')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='通訊地址')),
                ('progress_status', models.IntegerField(choices=[(0, '新接案'), (1, '討論中'), (2, '製作文件中'), (3, '審查中'), (4, '結案'), (5, '沒有辦理')], default=0, verbose_name='登記進度')),
                ('mandate_return', models.CharField(choices=[('draft', '草稿'), ('signing', '簽核中'), ('approved', '核准'), ('rejected', '拒絕')], default='draft', max_length=20, verbose_name='委任書簽回')),
                ('acceptance_date', models.DateField(default=django.utils.timezone.now, verbose_name='承接日期')),
                ('case_type', models.JSONField(blank=True, default=list, verbose_name='案件種類')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('quotation_data', models.JSONField(blank=True, default=list, verbose_name='報價單資料')),
                ('cost_sharing_data', models.JSONField(blank=True, default=list, verbose_name='公費分攤資料')),
                ('is_ar_transferred', models.BooleanField(default=False, verbose_name='已拋轉應收帳款')),
                ('is_posted', models.BooleanField(default=False, verbose_name='已拋轉傳票過帳')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 登記進度表',
                'verbose_name_plural': 'historical 登記進度表',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
