# Generated by Django 6.0.2 on 2026-04-13 12:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_progress_basemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vatentitychange',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='vatentitychange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.CreateModel(
            name='HistoricalVATEntityChange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='公司名稱')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='稅籍編號')),
                ('registered_address', models.CharField(blank=True, max_length=255, verbose_name='登記地址')),
                ('assistant_name', models.CharField(blank=True, max_length=100, verbose_name='助理人員')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('case_types', models.JSONField(blank=True, default=list, verbose_name='案件種類')),
                ('registration_no', models.CharField(blank=True, max_length=20, verbose_name='登記單號')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完成狀態')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 營業人變更登記',
                'verbose_name_plural': 'historical 營業人變更登記',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
