# Generated by Django 6.0.2 on 2026-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_vat_entity_change_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvatentitychange',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='結案日期'),
        ),
        migrations.AddField(
            model_name='vatentitychange',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='結案日期'),
        ),
    ]
