# Generated by Django 6.0.2 on 2026-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_vat_entity_change_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassessment',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='companyfiling',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='companyfiling',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalcaseassessment',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='historicalcaseassessment',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyfiling',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyfiling',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalprogress',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='historicalprogress',
            name='progress_status',
            field=models.IntegerField(choices=[(0, '新接案'), (1, '討論中'), (2, '製作文件中'), (3, '審查中'), (4, '結案'), (5, '沒有辦理')], db_index=True, default=0, verbose_name='登記進度'),
        ),
        migrations.AlterField(
            model_name='historicalprogress',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_status',
            field=models.IntegerField(choices=[(0, '新接案'), (1, '討論中'), (2, '製作文件中'), (3, '審查中'), (4, '結案'), (5, '沒有辦理')], db_index=True, default=0, verbose_name='登記進度'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='unified_business_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
    ]
