# Generated by Django 6.0.2 on 2026-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_alter_caseassessment_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvatentitychange',
            name='capital_stock_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='資本總額'),
        ),
        migrations.AddField(
            model_name='historicalvatentitychange',
            name='paid_in_capital_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='實收資本額'),
        ),
        migrations.AddField(
            model_name='historicalvatentitychange',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='負責人姓名'),
        ),
        migrations.AddField(
            model_name='vatentitychange',
            name='capital_stock_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='資本總額'),
        ),
        migrations.AddField(
            model_name='vatentitychange',
            name='paid_in_capital_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='實收資本額'),
        ),
        migrations.AddField(
            model_name='vatentitychange',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='負責人姓名'),
        ),
    ]
