# Generated by Django 6.0.2 on 2026-06-19 13:19

import django.db.models.deletion
import modules.registration.models.registration_document
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_historicalvatentitychange_capital_stock_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('doc_type', models.CharField(choices=[('id_card', '身分證影本'), ('bankbook', '存摺影本'), ('house_tax', '房屋稅單'), ('lease', '租賃契約'), ('photo', '大頭照'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型')),
                ('owner_id_number', models.CharField(blank=True, db_index=True, help_text='自然人身分證或法人統編；做為同人跨案重用的軟鍵', max_length=20, verbose_name='歸戶識別碼')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='歸戶人姓名')),
                ('file', models.FileField(upload_to=modules.registration.models.registration_document.get_registration_document_path, verbose_name='檔案')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始檔名')),
                ('source', models.CharField(choices=[('client_upload', '客戶上傳'), ('staff_upload', '承辦上傳')], db_index=True, default='client_upload', max_length=20, verbose_name='來源')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_documents', to='registration.progress', verbose_name='來源登記案')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='registration.registrationdocument', verbose_name='取代的舊版')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_registration_documents', to=settings.AUTH_USER_MODEL, verbose_name='上傳人員')),
            ],
            options={
                'verbose_name': '登記文件',
                'verbose_name_plural': '登記文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('doc_type', models.CharField(choices=[('id_card', '身分證影本'), ('bankbook', '存摺影本'), ('house_tax', '房屋稅單'), ('lease', '租賃契約'), ('photo', '大頭照'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型')),
                ('owner_id_number', models.CharField(blank=True, db_index=True, help_text='自然人身分證或法人統編；做為同人跨案重用的軟鍵', max_length=20, verbose_name='歸戶識別碼')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='歸戶人姓名')),
                ('file', models.TextField(max_length=100, verbose_name='檔案')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始檔名')),
                ('source', models.CharField(choices=[('client_upload', '客戶上傳'), ('staff_upload', '承辦上傳')], db_index=True, default='client_upload', max_length=20, verbose_name='來源')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.progress', verbose_name='來源登記案')),
                ('uploaded_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上傳人員')),
                ('supersedes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.registrationdocument', verbose_name='取代的舊版')),
            ],
            options={
                'verbose_name': 'historical 登記文件',
                'verbose_name_plural': 'historical 登記文件',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='registrationdocument',
            index=models.Index(fields=['owner_id_number', 'doc_type'], name='registratio_owner_i_123c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationdocument',
            index=models.Index(fields=['progress', 'doc_type'], name='registratio_progres_23bf58_idx'),
        ),
    ]
