# Generated by Django 6.0.2 on 2026-06-20 03:41

import django.db.models.deletion
import modules.registration.models.beneficial_owner_declaration
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_alter_historicalregistrationdocument_doc_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('photo', '大頭照'), ('aml_declaration', '所有權人/實質受益人聲明書'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型'),
        ),
        migrations.AlterField(
            model_name='registrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('photo', '大頭照'), ('aml_declaration', '所有權人/實質受益人聲明書'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型'),
        ),
        migrations.CreateModel(
            name='HistoricalBeneficialOwnerDeclaration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('company_name', models.CharField(max_length=255, verbose_name='本法人名稱')),
                ('transaction_description', models.CharField(blank=True, max_length=255, verbose_name='所從事之交易')),
                ('representative_title', models.CharField(max_length=100, verbose_name='代表人職稱')),
                ('representative_signature', models.TextField(max_length=100, verbose_name='代表人手寫簽名')),
                ('signed_at', models.DateTimeField(db_index=True, verbose_name='簽署時間')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='簽署來源 IP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.progress', verbose_name='來源登記案')),
                ('rendered_document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.registrationdocument', verbose_name='簽好的聲明書 PDF')),
            ],
            options={
                'verbose_name': 'historical 實質受益人聲明書',
                'verbose_name_plural': 'historical 實質受益人聲明書',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BeneficialOwnerDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('company_name', models.CharField(max_length=255, verbose_name='本法人名稱')),
                ('transaction_description', models.CharField(blank=True, max_length=255, verbose_name='所從事之交易')),
                ('representative_title', models.CharField(max_length=100, verbose_name='代表人職稱')),
                ('representative_signature', models.ImageField(upload_to=modules.registration.models.beneficial_owner_declaration.get_bo_signature_path, verbose_name='代表人手寫簽名')),
                ('signed_at', models.DateTimeField(db_index=True, verbose_name='簽署時間')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='簽署來源 IP')),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bo_declarations', to='registration.progress', verbose_name='來源登記案')),
                ('rendered_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registration.registrationdocument', verbose_name='簽好的聲明書 PDF')),
            ],
            options={
                'verbose_name': '實質受益人聲明書',
                'verbose_name_plural': '實質受益人聲明書',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['progress', '-signed_at'], name='registratio_progres_a0c87d_idx')],
            },
        ),
    ]
