# Generated by Django 6.0.2 on 2026-06-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_alter_historicalregistrationdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseassessment',
            name='beneficial_owner_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assessments', to='registration.beneficialownerdeclaration', verbose_name='關係人聲明書'),
        ),
        migrations.AddField(
            model_name='historicalcaseassessment',
            name='beneficial_owner_declaration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.beneficialownerdeclaration', verbose_name='關係人聲明書'),
        ),
    ]
