# Generated by Django 6.0.2 on 2026-06-28 09:22

import django.db.models.deletion
import modules.registration.models.draft_confirmation
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_alter_equitytransaction_organization_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('photo', '大頭照'), ('aml_declaration', '所有權人/實質受益人聲明書'), ('draft', '登記稿本（待客戶確認）'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型'),
        ),
        migrations.AlterField(
            model_name='registrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('photo', '大頭照'), ('aml_declaration', '所有權人/實質受益人聲明書'), ('draft', '登記稿本（待客戶確認）'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型'),
        ),
        migrations.CreateModel(
            name='HistoricalDraftConfirmation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='確認 Token')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已寄送'), ('confirmed', '已確認'), ('voided', '已作廢')], db_index=True, default='sent', max_length=20, verbose_name='狀態')),
                ('seal_authorization', models.BooleanField(default=False, verbose_name='包含用印授權')),
                ('authorization_text_snapshot', models.TextField(blank=True, help_text='發送當下凍結客戶將看到的授權文字，標準文字改版不影響舊紀錄', verbose_name='用印授權文字快照')),
                ('seal_authorized', models.BooleanField(default=False, verbose_name='客戶已授權用印')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='寄送時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='連結到期時間')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='寄送 Email')),
                ('recipient_line_id', models.CharField(blank=True, max_length=100, verbose_name='寄送 LINE/Room ID')),
                ('signature_image', models.TextField(blank=True, max_length=100, verbose_name='客戶手寫簽名')),
                ('signed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='確認時間')),
                ('signer_name', models.CharField(blank=True, max_length=100, verbose_name='簽署人姓名')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email')),
                ('signer_line_id', models.CharField(blank=True, max_length=100, verbose_name='簽署人 LINE/Room ID')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='簽署來源 IP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.progress', verbose_name='登記案')),
            ],
            options={
                'verbose_name': 'historical 稿本確認',
                'verbose_name_plural': 'historical 稿本確認',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DraftConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='確認 Token')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已寄送'), ('confirmed', '已確認'), ('voided', '已作廢')], db_index=True, default='sent', max_length=20, verbose_name='狀態')),
                ('seal_authorization', models.BooleanField(default=False, verbose_name='包含用印授權')),
                ('authorization_text_snapshot', models.TextField(blank=True, help_text='發送當下凍結客戶將看到的授權文字，標準文字改版不影響舊紀錄', verbose_name='用印授權文字快照')),
                ('seal_authorized', models.BooleanField(default=False, verbose_name='客戶已授權用印')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='寄送時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='連結到期時間')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='寄送 Email')),
                ('recipient_line_id', models.CharField(blank=True, max_length=100, verbose_name='寄送 LINE/Room ID')),
                ('signature_image', models.ImageField(blank=True, upload_to=modules.registration.models.draft_confirmation.get_draft_signature_path, verbose_name='客戶手寫簽名')),
                ('signed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='確認時間')),
                ('signer_name', models.CharField(blank=True, max_length=100, verbose_name='簽署人姓名')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email')),
                ('signer_line_id', models.CharField(blank=True, max_length=100, verbose_name='簽署人 LINE/Room ID')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='簽署來源 IP')),
                ('documents', models.ManyToManyField(blank=True, related_name='draft_confirmations', to='registration.registrationdocument', verbose_name='稿本文件')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_confirmations', to='registration.progress', verbose_name='登記案')),
            ],
            options={
                'verbose_name': '稿本確認',
                'verbose_name_plural': '稿本確認',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['progress', 'status'], name='registratio_progres_1ffdfc_idx')],
            },
        ),
    ]
