# Generated by Django 6.0.2 on 2026-06-29 00:10

import modules.registration.models.shareholder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_alter_historicalregistrationdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshareholder',
            name='id_card_back',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='身分證背面'),
        ),
        migrations.AddField(
            model_name='historicalshareholder',
            name='id_card_front',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='身分證正面'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=modules.registration.models.shareholder.get_id_card_path, verbose_name='身分證背面'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=modules.registration.models.shareholder.get_id_card_path, verbose_name='身分證正面'),
        ),
    ]
