# Generated by Django 6.0.2 on 2026-06-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0050_historicalshareholder_id_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshareholder',
            name='foreign_tax_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='國稅局外國人證件號碼'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='foreign_tax_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='國稅局外國人證件號碼'),
        ),
    ]
