# Generated by Django 6.0.2 on 2026-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_historicalshareholder_foreign_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='progress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
