# Generated by Django 6.0.2 on 2026-07-02 05:39

import django.db.models.deletion
import modules.registration.models.mandate
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_historicalprogress_email_progress_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMandateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('version', models.PositiveIntegerField(editable=False, unique=True, verbose_name='版本')),
                ('title', models.CharField(default='公司登記委任書', max_length=200, verbose_name='範本名稱')),
                ('body_html', models.TextField(help_text='支援 Django Template 佔位符：{{ company_name }} {{ unified_business_no }} {{ main_contact }} {{ acceptance_date }} {{ case_types }} {{ service_fee_total }} {{ advance_total }} {{ pre_collection_total }} {{ uncollected_total }} {{ today }}。報價明細表由客戶頁固定版位顯示，不必寫在本文。', verbose_name='條款本文')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '使用中'), ('archived', '已封存')], db_index=True, default='draft', max_length=20, verbose_name='狀態')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日')),
                ('notes', models.TextField(blank=True, help_text='這版改了什麼', verbose_name='版本備註')),
            ],
            options={
                'verbose_name': '登記委任書範本',
                'verbose_name_plural': '登記委任書範本',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationMandateTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('version', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='版本')),
                ('title', models.CharField(default='公司登記委任書', max_length=200, verbose_name='範本名稱')),
                ('body_html', models.TextField(help_text='支援 Django Template 佔位符：{{ company_name }} {{ unified_business_no }} {{ main_contact }} {{ acceptance_date }} {{ case_types }} {{ service_fee_total }} {{ advance_total }} {{ pre_collection_total }} {{ uncollected_total }} {{ today }}。報價明細表由客戶頁固定版位顯示，不必寫在本文。', verbose_name='條款本文')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '使用中'), ('archived', '已封存')], db_index=True, default='draft', max_length=20, verbose_name='狀態')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日')),
                ('notes', models.TextField(blank=True, help_text='這版改了什麼', verbose_name='版本備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 登記委任書範本',
                'verbose_name_plural': 'historical 登記委任書範本',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationMandate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='簽署 Token')),
                ('status', models.CharField(choices=[('sent', '已寄送'), ('signed', '已簽署'), ('declined', '已婉拒'), ('voided', '已作廢')], db_index=True, default='sent', max_length=20, verbose_name='狀態')),
                ('rendered_snapshot', models.TextField(blank=True, help_text='發送當下渲染並凍結，永不重生', verbose_name='條款凍結內容')),
                ('quotation_snapshot', models.JSONField(blank=True, default=dict, help_text='發送當下凍結的報價單明細與合計，之後改報價不影響本紀錄', verbose_name='報價明細快照')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='寄送時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='連結到期時間')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='寄送 Email')),
                ('recipient_line_id', models.CharField(blank=True, max_length=100, verbose_name='寄送 LINE/Room ID')),
                ('signature_image', models.TextField(blank=True, max_length=100, verbose_name='客戶手寫簽名')),
                ('signed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='簽署時間')),
                ('signer_name', models.CharField(blank=True, max_length=100, verbose_name='簽署人姓名')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email')),
                ('signer_line_id', models.CharField(blank=True, max_length=100, verbose_name='簽署人 LINE/Room ID')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='簽署來源 IP')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='婉拒時間')),
                ('decline_reason', models.TextField(blank=True, verbose_name='婉拒原因')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.progress', verbose_name='登記案')),
                ('template_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.registrationmandatetemplate', verbose_name='採用範本版本')),
            ],
            options={
                'verbose_name': 'historical 登記委任書',
                'verbose_name_plural': 'historical 登記委任書',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistrationMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='簽署 Token')),
                ('status', models.CharField(choices=[('sent', '已寄送'), ('signed', '已簽署'), ('declined', '已婉拒'), ('voided', '已作廢')], db_index=True, default='sent', max_length=20, verbose_name='狀態')),
                ('rendered_snapshot', models.TextField(blank=True, help_text='發送當下渲染並凍結，永不重生', verbose_name='條款凍結內容')),
                ('quotation_snapshot', models.JSONField(blank=True, default=dict, help_text='發送當下凍結的報價單明細與合計，之後改報價不影響本紀錄', verbose_name='報價明細快照')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='寄送時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='連結到期時間')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='寄送 Email')),
                ('recipient_line_id', models.CharField(blank=True, max_length=100, verbose_name='寄送 LINE/Room ID')),
                ('signature_image', models.ImageField(blank=True, upload_to=modules.registration.models.mandate.get_mandate_signature_path, verbose_name='客戶手寫簽名')),
                ('signed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='簽署時間')),
                ('signer_name', models.CharField(blank=True, max_length=100, verbose_name='簽署人姓名')),
                ('signer_email', models.EmailField(blank=True, max_length=254, verbose_name='簽署人 Email')),
                ('signer_line_id', models.CharField(blank=True, max_length=100, verbose_name='簽署人 LINE/Room ID')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='簽署來源 IP')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='婉拒時間')),
                ('decline_reason', models.TextField(blank=True, verbose_name='婉拒原因')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='registration.progress', verbose_name='登記案')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates', to='registration.registrationmandatetemplate', verbose_name='採用範本版本')),
            ],
            options={
                'verbose_name': '登記委任書',
                'verbose_name_plural': '登記委任書',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['progress', 'status'], name='registratio_progres_5d8f55_idx')],
            },
        ),
    ]
