# Generated by Django 6.0.2 on 2026-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_registrationmandatetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('photo', '大頭照'), ('aml_declaration', '所有權人/實質受益人聲明書'), ('draft', '登記稿本（待客戶確認）'), ('signed_mandate', '委任書（紙本簽回）'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型'),
        ),
        migrations.AlterField(
            model_name='registrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', '身分證影本'), ('nhi_card', '負責人健保卡影本'), ('lease', '租約或使用同意書影本'), ('house_tax', '房屋稅單或建物權狀影本'), ('bankbook_cover', '存摺封面影本'), ('bankbook_amount', '存摺金額頁影本'), ('bankbook_terms', '存摺約定條款影本'), ('balance_proof', '餘額證明影本'), ('fund_source', '資金來源證明影本'), ('photo', '大頭照'), ('aml_declaration', '所有權人/實質受益人聲明書'), ('draft', '登記稿本（待客戶確認）'), ('signed_mandate', '委任書（紙本簽回）'), ('other', '其他')], db_index=True, max_length=20, verbose_name='文件類型'),
        ),
    ]
