# Generated by Django 5.1.5 on 2026-02-26 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0010_delete_documentreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='收文日期')),
                ('subject', models.CharField(max_length=255, verbose_name='信件主旨')),
                ('category', models.CharField(blank=True, choices=[('營業稅憑證', '營業稅憑證'), ('會計帳冊', '會計帳冊'), ('補寄憑證', '補寄憑證'), ('國稅局公文', '國稅局公文'), ('經濟部公文', '經濟部公文'), ('法院公文', '法院公文'), ('其他公文', '其他公文'), ('事務所信件', '事務所信件'), ('事務所帳單', '事務所帳單'), ('各類函證', '各類函證'), ('其他', '其他')], max_length=50, null=True, verbose_name='信件分類')),
                ('status', models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已結案', '已結案')], default='待處理', max_length=20, verbose_name='處理狀態')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='document_receipts/%Y/%m/', verbose_name='附件')),
                ('is_line_notified', models.BooleanField(default=False, verbose_name='Line 通知狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_data.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '收文紀錄',
                'verbose_name_plural': '收文紀錄',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
    ]
