# Generated by Django 5.1.5 on 2026-02-26 01:36

from django.db import migrations

def add_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')
    # 1. Create parent "行政管理"
    parent, created = MenuItem.objects.update_or_create(
        title='行政管理',
        defaults={
            'url_name': '',
            'order': 35,
            'icon_svg': '<svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9.776c.112-.017.227-.026.344-.026h15.812c.117 0 .232.009.344.026m-16.5 0a2.25 2.25 0 0 0-1.883 2.542l.857 6a2.25 2.25 0 0 0 2.227 1.932H19.05a2.25 2.25 0 0 0 2.227-1.932l.857-6a2.25 2.25 0 0 0-1.883-2.542m-16.5 0V6A2.25 2.25 0 0 1 6 3.75h3.879a1.5 1.5 0 0 1 1.06.44l2.122 2.12a1.5 1.5 0 0 0 1.06.44H18A2.25 2.25 0 0 1 20.25 9v.776" /></svg>'
        }
    )
    
    # 2. Create child "收文系統" under "行政管理"
    MenuItem.objects.update_or_create(
        title='收文系統',
        defaults={
            'url_name': 'document_receipt_list',
            'parent': parent,
            'order': 10,
            'icon_svg': '<svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>',
        }
    )
    
    # 3. Clean up the old one from "基本資料" if it exists
    MenuItem.objects.filter(title='收文系統', parent__title='基本資料').delete()

def remove_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')
    MenuItem.objects.filter(title='收文系統', parent__title='行政管理').delete()
    MenuItem.objects.filter(title='行政管理').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_menu_items, remove_menu_items),
    ]
