# Generated by Django 5.1.5 on 2026-03-01 11:24

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_add_administrative_menu'),
        ('basic_data', '0010_delete_documentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIrsAuditNotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('attributable_year', models.IntegerField(blank=True, null=True, verbose_name='歸屬年度')),
                ('tax_category', models.CharField(blank=True, choices=[('營業稅', '營業稅'), ('所得稅', '所得稅'), ('印花稅', '印花稅'), ('個人綜所', '個人綜所'), ('遺贈稅', '遺贈稅'), ('貨物稅', '貨物稅'), ('其他', '其他')], max_length=50, null=True, verbose_name='稅種分類')),
                ('subject', models.CharField(max_length=255, verbose_name='信件主旨')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='收文日期')),
                ('assistant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='助理Email')),
                ('reply_deadline', models.DateField(blank=True, null=True, verbose_name='回復截止日')),
                ('merge_annual_income_tax', models.BooleanField(default=False, verbose_name='併入年度所得稅處理事項')),
                ('status', models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已結案', '已結案')], default='待處理', max_length=20, verbose_name='處理狀態')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='附件上傳')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('irs_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('irs_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人')),
                ('irs_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('irs_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='國稅局轄區')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_assistant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='指派助理')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basic_data.customer', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 國稅局查帳通知',
                'verbose_name_plural': 'historical 國稅局查帳通知',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IrsAuditNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('attributable_year', models.IntegerField(blank=True, null=True, verbose_name='歸屬年度')),
                ('tax_category', models.CharField(blank=True, choices=[('營業稅', '營業稅'), ('所得稅', '所得稅'), ('印花稅', '印花稅'), ('個人綜所', '個人綜所'), ('遺贈稅', '遺贈稅'), ('貨物稅', '貨物稅'), ('其他', '其他')], max_length=50, null=True, verbose_name='稅種分類')),
                ('subject', models.CharField(max_length=255, verbose_name='信件主旨')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='收文日期')),
                ('assistant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='助理Email')),
                ('reply_deadline', models.DateField(blank=True, null=True, verbose_name='回復截止日')),
                ('merge_annual_income_tax', models.BooleanField(default=False, verbose_name='併入年度所得稅處理事項')),
                ('status', models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已結案', '已結案')], default='待處理', max_length=20, verbose_name='處理狀態')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='irs_audit_notices/%Y/%m/', verbose_name='附件上傳')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('irs_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話')),
                ('irs_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人')),
                ('irs_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('irs_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='國稅局轄區')),
                ('assigned_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_notices', to=settings.AUTH_USER_MODEL, verbose_name='指派助理')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_data.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '國稅局查帳通知',
                'verbose_name_plural': '國稅局查帳通知',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrsAuditCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('comm_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('comm_content', models.TextField(verbose_name='溝通內容')),
                ('reply_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='回復狀態')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='administrative.irsauditnotice', verbose_name='查帳通知')),
            ],
            options={
                'verbose_name': '國稅局溝通紀錄',
                'verbose_name_plural': '國稅局溝通紀錄',
                'ordering': ['-comm_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalIrsAuditCommunication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('comm_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('comm_content', models.TextField(verbose_name='溝通內容')),
                ('reply_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='回復狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrative.irsauditnotice', verbose_name='查帳通知')),
            ],
            options={
                'verbose_name': 'historical 國稅局溝通紀錄',
                'verbose_name_plural': 'historical 國稅局溝通紀錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
