# Generated by Django 5.1.5 on 2026-03-02 00:32

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_historicalirsauditnotice_irsauditnotice_and_more'),
        ('basic_data', '0010_delete_documentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='發文日期')),
                ('dispatch_method', models.CharField(choices=[('郵局', '郵局'), ('掛號', '掛號'), ('快遞', '快遞'), ('親送', '親送'), ('其他', '其他')], default='掛號', max_length=20, verbose_name='發信方式')),
            ],
            options={
                'verbose_name': '發文紀錄',
                'verbose_name_plural': '發文紀錄',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDispatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dispatch_images/%Y/%m/', verbose_name='圖片檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administrative.documentdispatch', verbose_name='發文紀錄')),
            ],
            options={
                'verbose_name': '發文紀錄圖片',
                'verbose_name_plural': '發文紀錄圖片',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='寄送地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('postage', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='郵資費用')),
                ('is_absorbed_by_customer', models.BooleanField(default=False, verbose_name='是否客戶吸收')),
                ('is_notified', models.BooleanField(default=False, verbose_name='通知客戶')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='basic_data.customer', verbose_name='客戶')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administrative.documentdispatch', verbose_name='發文紀錄')),
            ],
            options={
                'verbose_name': '發文項目',
                'verbose_name_plural': '發文項目',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentDispatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='發文日期')),
                ('dispatch_method', models.CharField(choices=[('郵局', '郵局'), ('掛號', '掛號'), ('快遞', '快遞'), ('親送', '親送'), ('其他', '其他')], default='掛號', max_length=20, verbose_name='發信方式')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 發文紀錄',
                'verbose_name_plural': 'historical 發文紀錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentDispatchItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='寄送地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('postage', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='郵資費用')),
                ('is_absorbed_by_customer', models.BooleanField(default=False, verbose_name='是否客戶吸收')),
                ('is_notified', models.BooleanField(default=False, verbose_name='通知客戶')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basic_data.customer', verbose_name='客戶')),
                ('dispatch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrative.documentdispatch', verbose_name='發文紀錄')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 發文項目',
                'verbose_name_plural': 'historical 發文項目',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
