# Generated by Django 5.1.5 on 2026-03-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_documentdispatch_documentdispatchimage_and_more'),
        ('basic_data', '0010_delete_documentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdispatchitem',
            name='custom_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='自訂訊息'),
        ),
        migrations.AddField(
            model_name='documentdispatchitem',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='documentdispatchitem',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='統一編號'),
        ),
        migrations.AddField(
            model_name='historicaldocumentdispatchitem',
            name='custom_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='自訂訊息'),
        ),
        migrations.AddField(
            model_name='historicaldocumentdispatchitem',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, verbose_name='收件人'),
        ),
        migrations.AddField(
            model_name='historicaldocumentdispatchitem',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='documentdispatchitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='basic_data.customer', verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentdispatchitem',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basic_data.customer', verbose_name='客戶名稱'),
        ),
    ]
