# Generated by Django 5.1.5 on 2026-03-02 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_documentdispatchitem_custom_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_business_no', models.CharField(blank=True, default='', max_length=20, verbose_name='統一編號')),
                ('company_name', models.CharField(blank=True, default='', max_length=100, verbose_name='公司名稱')),
                ('line_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Line ID')),
                ('room_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Room ID')),
                ('main_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='主要聯絡人')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='手機')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='電話')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='通訊地址')),
                ('transfer_to_advance', models.BooleanField(default=False, verbose_name='轉為代墊款')),
                ('transfer_to_inventory', models.BooleanField(default=False, verbose_name='轉為庫存')),
                ('seal_cost_subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='印章費用小計')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已付款')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '印章採購單',
                'verbose_name_plural': '印章採購單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absorbed_by_customer', models.BooleanField(default=False, verbose_name='客戶吸收')),
                ('seal_type', models.CharField(choices=[('large_self', '大章(自留)'), ('small_self', '小章(自留)'), ('large_reg', '大章(登記)'), ('small_reg', '小章(登記)'), ('invoice', '發票章')], default='large_self', max_length=20, verbose_name='印章種類')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('name_or_address', models.CharField(blank=True, default='', max_length=200, verbose_name='名稱/地址')),
                ('unit_price', models.DecimalField(decimal_places=0, default=150, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='合計')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administrative.sealprocurement', verbose_name='採購單')),
            ],
            options={
                'verbose_name': '印章請購明細',
                'verbose_name_plural': '印章請購明細',
            },
        ),
    ]
