# Generated by Django 5.1.5 on 2026-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0006_sealprocurement_sealprocurementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealprocurementitem',
            name='movement_type',
            field=models.CharField(choices=[('purchase', '採購'), ('customer_provided', '客戶提供'), ('return_to_customer', '歸還客戶'), ('lend_out', '借出'), ('borrow_in', '借入'), ('surplus', '盤盈'), ('deficit', '盤虧')], default='purchase', max_length=30, verbose_name='異動類別'),
        ),
        migrations.AlterField(
            model_name='sealprocurementitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='數量'),
        ),
    ]
