# Generated by Django 5.1.5 on 2026-03-06 08:39

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0007_sealprocurementitem_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='公佈日期', verbose_name='日期')),
                ('subject', models.CharField(max_length=200, verbose_name='主題')),
                ('content', models.TextField(verbose_name='相關說明')),
                ('status', models.CharField(choices=[('active', '生效'), ('inactive', '失效')], default='active', max_length=20, verbose_name='狀態')),
            ],
            options={
                'verbose_name': '系統公佈欄',
                'verbose_name_plural': '系統公佈欄',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSystemBulletin',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='公佈日期', verbose_name='日期')),
                ('subject', models.CharField(max_length=200, verbose_name='主題')),
                ('content', models.TextField(verbose_name='相關說明')),
                ('status', models.CharField(choices=[('active', '生效'), ('inactive', '失效')], default='active', max_length=20, verbose_name='狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 系統公佈欄',
                'verbose_name_plural': 'historical 系統公佈欄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
