# Generated by Django 5.1.5 on 2026-03-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0008_systembulletin_historicalsystembulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystembulletin',
            name='importance_level',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='low', max_length=20, verbose_name='重要等級'),
        ),
        migrations.AddField(
            model_name='systembulletin',
            name='importance_level',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='low', max_length=20, verbose_name='重要等級'),
        ),
    ]
