# Generated by Django 5.1.5 on 2026-03-06 14:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0009_historicalsystembulletin_importance_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='任務名稱')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='是否為週期性')),
                ('recurring_months', models.CharField(help_text='例如: 1,3,5,7,9,11', max_length=50, verbose_name='執行月份')),
                ('deadline_day', models.IntegerField(default=15, verbose_name='截止日期(日)')),
                ('description', models.TextField(blank=True, verbose_name='備註說明')),
                ('source_type', models.CharField(choices=[('manual', '手動更新'), ('business_tax', '營業稅模組'), ('bookkeeping', '記帳模組')], default='manual', max_length=20, verbose_name='資料來源類型')),
            ],
            options={
                'verbose_name': '任務範本',
                'verbose_name_plural': '任務範本',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTaxTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, verbose_name='任務名稱')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='是否為週期性')),
                ('recurring_months', models.CharField(help_text='例如: 1,3,5,7,9,11', max_length=50, verbose_name='執行月份')),
                ('deadline_day', models.IntegerField(default=15, verbose_name='截止日期(日)')),
                ('description', models.TextField(blank=True, verbose_name='備註說明')),
                ('source_type', models.CharField(choices=[('manual', '手動更新'), ('business_tax', '營業稅模組'), ('bookkeeping', '記帳模組')], default='manual', max_length=20, verbose_name='資料來源類型')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 任務範本',
                'verbose_name_plural': 'historical 任務範本',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxTaskInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('title', models.CharField(max_length=200, verbose_name='任務標題')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('deadline', models.DateField(verbose_name='正式截止日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否全數完工')),
                ('total_clients', models.IntegerField(default=0, verbose_name='總客戶數')),
                ('completed_clients', models.IntegerField(default=0, verbose_name='已完成數')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrative.taxtemplate', verbose_name='任務範本')),
            ],
            options={
                'verbose_name': 'historical 任務實例',
                'verbose_name_plural': 'historical 任務實例',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('title', models.CharField(max_length=200, verbose_name='任務標題')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('deadline', models.DateField(verbose_name='正式截止日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否全數完工')),
                ('total_clients', models.IntegerField(default=0, verbose_name='總客戶數')),
                ('completed_clients', models.IntegerField(default=0, verbose_name='已完成數')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='administrative.taxtemplate', verbose_name='任務範本')),
            ],
            options={
                'verbose_name': '任務實例',
                'verbose_name_plural': '任務實例',
                'ordering': ['deadline'],
                'unique_together': {('template', 'year', 'month')},
            },
        ),
    ]
