# Generated by Django 5.1.5 on 2026-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0010_taxtemplate_historicaltaxtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxtaskinstance',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='taxtaskinstance',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
    ]
