# Generated by Django 5.1.5 on 2026-03-08 00:49

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0011_historicaltaxtaskinstance_remarks_and_more'),
        ('basic_data', '0010_delete_documentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('advance_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='代墊款單號')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='金額合計')),
                ('description', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_posted', models.BooleanField(default=False, verbose_name='已拋轉傳票')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
            ],
            options={
                'verbose_name': '代墊款',
                'verbose_name_plural': '代墊款',
                'ordering': ['-date', '-advance_no'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_customer_absorbed', models.BooleanField(default=True, verbose_name='客戶吸收')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='事由')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='代墊費用')),
                ('is_billed', models.BooleanField(default=False, verbose_name='是否已發單')),
                ('payment_type', models.CharField(blank=True, choices=[('POSTAGE', '郵資及快遞'), ('GROUP_INVOICE', '統購發票'), ('TAX', '稅款'), ('SUPPLEMENTARY_PREMIUM', '補充保費'), ('GOV_FEE', '政府規費'), ('RETAIL_INVOICE', '零買發票'), ('SEAL', '印章')], max_length=50, null=True, verbose_name='代墊類型')),
                ('advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='administrative.advancepayment', verbose_name='代墊款主檔')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_data.customer', verbose_name='費用歸屬')),
            ],
            options={
                'verbose_name': '代墊款明細',
                'verbose_name_plural': '代墊款明細',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePaymentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image', models.ImageField(upload_to='advance_payments/%Y/%m/', verbose_name='圖片檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administrative.advancepayment', verbose_name='代墊款')),
            ],
            options={
                'verbose_name': '代墊款夾檔圖片',
                'verbose_name_plural': '代墊款夾檔圖片',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdvancePayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('advance_no', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='代墊款單號')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='金額合計')),
                ('description', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_posted', models.BooleanField(default=False, verbose_name='已拋轉傳票')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applicant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 代墊款',
                'verbose_name_plural': 'historical 代墊款',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAdvancePaymentDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('is_customer_absorbed', models.BooleanField(default=True, verbose_name='客戶吸收')),
                ('unified_business_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='事由')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='代墊費用')),
                ('is_billed', models.BooleanField(default=False, verbose_name='是否已發單')),
                ('payment_type', models.CharField(blank=True, choices=[('POSTAGE', '郵資及快遞'), ('GROUP_INVOICE', '統購發票'), ('TAX', '稅款'), ('SUPPLEMENTARY_PREMIUM', '補充保費'), ('GOV_FEE', '政府規費'), ('RETAIL_INVOICE', '零買發票'), ('SEAL', '印章')], max_length=50, null=True, verbose_name='代墊類型')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('advance_payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrative.advancepayment', verbose_name='代墊款主檔')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basic_data.customer', verbose_name='費用歸屬')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 代墊款明細',
                'verbose_name_plural': 'historical 代墊款明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAdvancePaymentImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('image', models.TextField(max_length=100, verbose_name='圖片檔案')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False, verbose_name='上傳時間')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('advance_payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrative.advancepayment', verbose_name='代墊款')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 代墊款夾檔圖片',
                'verbose_name_plural': 'historical 代墊款夾檔圖片',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
