# Generated by Django 6.0.2 on 2026-03-24 14:14

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0012_advancepayment_advancepaymentdetail_and_more'),
        ('basic_data', '0014_historicalserviceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreceipt',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentReceipt',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now, verbose_name='收文日期')),
                ('subject', models.CharField(max_length=255, verbose_name='信件主旨')),
                ('category', models.CharField(blank=True, choices=[('營業稅憑證', '營業稅憑證'), ('會計帳冊', '會計帳冊'), ('補寄憑證', '補寄憑證'), ('國稅局公文', '國稅局公文'), ('經濟部公文', '經濟部公文'), ('法院公文', '法院公文'), ('其他公文', '其他公文'), ('事務所信件', '事務所信件'), ('事務所帳單', '事務所帳單'), ('各類函證', '各類函證'), ('其他', '其他')], max_length=50, null=True, verbose_name='信件分類')),
                ('status', models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已結案', '已結案')], default='待處理', max_length=20, verbose_name='處理狀態')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='附件')),
                ('is_line_notified', models.BooleanField(default=False, verbose_name='Line 通知狀態')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basic_data.customer', verbose_name='客戶')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 收文紀錄',
                'verbose_name_plural': 'historical 收文紀錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
