# Generated by Django 6.0.2 on 2026-03-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0014_documentreceiptattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrsAuditNoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='irs_audit_notices/%Y/%m/', verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrative.irsauditnotice', verbose_name='查帳通知')),
            ],
            options={
                'verbose_name': '查帳通知附件',
                'verbose_name_plural': '查帳通知附件',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
