# Generated by Django 6.0.2 on 2026-03-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0017_sealprocurement_is_advance_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdispatch',
            name='transferred_advance_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_dispatches', to='administrative.advancepayment', verbose_name='已拋轉代墊款'),
        ),
        migrations.AddField(
            model_name='historicaldocumentdispatch',
            name='transferred_advance_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administrative.advancepayment', verbose_name='已拋轉代墊款'),
        ),
        migrations.AlterField(
            model_name='sealprocurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='sealprocurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
