# Generated by Django 6.0.2 on 2026-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0018_documentdispatch_transferred_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentdetail',
            name='is_registration_case',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='登記案件'),
        ),
        migrations.AddField(
            model_name='historicaladvancepaymentdetail',
            name='is_registration_case',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True, verbose_name='登記案件'),
        ),
    ]
