# Generated by Django 6.0.2 on 2026-04-23 00:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0019_add_is_registration_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTaxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('title', models.CharField(max_length=200, verbose_name='事件標題')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('urgent_days', models.IntegerField(default=14, help_text='距截止日幾天內顯示緊急標記', verbose_name='緊急天數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '客戶行事曆事件',
                'verbose_name_plural': '客戶行事曆事件',
                'ordering': ['deadline', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalClientTaxEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('title', models.CharField(max_length=200, verbose_name='事件標題')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('urgent_days', models.IntegerField(default=14, help_text='距截止日幾天內顯示緊急標記', verbose_name='緊急天數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 客戶行事曆事件',
                'verbose_name_plural': 'historical 客戶行事曆事件',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
