# Generated by Django 6.0.2 on 2026-05-08 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0020_client_tax_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalirsauditnotice',
            name='attributable_year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='歸屬年度'),
        ),
        migrations.AlterField(
            model_name='historicalirsauditnotice',
            name='receipt_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='收文日期'),
        ),
        migrations.AlterField(
            model_name='historicalirsauditnotice',
            name='status',
            field=models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已結案', '已結案')], db_index=True, default='待處理', max_length=20, verbose_name='處理狀態'),
        ),
        migrations.AlterField(
            model_name='historicalirsauditnotice',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='historicalsystembulletin',
            name='publish_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='公佈日期', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='historicalsystembulletin',
            name='status',
            field=models.CharField(choices=[('active', '生效'), ('inactive', '失效')], db_index=True, default='active', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='irsauditnotice',
            name='attributable_year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='歸屬年度'),
        ),
        migrations.AlterField(
            model_name='irsauditnotice',
            name='receipt_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='收文日期'),
        ),
        migrations.AlterField(
            model_name='irsauditnotice',
            name='status',
            field=models.CharField(choices=[('待處理', '待處理'), ('處理中', '處理中'), ('已結案', '已結案')], db_index=True, default='待處理', max_length=20, verbose_name='處理狀態'),
        ),
        migrations.AlterField(
            model_name='irsauditnotice',
            name='tax_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='systembulletin',
            name='publish_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='公佈日期', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='systembulletin',
            name='status',
            field=models.CharField(choices=[('active', '生效'), ('inactive', '失效')], db_index=True, default='active', max_length=20, verbose_name='狀態'),
        ),
    ]
