# Generated by Django 6.0.2 on 2026-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0021_alter_historicalirsauditnotice_attributable_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdispatchitem',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentdispatchitem',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='documentdispatchitem',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentdispatchitem',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='收件人'),
        ),
    ]
