# Generated by Django 6.0.2 on 2026-07-01 08:36

from django.db import migrations, models


def merge_guahao_into_youju(apps, schema_editor):
    """'掛號' 與 '郵局' 語意相同，統一為 '郵局'（含歷史紀錄表）。"""
    DocumentDispatch = apps.get_model('administrative', 'DocumentDispatch')
    HistoricalDocumentDispatch = apps.get_model('administrative', 'HistoricalDocumentDispatch')
    DocumentDispatch.objects.filter(dispatch_method='掛號').update(dispatch_method='郵局')
    HistoricalDocumentDispatch.objects.filter(dispatch_method='掛號').update(dispatch_method='郵局')


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0022_remove_documentdispatchitem_recipient_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_guahao_into_youju, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentdispatch',
            name='dispatch_method',
            field=models.CharField(choices=[('郵局', '郵局'), ('快遞', '快遞'), ('親送', '親送'), ('其他', '其他')], default='郵局', max_length=20, verbose_name='發信方式'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentdispatch',
            name='dispatch_method',
            field=models.CharField(choices=[('郵局', '郵局'), ('快遞', '快遞'), ('親送', '親送'), ('其他', '其他')], default='郵局', max_length=20, verbose_name='發信方式'),
        ),
    ]
