# Generated by Django 6.0.2 on 2026-07-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0023_alter_documentdispatch_dispatch_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsealprocurementitem',
            name='seal_type',
            field=models.CharField(choices=[('large_self', '大章(自留)'), ('small_self', '小章(自留)'), ('large_reg', '大章(登記)'), ('small_reg', '小章(登記)'), ('invoice', '發票章'), ('ticket_cert', '購票證'), ('natural_person_cert', '自然人憑證')], default='large_self', max_length=20, verbose_name='印章種類'),
        ),
        migrations.AlterField(
            model_name='sealprocurementitem',
            name='seal_type',
            field=models.CharField(choices=[('large_self', '大章(自留)'), ('small_self', '小章(自留)'), ('large_reg', '大章(登記)'), ('small_reg', '小章(登記)'), ('invoice', '發票章'), ('ticket_cert', '購票證'), ('natural_person_cert', '自然人憑證')], default='large_self', max_length=20, verbose_name='印章種類'),
        ),
    ]
