# Generated by Django 6.0.2 on 2026-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0024_alter_historicalsealprocurementitem_seal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdispatchitem',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='郵遞區號'),
        ),
        migrations.AddField(
            model_name='historicaldocumentdispatchitem',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='郵遞區號'),
        ),
    ]
