# Generated by Django 6.0.2 on 2026-05-05 06:00

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('role', models.CharField(blank=True, max_length=80, verbose_name='職稱')),
                ('bio', models.TextField(blank=True, verbose_name='簡介')),
                ('avatar_initial', models.CharField(blank=True, max_length=4, verbose_name='頭像文字（如「林」）')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='分類名稱')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='說明')),
            ],
            options={
                'verbose_name': '部落格分類',
                'verbose_name_plural': '部落格分類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_jp', models.CharField(blank=True, default='勤信季刊', max_length=80, verbose_name='日文標題')),
                ('intro_en', models.CharField(blank=True, default='QUARTERLY', max_length=80, verbose_name='英文副標')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='主標題（可含 <em> 強調）')),
                ('hero_sub', models.TextField(blank=True, verbose_name='副標說明')),
            ],
            options={
                'verbose_name': '部落格首頁',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('cover_caption', models.CharField(blank=True, max_length=200, verbose_name='封面圖說')),
                ('lead', models.TextField(blank=True, verbose_name='導言（出現在標題下方）')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('subheading', 3), ('paragraph', 4), ('news_clip', 10), ('editor_take', 13), ('stat_callout', 18), ('cpa_note', 21), ('timeline', 27), ('figure', 30), ('table', 33)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '編號（如 01）', 'max_length': 8, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': '標題文字', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('text', 1)]], {}), 3: ('modules.blog.blocks.SubHeadingBlock', (), {}), 4: ('modules.blog.blocks.ParagraphBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'label': '新聞來源', 'max_length': 80, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': '日期', 'max_length': 40, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': '新聞標題', 'max_length': 200, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'label': '引言內容', 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'label': '原文連結', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('source', 5), ('date', 6), ('title', 7), ('quote', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'label': '勤信觀點內容', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': '署名', 'max_length': 80, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('body', 11), ('sign', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': '主要數字', 'max_length': 20, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'label': '單位（%、萬等）', 'max_length': 20, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'label': '說明文字', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'label': '資料來源', 'max_length': 120, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('number', 14), ('unit', 15), ('text', 16), ('source', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': '會計師補充', 'label': '標籤', 'max_length': 40, 'required': False}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': '補充內容', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('label', 19), ('body', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 24: ('wagtail.blocks.TextBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('date', 22), ('title', 23), ('desc', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'label': '時間軸項目'}), 27: ('wagtail.blocks.StructBlock', [[('items', 26)]], {}), 28: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'label': '圖說', 'max_length': 200, 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('image', 28), ('caption', 29)]], {}), 31: ('wagtail.blocks.CharBlock', (), {'help_text': '例：項目|稅前|稅後', 'label': '表頭（以 | 分隔）', 'required': True}), 32: ('wagtail.blocks.TextBlock', (), {'label': '內容列（每行一列，欄位以 | 分隔）', 'required': True}), 33: ('wagtail.blocks.StructBlock', [[('headers', 31), ('rows', 32)]], {})}, verbose_name='內文')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='顯示日期')),
                ('read_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='閱讀分鐘數')),
                ('authors', modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.author', verbose_name='作者')),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogcategory', verbose_name='分類')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='封面圖')),
            ],
            options={
                'verbose_name': '部落格文章',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpostpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
