# Generated by Django 6.0.2 on 2026-06-17 12:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('subheading', 3), ('paragraph', 4), ('news_clip', 10), ('editor_take', 13), ('stat_callout', 18), ('cpa_note', 21), ('timeline', 27), ('figure', 30), ('table', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '編號（如 01）', 'max_length': 8, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': '標題文字', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('text', 1)]], {}), 3: ('modules.blog.blocks.SubHeadingBlock', (), {}), 4: ('modules.blog.blocks.ParagraphBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'label': '新聞來源', 'max_length': 80, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': '日期', 'max_length': 40, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': '新聞標題', 'max_length': 200, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'label': '引言內容', 'required': True}), 9: ('wagtail.blocks.URLBlock', (), {'label': '原文連結', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('source', 5), ('date', 6), ('title', 7), ('quote', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'label': '勤信觀點內容', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': '署名', 'max_length': 80, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('body', 11), ('sign', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': '主要數字', 'max_length': 20, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'label': '單位（%、萬等）', 'max_length': 20, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'label': '說明文字', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'label': '資料來源', 'max_length': 120, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('number', 14), ('unit', 15), ('text', 16), ('source', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': '會計師補充', 'label': '標籤', 'max_length': 40, 'required': False}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': '補充內容', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('label', 19), ('body', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 24: ('wagtail.blocks.TextBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('date', 22), ('title', 23), ('desc', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'label': '時間軸項目'}), 27: ('wagtail.blocks.StructBlock', [[('items', 26)]], {}), 28: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 29: ('wagtail.blocks.CharBlock', (), {'label': '圖說', 'max_length': 200, 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('image', 28), ('caption', 29)]], {}), 31: ('modules.blog.blocks.ArticleTableBlock', (), {'table_options': {'autoColumnSize': False, 'colHeaders': True, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo'], 'editor': 'text', 'height': 240, 'language': 'zh-TW', 'manualColumnResize': True, 'minSpareRows': 0, 'renderer': 'html', 'rowHeaders': True, 'startCols': 3, 'startRows': 3, 'stretchH': 'last'}})}, verbose_name='內文'),
        ),
    ]
