# Generated by Django 6.0.2 on 2026-05-02 14:01

import django.db.models.deletion
import pgvector.django.vector
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0005_alter_case_category_alter_casetasktemplate_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalKnowledgeEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('question_summary', models.TextField(verbose_name='問題摘要')),
                ('answer_summary', models.TextField(verbose_name='回答摘要')),
                ('category', models.CharField(choices=[('tax_filing', '稅務申報'), ('invoice', '發票管理'), ('payroll', '薪資勞健保'), ('financial', '財務報表'), ('incorporation', '公司設立'), ('other', '其他')], default='other', max_length=20, verbose_name='類別')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='向量')),
                ('embedding_model', models.CharField(blank=True, default='text-embedding-004', max_length=100)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('internal', '僅內部'), ('public', '客戶可見')], default='internal', max_length=10, verbose_name='可見範圍')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期限')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已審核')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case_management.case', verbose_name='來源案件')),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='審核者')),
            ],
            options={
                'verbose_name': 'historical 知識條目',
                'verbose_name_plural': 'historical 知識條目',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('question_summary', models.TextField(verbose_name='問題摘要')),
                ('answer_summary', models.TextField(verbose_name='回答摘要')),
                ('category', models.CharField(choices=[('tax_filing', '稅務申報'), ('invoice', '發票管理'), ('payroll', '薪資勞健保'), ('financial', '財務報表'), ('incorporation', '公司設立'), ('other', '其他')], default='other', max_length=20, verbose_name='類別')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='向量')),
                ('embedding_model', models.CharField(blank=True, default='text-embedding-004', max_length=100)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('internal', '僅內部'), ('public', '客戶可見')], default='internal', max_length=10, verbose_name='可見範圍')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期限')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已審核')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('source_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_knowledge', to='case_management.case', verbose_name='來源案件')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_knowledge', to=settings.AUTH_USER_MODEL, verbose_name='審核者')),
            ],
            options={
                'verbose_name': '知識條目',
                'verbose_name_plural': '知識條目',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_verified'], name='knowledge_b_categor_e12826_idx'), models.Index(fields=['visibility', 'is_verified'], name='knowledge_b_visibil_53f089_idx')],
            },
        ),
    ]
