# Generated by Django 6.0.2 on 2026-05-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalknowledgeentry',
            name='checklist',
            field=models.TextField(blank=True, help_text='每行一個項目', verbose_name='準備清單'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='checklist',
            field=models.TextField(blank=True, help_text='每行一個項目', verbose_name='準備清單'),
        ),
    ]
