# Generated by Django 6.0.2 on 2026-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_add_checklist_to_knowledgeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalknowledgeentry',
            name='category',
            field=models.CharField(choices=[('tax_filing', '稅務申報'), ('invoice', '發票管理'), ('payroll', '薪資勞健保'), ('financial', '財務報表'), ('accounting', '會計處理'), ('incorporation', '公司登記'), ('inheritance', '遺產贈與'), ('other', '其他')], default='other', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='category',
            field=models.CharField(choices=[('tax_filing', '稅務申報'), ('invoice', '發票管理'), ('payroll', '薪資勞健保'), ('financial', '財務報表'), ('accounting', '會計處理'), ('incorporation', '公司登記'), ('inheritance', '遺產贈與'), ('other', '其他')], default='other', max_length=20, verbose_name='類別'),
        ),
    ]
