# Generated by Django 6.0.2 on 2026-05-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_historicalinquiry_inquiry'),
        ('knowledge_base', '0003_add_category_choices'),
        ('registration', '0041_vat_entity_change_closed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalknowledgeentry',
            name='domain',
            field=models.CharField(choices=[('case_qa', '案件問答'), ('registration', '登記業務'), ('tax_sop', '稅務 SOP'), ('general', '通用知識')], default='case_qa', help_text='上層分流，避免不同業務的知識在檢索時混在一起', max_length=20, verbose_name='知識領域'),
        ),
        migrations.AddField(
            model_name='historicalknowledgeentry',
            name='source_registration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.companyfiling', verbose_name='來源登記案'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='domain',
            field=models.CharField(choices=[('case_qa', '案件問答'), ('registration', '登記業務'), ('tax_sop', '稅務 SOP'), ('general', '通用知識')], default='case_qa', help_text='上層分流，避免不同業務的知識在檢索時混在一起', max_length=20, verbose_name='知識領域'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='source_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_knowledge', to='registration.companyfiling', verbose_name='來源登記案'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['domain', 'is_verified'], name='knowledge_b_domain_7f0ada_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['domain', 'category'], name='knowledge_b_domain_7bec5a_idx'),
        ),
    ]
