# Generated by Django 6.0.2 on 2026-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_historicalknowledgeentry_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalknowledgeentry',
            name='category',
            field=models.CharField(choices=[('tax_filing', '稅務申報'), ('invoice', '發票管理'), ('payroll', '薪資勞健保'), ('financial', '財務報表'), ('accounting', '會計處理'), ('incorporation', '公司登記'), ('inheritance', '遺產贈與'), ('inc_setup', '設立登記'), ('inc_change', '變更登記'), ('inc_dissolve', '解散/清算'), ('equity_tx', '股權交易'), ('vat_change', '營業人變更'), ('aml', '洗錢防制'), ('company_law_22_1', '公司法 22-1'), ('capital_change', '增資/減資'), ('merger', '合併'), ('split', '分割'), ('other_reg', '其他登記'), ('other', '其他')], default='other', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='category',
            field=models.CharField(choices=[('tax_filing', '稅務申報'), ('invoice', '發票管理'), ('payroll', '薪資勞健保'), ('financial', '財務報表'), ('accounting', '會計處理'), ('incorporation', '公司登記'), ('inheritance', '遺產贈與'), ('inc_setup', '設立登記'), ('inc_change', '變更登記'), ('inc_dissolve', '解散/清算'), ('equity_tx', '股權交易'), ('vat_change', '營業人變更'), ('aml', '洗錢防制'), ('company_law_22_1', '公司法 22-1'), ('capital_change', '增資/減資'), ('merger', '合併'), ('split', '分割'), ('other_reg', '其他登記'), ('other', '其他')], default='other', max_length=20, verbose_name='類別'),
        ),
    ]
