# Generated by Django 5.1.5 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(editable=False, help_text='自動生成，格式：西元年+序號（如：2026001）', max_length=10, unique=True, verbose_name='員工編號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別')),
                ('id_number', models.CharField(help_text='身分證字號須為唯一', max_length=10, unique=True, verbose_name='身分證字號')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='Line ID')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='分機號碼')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('employment_status', models.CharField(choices=[('ACTIVE', '在職'), ('RESIGNED', '離職'), ('ON_LEAVE', '留職停薪')], default='ACTIVE', max_length=20, verbose_name='在職狀態')),
                ('hire_date', models.DateField(verbose_name='到職日期')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='離職日期')),
                ('team', models.CharField(choices=[('A', 'A組'), ('B', 'B組')], max_length=1, verbose_name='組別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
                'ordering': ['-employee_number'],
            },
        ),
    ]
