# Generated by Django 5.1.5 on 2026-03-03 23:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('day_type', models.CharField(choices=[('national_holiday', '國定假日'), ('makeup_workday', '補班日')], max_length=20, verbose_name='日期類型')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='說明')),
                ('year', models.IntegerField(editable=False, verbose_name='年度')),
            ],
            options={
                'verbose_name': '工作日曆',
                'verbose_name_plural': '工作日曆',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='出勤日期')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='上班打卡')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='下班打卡')),
                ('source', models.CharField(choices=[('web', '網頁打卡'), ('line', 'Line 打卡'), ('makeup', '補卡')], default='web', max_length=10, verbose_name='打卡來源')),
                ('makeup_reason', models.TextField(blank=True, default='', help_text='補卡時必須填寫事由', verbose_name='補卡事由')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已核准')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='核准人')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='員工')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 出勤紀錄',
                'verbose_name_plural': 'historical 出勤紀錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkCalendar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('day_type', models.CharField(choices=[('national_holiday', '國定假日'), ('makeup_workday', '補班日')], max_length=20, verbose_name='日期類型')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='說明')),
                ('year', models.IntegerField(editable=False, verbose_name='年度')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 工作日曆',
                'verbose_name_plural': 'historical 工作日曆',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='出勤日期')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='上班打卡')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='下班打卡')),
                ('source', models.CharField(choices=[('web', '網頁打卡'), ('line', 'Line 打卡'), ('makeup', '補卡')], default='web', max_length=10, verbose_name='打卡來源')),
                ('makeup_reason', models.TextField(blank=True, default='', help_text='補卡時必須填寫事由', verbose_name='補卡事由')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已核准')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL, verbose_name='核准人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '出勤紀錄',
                'verbose_name_plural': '出勤紀錄',
                'ordering': ['-date', 'employee__employee_number'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date_attendance')],
            },
        ),
    ]
