# Generated by Django 5.1.5 on 2026-03-04 00:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_workcalendar_historicalattendancerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='假別代碼')),
                ('name', models.CharField(max_length=50, verbose_name='假別名稱')),
                ('is_paid', models.BooleanField(default=True, verbose_name='有薪假')),
                ('max_hours_per_year', models.DecimalField(blank=True, decimal_places=1, help_text='留空代表無上限或由人工給予', max_digits=6, null=True, verbose_name='年度上限(小時)')),
                ('requires_doc', models.BooleanField(default=False, help_text='是否需要上傳附件/證明文件', verbose_name='需附證明')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '假別設定',
                'verbose_name_plural': '假別設定',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeaveType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='假別代碼')),
                ('name', models.CharField(max_length=50, verbose_name='假別名稱')),
                ('is_paid', models.BooleanField(default=True, verbose_name='有薪假')),
                ('max_hours_per_year', models.DecimalField(blank=True, decimal_places=1, help_text='留空代表無上限或由人工給予', max_digits=6, null=True, verbose_name='年度上限(小時)')),
                ('requires_doc', models.BooleanField(default=False, help_text='是否需要上傳附件/證明文件', verbose_name='需附證明')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 假別設定',
                'verbose_name_plural': 'historical 假別設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('start_datetime', models.DateTimeField(verbose_name='開始時間')),
                ('end_datetime', models.DateTimeField(verbose_name='結束時間')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='請假時數')),
                ('reason', models.TextField(verbose_name='請假事由')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已駁回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/%Y/%m/', verbose_name='附件')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='核准人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='員工')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype', verbose_name='假別')),
            ],
            options={
                'verbose_name': '請假單',
                'verbose_name_plural': '請假單',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeaveRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('start_datetime', models.DateTimeField(verbose_name='開始時間')),
                ('end_datetime', models.DateTimeField(verbose_name='結束時間')),
                ('total_hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='請假時數')),
                ('reason', models.TextField(verbose_name='請假事由')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已駁回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='附件')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='核准人')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='員工')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.leavetype', verbose_name='假別')),
            ],
            options={
                'verbose_name': 'historical 請假單',
                'verbose_name_plural': 'historical 請假單',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLeaveBalance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('entitled_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='應有時數')),
                ('used_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='已使用時數')),
                ('manually_granted', models.BooleanField(default=False, help_text='如喪假等由管理員手動給予', verbose_name='人工給假')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='員工')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.leavetype', verbose_name='假別')),
            ],
            options={
                'verbose_name': 'historical 假期餘額',
                'verbose_name_plural': 'historical 假期餘額',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('entitled_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='應有時數')),
                ('used_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='已使用時數')),
                ('manually_granted', models.BooleanField(default=False, help_text='如喪假等由管理員手動給予', verbose_name='人工給假')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee', verbose_name='員工')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype', verbose_name='假別')),
            ],
            options={
                'verbose_name': '假期餘額',
                'verbose_name_plural': '假期餘額',
                'ordering': ['employee', 'leave_type'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_year')],
            },
        ),
    ]
