# Generated by Django 5.1.5 on 2026-03-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_historicalovertimerecord_historicalpayrollrecord_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leavebalance',
            name='unique_employee_leave_year',
        ),
        migrations.AddField(
            model_name='historicalleavebalance',
            name='period_end',
            field=models.DateField(blank=True, help_text='假期有效截止日', null=True, verbose_name='到期日'),
        ),
        migrations.AddField(
            model_name='historicalleavebalance',
            name='period_start',
            field=models.DateField(blank=True, help_text='假期有效起始日', null=True, verbose_name='生效日'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='period_end',
            field=models.DateField(blank=True, help_text='假期有效截止日', null=True, verbose_name='到期日'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='period_start',
            field=models.DateField(blank=True, help_text='假期有效起始日', null=True, verbose_name='生效日'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year', 'period_start'), name='unique_employee_leave_period'),
        ),
    ]
