# Generated by Django 5.1.5 on 2026-03-05 04:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('level_name', models.CharField(help_text='例如：第 1 級', max_length=50, verbose_name='級別名稱')),
                ('insured_salary', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='投保薪資')),
                ('labor_employee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞保-自付')),
                ('health_employee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='健保-自付')),
                ('labor_employer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞保-雇主')),
                ('health_employer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='健保-雇主')),
                ('pension_employer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞退-雇主')),
                ('occupational_hazard', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='職災費')),
                ('wage_arrears', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='工資墊償')),
            ],
            options={
                'verbose_name': '勞健保投保級距',
                'verbose_name_plural': '勞健保投保級距',
                'ordering': ['insured_salary'],
            },
        ),
        migrations.AddField(
            model_name='historicalsalarystructure',
            name='health_insurance_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='健保費_雇主負擔'),
        ),
        migrations.AddField(
            model_name='historicalsalarystructure',
            name='labor_insurance_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞保費_雇主負擔'),
        ),
        migrations.AddField(
            model_name='historicalsalarystructure',
            name='occupational_hazard_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='職災費'),
        ),
        migrations.AddField(
            model_name='historicalsalarystructure',
            name='pension_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='退休金_雇主負擔'),
        ),
        migrations.AddField(
            model_name='historicalsalarystructure',
            name='wage_arrears_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='工資墊償金'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='health_insurance_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='健保費_雇主負擔'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='labor_insurance_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞保費_雇主負擔'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='occupational_hazard_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='職災費'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pension_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='退休金_雇主負擔'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='wage_arrears_employer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='工資墊償金'),
        ),
        migrations.CreateModel(
            name='HistoricalInsuranceBracket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('level_name', models.CharField(help_text='例如：第 1 級', max_length=50, verbose_name='級別名稱')),
                ('insured_salary', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='投保薪資')),
                ('labor_employee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞保-自付')),
                ('health_employee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='健保-自付')),
                ('labor_employer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞保-雇主')),
                ('health_employer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='健保-雇主')),
                ('pension_employer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='勞退-雇主')),
                ('occupational_hazard', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='職災費')),
                ('wage_arrears', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='工資墊償')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 勞健保投保級距',
                'verbose_name_plural': 'historical 勞健保投保級距',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
