# Generated by Django 5.1.5 on 2026-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_insurancebracket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayrollrecord',
            name='late_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='遲到扣款'),
        ),
        migrations.AddField(
            model_name='historicalpayrollrecord',
            name='missing_punch_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='缺卡扣款'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='late_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='遲到扣款'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='missing_punch_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='缺卡扣款'),
        ),
        migrations.AlterField(
            model_name='historicalpayrollrecord',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='請假扣款'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='請假扣款'),
        ),
    ]
