# Generated by Django 5.1.5 on 2026-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_historicalpayrollrecord_late_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayrollrecord',
            name='advance_payment_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='代墊款扣除'),
        ),
        migrations.AddField(
            model_name='historicalpayrollrecord',
            name='bonus_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='獎金/年終/績效'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='advance_payment_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='代墊款扣除'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bonus_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='獎金/年終/績效'),
        ),
    ]
