# Generated by Django 5.1.5 on 2026-03-05 06:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_historicalpayrollrecord_advance_payment_deduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date_applied', models.DateField(verbose_name='申請日期')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='代墊金額')),
                ('reason', models.TextField(verbose_name='代墊事由')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('approved', '已核准 (待發放)'), ('deducted', '已發放 (依附薪資單)'), ('rejected', '已駁回')], default='pending', max_length=20, verbose_name='狀態')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已核准')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advance_payments', to=settings.AUTH_USER_MODEL, verbose_name='核准人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='hr.employee', verbose_name='申請人')),
                ('payroll_record', models.ForeignKey(blank=True, help_text='綁定薪資單，當薪資單確認時自動轉為已發放。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_advance_payments', to='hr.payrollrecord', verbose_name='發放於哪期薪資單')),
            ],
            options={
                'verbose_name': '代墊款申請',
                'verbose_name_plural': '代墊款申請',
                'ordering': ['-date_applied', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdvancePayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('date_applied', models.DateField(verbose_name='申請日期')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='代墊金額')),
                ('reason', models.TextField(verbose_name='代墊事由')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('approved', '已核准 (待發放)'), ('deducted', '已發放 (依附薪資單)'), ('rejected', '已駁回')], default='pending', max_length=20, verbose_name='狀態')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已核准')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='核准人')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='申請人')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_record', models.ForeignKey(blank=True, db_constraint=False, help_text='綁定薪資單，當薪資單確認時自動轉為已發放。', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.payrollrecord', verbose_name='發放於哪期薪資單')),
            ],
            options={
                'verbose_name': 'historical 代墊款申請',
                'verbose_name_plural': 'historical 代墊款申請',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
