# Generated by Django 5.1.5 on 2026-03-05 15:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_advancepayment_historicaladvancepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleavebalance',
            name='is_carried_over',
            field=models.BooleanField(default=False, help_text='是否已將未用完的天數結轉為下一年度的遞延特休', verbose_name='已結轉遞延'),
        ),
        migrations.AddField(
            model_name='historicalleavebalance',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='是否已將到期未用完的遞延特休折算為薪資', verbose_name='已折算薪資'),
        ),
        migrations.AddField(
            model_name='historicalpayrollrecord',
            name='leave_settlement_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='特休折算薪資'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='is_carried_over',
            field=models.BooleanField(default=False, help_text='是否已將未用完的天數結轉為下一年度的遞延特休', verbose_name='已結轉遞延'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='是否已將到期未用完的遞延特休折算為薪資', verbose_name='已折算薪資'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='leave_settlement_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='特休折算薪資'),
        ),
        migrations.AlterField(
            model_name='historicalpayrollrecord',
            name='advance_payment_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='代墊款歸還'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='advance_payment_deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='代墊款歸還'),
        ),
        migrations.CreateModel(
            name='HistoricalLeaveSettlementRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新時間')),
                ('date_settled', models.DateField(blank=True, editable=False, verbose_name='結算日期')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='折算時數')),
                ('hourly_rate', models.DecimalField(decimal_places=0, help_text='結算當時的時薪', max_digits=10, verbose_name='時薪')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='折算金額')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='員工')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_balance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.leavebalance', verbose_name='來源假期餘額')),
                ('payroll_record', models.ForeignKey(blank=True, db_constraint=False, help_text='綁定薪資單，確認已發放', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.payrollrecord', verbose_name='發放於哪期薪資單')),
            ],
            options={
                'verbose_name': 'historical 特休折算紀錄',
                'verbose_name_plural': 'historical 特休折算紀錄',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveSettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date_settled', models.DateField(auto_now_add=True, verbose_name='結算日期')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='折算時數')),
                ('hourly_rate', models.DecimalField(decimal_places=0, help_text='結算當時的時薪', max_digits=10, verbose_name='時薪')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='折算金額')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_settlements', to='hr.employee', verbose_name='員工')),
                ('leave_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_record', to='hr.leavebalance', verbose_name='來源假期餘額')),
                ('payroll_record', models.ForeignKey(blank=True, help_text='綁定薪資單，確認已發放', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_settlements', to='hr.payrollrecord', verbose_name='發放於哪期薪資單')),
            ],
            options={
                'verbose_name': '特休折算紀錄',
                'verbose_name_plural': '特休折算紀錄',
                'ordering': ['-date_settled'],
            },
        ),
    ]
