# Generated by Django 6.0.2 on 2026-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_historicalleavebalance_is_carried_over_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', '在職'), ('RESIGNED', '離職'), ('ON_LEAVE', '留職停薪')], db_index=True, default='ACTIVE', max_length=20, verbose_name='在職狀態'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='姓名'),
        ),
    ]
