# Generated by Django 6.0.2 on 2026-06-26 15:14
#
# 加班紀錄改為以「分鐘」為單位、加班費依級距加權計算。
# 此 migration 先新增 minutes 欄位，把既有 hours 換算成 minutes（×60，四捨五入），
# 再移除舊的 hours / rate 欄位，確保既有加班資料不遺失。

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def copy_hours_to_minutes(apps, schema_editor):
    """既有資料：minutes = round(hours × 60)。含歷史表與軟刪除資料。"""
    for model_name in ('OvertimeRecord', 'HistoricalOvertimeRecord'):
        Model = apps.get_model('hr', model_name)
        for rec in Model.objects.all():
            hours = rec.hours or Decimal('0')
            rec.minutes = int((Decimal(hours) * 60).quantize(Decimal('1'), rounding=ROUND_HALF_UP))
            rec.save(update_fields=['minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_leavetype_pay_rate'),
    ]

    operations = [
        # 1. 先新增 minutes 欄位
        migrations.AddField(
            model_name='historicalovertimerecord',
            name='minutes',
            field=models.PositiveIntegerField(default=0, help_text='當日加班總分鐘數，系統會依日期自動分類並依級距加權計算加班費', verbose_name='加班分鐘'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='minutes',
            field=models.PositiveIntegerField(default=0, help_text='當日加班總分鐘數，系統會依日期自動分類並依級距加權計算加班費', verbose_name='加班分鐘'),
        ),
        # 2. 把既有 hours 換算填入 minutes
        migrations.RunPython(copy_hours_to_minutes, migrations.RunPython.noop),
        # 3. 移除舊欄位
        migrations.RemoveField(
            model_name='historicalovertimerecord',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='historicalovertimerecord',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='overtimerecord',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='overtimerecord',
            name='rate',
        ),
    ]
