# Generated by Django 5.1.5 on 2026-02-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='顯示名稱')),
                ('url_name', models.CharField(blank=True, help_text="Django URL pattern name (e.g. 'dashboard') or absolute URL", max_length=100, verbose_name='URL 名稱')),
                ('icon_svg', models.TextField(blank=True, help_text='Paste the full <svg> code here', verbose_name='SVG 圖示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system_config.menuitem', verbose_name='父層選單')),
                ('roles', models.ManyToManyField(blank=True, help_text='留空則對所有登入使用者可見', to='auth.group', verbose_name='可見角色')),
            ],
            options={
                'verbose_name': '選單項目',
                'verbose_name_plural': '選單管理',
                'ordering': ['order'],
            },
        ),
    ]
