# Generated by Django 5.1.5 on 2026-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key, e.g. EMAIL_HOST', max_length=50, unique=True, verbose_name='參數鍵名')),
                ('value', models.TextField(blank=True, verbose_name='參數值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('is_secret', models.BooleanField(default=False, help_text='If true, value will be masked in UI', verbose_name='是否加密/隱藏')),
                ('group', models.CharField(choices=[('email', 'Email'), ('payment', 'Payment (ECPay)'), ('line', 'Line'), ('ai', 'AI (Gemini)'), ('other', 'Other')], default='other', max_length=20, verbose_name='群組')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系統參數',
                'verbose_name_plural': '系統參數設定',
                'ordering': ['group', 'key'],
            },
        ),
    ]
