# Generated by Django 6.0.2 on 2026-04-15 01:04

from django.db import migrations

# URL prefixes that belong to the HR module
HR_URL_PREFIXES = ('hr:',)

# Groups that can access the HR module
HR_GROUPS = ['CPA', 'management', 'Admin', '人資組']

# Groups that can access business modules
BUSINESS_GROUPS = ['CPA', 'management', 'Admin', 'A組', 'B組', 'C組']

# Items with no url_name (section headers) — classified by their title
# We identify them by their children's url prefixes instead.
HR_SECTION_TITLES = ['人力資源']


def assign_menu_roles(apps, _schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')
    Group = apps.get_model('auth', 'Group')

    # Build group lookup
    hr_groups = list(Group.objects.filter(name__in=HR_GROUPS))
    business_groups = list(Group.objects.filter(name__in=BUSINESS_GROUPS))

    all_items = list(MenuItem.objects.prefetch_related('roles').all())

    for item in all_items:
        # Dashboard — leave open (no roles required)
        if item.url_name == 'dashboard' or (not item.url_name and not item.parent_id):
            # Root section headers handled below; dashboard stays open
            if item.url_name == 'dashboard':
                item.roles.clear()
                continue

        # Determine if this item is HR or business based on url_name
        if item.url_name and any(item.url_name.startswith(p) for p in HR_URL_PREFIXES):
            item.roles.set(hr_groups)
        elif item.url_name:
            # All other named items → business
            item.roles.set(business_groups)
        else:
            # Section header (no url_name) — classify by title
            if item.title in HR_SECTION_TITLES:
                item.roles.set(hr_groups)
            else:
                # Dashboard root has no url_name too, but it's the only one
                # without a parent that isn't a section — skip if no parent
                # (shouldn't reach here for Dashboard since url_name='dashboard')
                item.roles.set(business_groups)


def remove_menu_roles(apps, _schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')
    for item in MenuItem.objects.all():
        item.roles.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_add_period_menu_item'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_add_permission_groups'),   # groups must exist first
    ]

    operations = [
        migrations.RunPython(assign_menu_roles, remove_menu_roles),
    ]
