# Generated by Django 6.0.2 on 2026-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0004_assign_menu_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='required_permission',
            field=models.CharField(blank=True, help_text='格式：app_label.codename，例如 hr.view_employee。設定後以此 permission 取代 roles 判斷。', max_length=100, verbose_name='需要的 Permission'),
        ),
    ]
