# Generated by Django 6.0.2 on 2026-04-15 15:41

from django.db import migrations

# Maps url_name → required Django permission (app_label.codename)
URL_PERMISSION_MAP = {
    # basic_data
    'basic_data:customer_list':         'basic_data.view_customer',
    'basic_data:contact_list':          'basic_data.view_contact',
    'basic_data:service_item_list':     'basic_data.view_serviceitem',
    # administrative
    'administrative:document_receipt_list':  'administrative.view_documentreceipt',
    'administrative:irs_audit_notice_list':  'administrative.view_irsauditnotice',
    'administrative:document_dispatch_list': 'administrative.view_documentdispatch',
    'administrative:seal_procurement_list':  'administrative.view_sealprocurement',
    'administrative:seal_inventory_report':  'administrative.view_sealprocurement',
    'administrative:system_bulletin_list':   'administrative.view_systembulletin',
    'administrative:advance_payment_list':   'administrative.view_advancepayment',
    # registration
    'registration:progress_list':            'registration.view_progress',
    'registration:client_assessment_list':   'registration.view_clientassessment',
    'registration:case_assessment_list':     'registration.view_caseassessment',
    'registration:shareholder_register_list':'registration.view_shareholderregister',
    'registration:shareholder_list':         'registration.view_shareholder',
    'registration:equity_transaction_list':  'registration.view_equitytransaction',
    'registration:company_filing_list':      'registration.view_companyfiling',
    'registration:vat_entity_change_list':   'registration.view_vatentitychange',
    # internal_accounting
    'internal_accounting:voucher_list':              'internal_accounting.view_voucher',
    'internal_accounting:account_list':              'internal_accounting.view_account',
    'internal_accounting:receivable_list':           'internal_accounting.view_receivable',
    'internal_accounting:collection_list':           'internal_accounting.view_collection',
    'internal_accounting:pre_collection_list':       'internal_accounting.view_precollection',
    'internal_accounting:fixed_asset_list':          'internal_accounting.view_fixedasset',
    'internal_accounting:period_list':               'internal_accounting.view_accountingperiod',
    'internal_accounting:report_journal':            'internal_accounting.view_voucher',
    'internal_accounting:report_general_ledger':     'internal_accounting.view_voucher',
    'internal_accounting:report_income_statement':   'internal_accounting.view_voucher',
    'internal_accounting:report_balance_sheet':      'internal_accounting.view_voucher',
    'internal_accounting:report_subsidiary_ledger':  'internal_accounting.view_voucher',
    'internal_accounting:report_withholding_tax':    'internal_accounting.view_voucher',
    'internal_accounting:report_fee_apportion':      'internal_accounting.view_receivable',
    # bookkeeping
    'bookkeeping:client_list':           'bookkeeping.view_bookkeepingclient',
    'bookkeeping:group_invoice_report':  'bookkeeping.view_groupinvoice',
    'bookkeeping:convenience_bag_list':  'bookkeeping.view_conveniencebaglog',
    'bookkeeping:business_tax_list':     'bookkeeping.view_vat',
    'bookkeeping:income_tax_list':       'bookkeeping.view_incometax',
    'bookkeeping:progress_list':         'bookkeeping.view_progress',
    'bookkeeping:bill_list':             'bookkeeping.view_clientbill',
    'bookkeeping:industry_tax_rate_list':'bookkeeping.view_industrytaxrate',
    # hr
    'hr:employee_list':          'hr.view_employee',
    'hr:work_calendar_list':     'hr.view_workcalendar',
    'hr:advance_payment_list':   'hr.view_advancepayment',
    'hr:attendance_list':        'hr.view_attendancerecord',
    'hr:clock_in_out':           'hr.view_attendancerecord',
    'hr:leave_type_list':        'hr.view_leavetype',
    'hr:leave_balance_list':     'hr.view_leavebalance',
    'hr:leave_request_list':     'hr.view_leaverequest',
    'hr:salary_structure_list':  'hr.view_salarystructure',
    'hr:overtime_list':          'hr.view_overtimerecord',
    'hr:payroll_list':           'hr.view_payrollrecord',
    'hr:line_clock_simulate':    'hr.view_attendancerecord',
    'hr:insurance_bracket_list': 'hr.view_insurancebracket',
}


def set_required_permissions(apps, _schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')
    for item in MenuItem.objects.all():
        perm = URL_PERMISSION_MAP.get(item.url_name, '')
        if perm and not item.required_permission:
            item.required_permission = perm
            item.save(update_fields=['required_permission'])


def clear_required_permissions(apps, _schema_editor):
    MenuItem = apps.get_model('system_config', 'MenuItem')
    MenuItem.objects.update(required_permission='')


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0005_add_required_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='roles',
        ),
        migrations.RunPython(set_required_permissions, clear_required_permissions),
    ]
